### ISSUE TITLE
Pirate and trader stuck

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1021]
The pirate and the trader can get stuck forever. It can happen in other ship vs ship cases as well so it might be a good idea to make both the trader and the pirate give up after a while.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1021)
**Attachment**: [stuck_pirate_trader.sqlite](http://up.unknown-horizons.org/f/?id=199&n=stuck_pirate_trader.sqlite)
##

**Comment by AndyMender** [comment]
Seems to be related to: https://github.com/unknown-horizons/unknown-horizons/issues/967
