### ISSUE TITLE
Fix handling of automatically moving ships that get blocked.

### ISSUE THREAD

**Issue by totycro** [unknown-horizons/unknown-horizons#1023]
The current code base doesn't handle ships getting blocked well. See "Blocked by".

Solutions could be to make ships

a) go through other ships after no alternative path has been found after a few seconds/tries. this could be implemented for small ships, where it's not such a big problem visually.

b) do something different on a higher level (trader: find other trader partner, fisher: find other ship deposit). this does not solve the problem of a fisher that can't get home

c) reset ships to a different position (beaming). this could solve the fisher getting stuck/not getting home issue

For now, fisher ships will not be included in the ship map to avoid the problems in the current code.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1023)
##

**Comment by AndyMender** [comment]
Possibly related to? https://github.com/unknown-horizons/unknown-horizons/issues/967
