### ISSUE TITLE
unable to set most resource quantities for trade routes

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1095]
It is currently not possible to create a trade route where you load N tons of a resource where N is not a multiple of 3. That isn't a problem for large quantities but it isn't as good when you want to carry a very small amount at a time.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1095)
##

**Comment by AndyMender** [comment]
Indeed, the slider doesn't allow resource amount changes smaller than +/- 3 in the traderoute menu. I will have a look at the underlying code to see why this is the case. @LinuxDonald should the traderoute menu sliders be replaced with up/down arrows or is adjusting the slider increment to +/- 1 sufficient?

**Comment by LinuxDonald** [comment]
Slider is better? Faster?

**Comment by AndyMender** [comment]
A slider is potentially faster, but harder to get a specific value with. I also noticed that the slider does not consider the max amount of player resources, suggesting quite ridiculous values as the maximum amount to load. This of course would require extra logic checks and apart from looking strange is not game-breaking.

**Comment by LinuxDonald** [comment]
Than make it that it works good and is easy for gamer.

**Comment by AndyMender** [comment]
As Xiong mentioned quite some time ago, the sliders are a much broader issue and concern also the warehouse and transactions with the free trader. That's a game enhancement that I believe should be discussed with other developers and resolved in a separate ticket. 

The case of the traderoute menu is clearly a bug, which I tried to "fix". I'll try to make sure the fix is not game-breaking before committing.

**Comment by jmdejong** [comment]
I could fix this by limiting the slider scale to something around 40 or 50.
The problem would be that the player can not trade more than that in a single slot.
Also, it will be hard to get the mouse on the correct pixel, but it is possible
