### ISSUE TITLE
Ships change orientation for no reason

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1182]
Ships sometimes change orientation for no particular reason. This seems to happen more often when a frame takes longer than usual to calculate.
See the attached video for an example of this behaviour.

**Attachment**: [ship_orientation.avi](http://up.unknown-horizons.org/f/?id=209&n=ship_orientation.avi)
##

**Comment by AndyMender** [comment]
@ChrisOelmueller, is this still an issue? I haven't noticed any ships "jiving" on the water's surface.
