### ISSUE TITLE
Inaccurate minimap view position indicator

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1284]
The minimap position indicator shows that one should barely see any of the blue settlement while one can see quite a lot. Part of the red settlement should also be outside the view although it isn't.

![lgztf](https://cloud.githubusercontent.com/assets/50333/19888177/500b98d8-a02d-11e6-84b4-dc87046c6f33.jpg)

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1284)
##

**Comment by LinuxDonald** [comment]
Maybe the minimap should rotated as the map it self?

**Comment by LinuxDonald** [comment]
@jmdejong no man power. You can work on it if you like :-)
