### ISSUE TITLE
Automatically restart the game when needed

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1327]
Some display settings changes require restarting the game. It would be better if the game did that on its own.
A further improvement would be a post-change prompt asking whether to keep the settings (revert if crashed or not confirmed in N seconds).

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/1327)

**Comment by jorgesumle** [comment]
Solved #2434
