### ISSUE TITLE
Scrolling doesn't stop when moving cursor out of the game window

### ISSUE THREAD

**Issue by unknown-horizons** [unknown-horizons/unknown-horizons#1413]
This issue was reported by **AyCe**

When you move the mouse to the left/top/right and then quickly on a UI panel, the scrolling continues (annoying when building)

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1413)
##

**Comment by jmdejong** [comment]
fixed in #2818
