### ISSUE TITLE
Fields for farm (Tier 4)

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#1448]
Please create new tickets for the fields you want to work on and link them here.

* [x] vineyard (grapes)
* [x] cocoa field (cocoa beans) #2336
* [x] alvearies (honeycombs) #1450

More information:  http://wiki.unknown-horizons.org/w/User:Eoc/DD/BL#Resource_cultivation_.2F_Agriculture

**Comment by janexx** [comment]
close this issue?

**Comment by LinuxDonald** [comment]
Yeah let's close it. Thx for your work :-)
