### ISSUE TITLE
Tooltips in resource bar displayed twice occasionally

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#1451]
Usually happens when you start hovering from the bottom area and slowly move up.

**Attachment**: [buggy-resbar-tooltips-1.png](http://up.unknown-horizons.org/f/?id=244&n=buggy-resbar-tooltips-1.png)
**Attachment**: [buggy-resbar-tooltips-2.png](http://up.unknown-horizons.org/f/?id=245&n=buggy-resbar-tooltips-2.png)
**Attachment**: [buggy-resbar-tooltips-3.png](http://up.unknown-horizons.org/f/?id=247&n=buggy-resbar-tooltips-3.png)
##

**Comment by AndyMender** [comment]
Issue in question resolved here: https://github.com/unknown-horizons/unknown-horizons/pull/2241. Tooltips not disappearing or being spawned multiple times is a common problem of some GUI widgets, but needs to be addressed on a per-widget basis (for instance, by reducing widget complexity). See https://github.com/unknown-horizons/unknown-horizons/issues/2648 for reference.
