### ISSUE TITLE
Create variations of inhabitants housings

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#1468]
As usual, there can (and should) be more than one kind of inhabitants housing graphics.

* Half-timbered house (Tier III): #633
* Wooden house (Tier II)

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/1468)

**Comment by janexx** [comment]
Tier II (Pioneers) has already 3 different residential houses. So I would add only 2 additional houses for Tier II. And maybe I could improve the stone houses of Tier IV (citizens) a bit...

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/1835fb3cf9c13c9f4ca33e16afed77fb89b13c28

**Comment by LinuxDonald** [comment]
@janexx could you maybe make the https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gfx/buildings/citizens/residential/as_stonehouse0 house a liitle bit nicer? And one more tier 3 building and this ticket is done.

**Comment by janexx** [comment]
yep :)

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/bed228cb7d1a4af0492e2561e852b96e382665ad

Last building is done @janexx thx :) Good Work :+1:
