### ISSUE TITLE
Jumping collectors

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1701]
The attached video shows some (but not all) collectors jumping a tile at a time instead of walking normally.

It is not known how to get this behaviour. Reloading the game fixes it.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1701)
**Attachment**: [jumping.avi](http://up.unknown-horizons.org/f/?id=312&n=jumping.avi)
##

**Comment by AndyMender** [comment]
@ChrisOelmueller, it seems the .avi video is no longer available. Still, could this issue be related to this one? https://github.com/unknown-horizons/unknown-horizons/issues/2642

**Comment by AndyMender** [comment]
I'm closing this one as upon thorough investigation the collectors seem to behave normally and move without jumping tiles.
