### ISSUE TITLE
Don't hide the cursor

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#1765]
It is not user friendly to hide the cursor unless the user should really be expecting it. That is definitely not the case on loading screens such as those in UH.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/1765)

**Comment by squiddy** [comment]
On archlinux, the cursor is hidden on loading screens. When I move it outside the window it is visible.

Do we consider that a bug? Is there a problem on windows where the cursor is hidden even outside the window? @LinuxDonald perhaps you can clear things up a bit here

**Comment by LinuxDonald** [comment]
I dont use. UH on Windows. Maybe the cursor should be visable in window mode on loding screen. But on fullscreen this should now be needed. An this have only i think low priority.

**Comment by squiddy** [comment]
Since we do not have other reports of this causing issues, we might as well close it?
