### ISSUE TITLE
Create building graphics: Tier 3, animated spice field

### ISSUE THREAD

**Issue by DanielStephens** [unknown-horizons/unknown-horizons#1788]
A field of our farm which is used to grow spices. These would be prepared in the farm (not visible to players) and refined by the blender to be used on foods for inhabitants.

Planned size for the spice field is 3x3 tiles which equals a rendered size of 192x192 px. Similar sized fields are e.g.:
* [Tobbaco field](https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gfx/buildings/settlers/agricultural/as_tobaccofield0/idle_full/135/0.png)
* [Herbary](https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gfx/buildings/settlers/agricultural/as_herbary0/idle_full/135/004.png)

Inspiration for different growth stages (4 to 5 stages, starting at no plants, ending with ready-to-be-harvested):

* Chili plant examples: [this](http://www.cookooboxchillies.com/chillis/chili-chilli-24-lrg.jpg) and [this](http://i479.photobucket.com/albums/rr153/duckboy1973/The%20Upton%20Cheyney%20Chilli%20Company%20Web%20Site%20Gallery/DSC00093.jpg)
* Pepper corn plant examples: [this](http://3.bp.blogspot.com/_JZlh88EMaiw/SliM_Mh4PgI/AAAAAAAADzw/iqT1ayEhzuo/s400/pepper+plants.JPG), [this](http://www.spices.res.in/package/pepper/pepper.jpg) and [this](http://www.catscanman.net/uploads/Images/Yercaud%20images/Yercaud%20house8.jpg)
* Coriander examples: [this](http://www.extension.iastate.edu/newsrel/reiman/cilantro.jpg), [this](http://1.bp.blogspot.com/_6KRo-dmHHWA/TCIDJ2n9vRI/AAAAAAAAASU/5u-XRgoZ_Uw/s1600/cilantro.jpg) and [this](http://thymeforfood.files.wordpress.com/2008/06/cut-coriander-plant-2.jpg)
* Basil: [this](http://www.anordinaryworld.com/uploaded_images/basil-740086.jpg), [this](http://farm3.static.flickr.com/2481/3681654250_a2a538917a.jpg)
* Mint: [this](http://www.chm.bris.ac.uk/motm/menthol/mintplant.gif), [this](http://sanbenitowellness.com/shop/wp-content/uploads/marketimages/mint-plant1.jpg)
* Rosemary: [this](http://www.veggiegardeningtips.com/wp-content/uploads/2007/07/rosemary-herb.jpg), [this](http://www.flowerworksuk.com/florist/images/1105-1.jpg)
* Chives: [this](http://www.onlyfoods.net/wp-content/uploads/2011/12/Chives-Photos.jpg), [this](http://www.fruechteadam.com/img/Schnittlauch.jpg)
* Cinnamon plant: [this](http://gardeninginthelines.files.wordpress.com/2012/04/osmundacinnamomea_mg_1_lg.jpg)
* Ginger root: [this](http://webecoist.momtastic.com/wp-content/uploads/2009/07/turmeric-root-galangal-and-ginger-root.jpg) the actual root is underground but looks like [this](http://thezedgirl.files.wordpress.com/2009/09/ginger-root.jpg)

If you are running short on ideas of what to put in the field check out [this list of spices and herbs](http://en.wikipedia.org/wiki/List_of_culinary_herbs_and_spices)

You can choose some of the above images and assemble a field where different kinds of plants are grown together. They can have different height, color and density. Please make sure that the animationmeans that something happens to the plants in every frame (grow or bloom), and try to make things grow quickly to start with to avoid having a large area of brown field for long periods of time.

The state idle represents the fact that no growth happens (e.g. because of infertile ground) which is the first growth animation and idle_full is the last growth animation which waits for harvest. Usually those are blatantly copied, so you needn't worry about creating more action sets than work.

**Comment by janexx** [comment]
added a buildmenu icon with commit 7263189b6b82445aa1376244da1322e93b29ec14

**Comment by janexx** [comment]
When I am right, there is still the resources icon missing. I made one: http://up.unknown-horizons.org/f/?id=696&n=recource.png
Are you happy with that? If so, then which dummy icon will be replaced? 046.png in /home/wally/unknown-horizons/content/gui/icons/resources/32/ ?

**Comment by stubb** [comment]
@janexx Just checked the buildmenu, its there for both buidlmenu styles.
![Image of spicefield buildmenu entry](http://up.unknown-horizons.org/f/?a=v&id=700&n=2015-01-21.19-38-41.603720.png)

**Comment by stubb** [comment]
Since everything if working as expected, we can close this issue.

**Comment by janexx** [comment]
I finally added the condiments icon in color and grayscale with commit b6b7d8d3ec3a909b7bd9bc4f21e4bc6acaf712bb
Now its all finished. Close this issue?

**Comment by stubb** [comment]
Yep, this issue is fixed! Thanks a lot. Only one task left before finishing all buildings for Tier 3 ;-)
