### ISSUE TITLE
Add more Gameplay Tips

### ISSUE THREAD

**Issue by hoffi** [unknown-horizons/unknown-horizons#1821]
Actually we only have 9 Gameplay tips, which is not very much. 
We should add much more helpful gameplay tips. 

The tips are stored here: [/horizons/gui/quotes.py#L49](https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/gui/quotes.py#L49)

**Comment by xseanl** [comment]
Would like to do this ticket.
Since 2012 the file mentionned above  "/horizons/gui/quotes.py#L49" seems to be gone. 
Gameplay tips are found in /unknown-horizons/horizons/gui/modules/loadingscreen.py now.

**Comment by LinuxDonald** [comment]
Okay than do it :-)
