### ISSUE TITLE
Small production overview tab does not use small images, makes bad use of spacing

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#1901]
Not urgent:
After merging `centered_production_lines` the farm overview will look like a regular production overview.
That's not supposed to happen, check current master for how the smaller production overview looks.

Pastry shop overview is easier to test than the farm by the way since you do not need to build fields for the former.
##

**Comment by squiddy** [comment]
Screenshot of the wheel issue

![](http://i.imgur.com/NwvoZS2.jpg)

Apart from the wheel not beeing centered, what else is this issue about? @ChrisOelmueller can you say more? You mentioned something about it beeing unusable about 4 years ago. :)

**Comment by LinuxDonald** [comment]
I think only the wheel issue is here. Because stubb already added an scrollbar here.
