### ISSUE TITLE
Multiple minor multiplayer menu issues

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#1975]
- [x] the password textfield is invisible
- [x] the ready button shouldn't be named ready if your player state is already "ready"
- [ ] the autoscroll feature within the chat scrollbox only scrolls down to the next to last message, it doesnt show the last message
- [x] add an extra start button for the game host

**Comment by squiddy** [comment]
The extra button is tracked in #1406 already, will have a look at the chat issue.
