### ISSUE TITLE
Warehouse (Pioneers)

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2022]

**Comment by janexx** [comment]
There are already graphics for a storage hut. But its not in game. Is this already the warehouse?
Or what is the difference from a storage hut to a warehouse? Are there really new graphics needed?

**Comment by stubb** [comment]
@janexx The warehouse is the main building of the settlement. Its a warehouse accessibly by ships. The storage huts main task is extending the settlements resource capacity and providing places where the settlers can get resources.

**Comment by janexx** [comment]
... is finished with commit a5b261550a3cacc0663496c226c7c3bb6c77a39c
