### ISSUE TITLE
Windows installer: installation unsuccessful but no error

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2075]
If you run the installer as a user who hasn't the rights to write to the installation target folder, there is only a message displayed that the file wasn't copied to the target location, but the installer runs further.
In my opinion the  installer should stop if one file wasn't copied correctly and trash all files that are copied already. Also a notification to the user that something went wrong would be helpful.
![Installer screenshot](http://up.unknown-horizons.org/f/?a=v&id=441&n=win_skip.png)
##

**Comment by LinuxDonald** [comment]
Where is the installer source for windows?

**Comment by stubb** [comment]
Every necessary information are collected here https://github.com/unknown-horizons/unknown-horizons/wiki/Windows-installer

**Comment by LinuxDonald** [comment]
Closed because creating new installer.
