### ISSUE TITLE
Overlay renders of brickyard production

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2131]
The central area in `work` animation and up to `idle_full` gets gradually filled with bricks.
With inventory overlays, It would make sense to have that as storage indicator instead with the current five steps plus a new, to-be-done completely empty center (there's a few bricks in `idle` that I'd like to see go).

We'd also need some new way of indicating that a production is currently active, which may or may not involve the oven for instance. It should be made in a way that allows the same inventory overlays to display, to avoid having to render lots of slightly different overlay images.

Note that we currently have not archived a model of the brickyard, so this ticket is kind of blocked.
**edit:** We now have, thanks to terwarf :)

**Comment by janexx** [comment]
eh whats here still to do? Or can this be closed?

**Comment by ChrisOelmueller** [comment]
@janexx 

Does the brickyard support animated production/inventory overlays now?

I seem to remember testing this code with lumberjacks exclusively, so the ticket was about also using the same feature for brickyards (by only showing certain amount of "finished" bricks in its yard) I believe.

**Comment by janexx** [comment]
Finished with commit 33377593ed512b6d65431ac9e972cafe3d9e1f3c
I've tested it already. Thanks @ChrisOelmueller for helpful informations! :)
