### ISSUE TITLE
Inconsistencies between build menu types

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2176]
As seen in e.g. f743e07 the (currently two) different build menu definitions go out of sync rather quickly.
There's no test to check that all available buildings are enabled for each type (either in-code or as actual test in our test suite).

Note that "available building" currently defines as "is active in the per_tier buildmenu".
##

**Comment by squiddy** [comment]
Should be easy enough to write an actual test that checks whether the set of buildings in each menu type is identical. If that surfaces inconsistencies, we can fix them.

**Comment by squiddy** [comment]
Added test in 2a660ced55413224ac0b44521bc85d314c45aad7. No inconsistencies at this time.
