### ISSUE TITLE
Autosave intervall doesn't work correctly

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2180]
Set autosave intervall to 1 minute and wait around ~ 3minutes till automatic saving happens.
##

**Comment by squiddy** [comment]
Definitly related to #1957. If you move the slider until it almost switches its value to 2, internally it's about 1.89.

Which means one would expect the game to be saved every 1 * 60seconds, but it's actually 1.89 * 60 = 113seconds.

**Comment by squiddy** [comment]
Using our `StepSlider` widget (https://github.com/unknown-horizons/unknown-horizons/blob/f24e1ddece01f8ef3cec04e0e3ad7c7f25e1070a/horizons/gui/widgets/stepslider.py) should help here.

**Comment by jmdejong** [comment]
I just tested this and the interval seemed pretty accurate.
It does show decimal numbers now, so when it's almost 2 minutes it shows in the slider as 1.9

Is this still an issue or has it been fixed by now?
