### ISSUE TITLE
Trade Tutorial Confusing

### ISSUE THREAD

**Issue by Rybadour** [unknown-horizons/unknown-horizons#2242]
This was my first time trying out the game and most of the tutorial was pretty straight forward except for the trading. The text starts off with "After selecting a particular type of good," but it didn't really explain where you're supposed to see this.

At this point in the tutorial I didn't get that you had to select the warehouse to see trade information. Similarly, it took me more time to realize you have to select the main square to see tax information.

I'd recommend adding a line at the start of the trade tutorial like "First, select your warehouse.". 

Also, wasn't quite clear how the GUI works to setup a trade. Maybe something like this can help explain it: "Click the one of the open spots in the trade menu to choose a good to buy or sell"

**Comment by LinuxDonald** [comment]
Started to work on this: https://github.com/unknown-horizons/unknown-horizons/commit/d5c060ff3f0bd75c2193dbbf3a84cb4d47b0d8a2

@Rybadour maybe you have some feedback?

**Comment by Rybadour** [comment]
Much better. Although there are some typos:

> Than click on one of the 3 solts than you can select an good that you want to buy or sell.

Then click on one of the 3 slots, then select a good you want to buy or sell.

**Comment by LinuxDonald** [comment]
Thx :-) have you some more ideas or is it okay now?

**Comment by Rybadour** [comment]
Sorry it's been a long time since I tried the game out. This was the only thing I felt a need to complain about :)
