### ISSUE TITLE
Implement sound for cancel action in the menus

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2250]
Right now there is only one sound used for all GUI interactions (the click.wav from #1529).

The task is to implement a different sound for the cancel actions. You could use the click2.wav from the ticket mentioned above or use another one, but keep the legal issues in mind.

**Comment by Gladius1** [comment]
Hello, I implemented the cancel Button sound. But I don't know how to upload the changes...

**Comment by stubb** [comment]
hi Gladius1,

you have to create a git commit in your fork and make  pull request. https://help.github.com/articles/using-pull-requests/ Should help you to understand whats necessary to create the pull request. If not feel free to ask again.

**Comment by Gladius1** [comment]
Ok, I made a pull request. But it turned out to be messy. I hope it is usable as it is.
