### ISSUE TITLE
Gnome3-Issues

### ISSUE THREAD

**Issue by M3tal-Warrior** [unknown-horizons/unknown-horizons#2276]
OS: Debian Wheezy, DE: Gnome3, fglrx-driver (non-free)
Version: Debian Wheezy repository of May 2nd 2014 (2012.1+dfsg1-1)
Graphical settings: 1366x768, 32bit, tested with OpenGL and OpenGLe

Alt + Tab not working, neither do CTRL + ALT + Arrows (for switching desktops), only CTRL + ALT + F1/2/3... works (for leaving X11, but F7 always returns to the game, so the desktops are effectively blocked by the game). 
Gnome3-messages (for mail etc.) let the screen flicker now and then, as do skype messages.

**Comment by LinuxDonald** [comment]
@M3tal-Warrior can you please test it with lastest fife-git/fifechan-git and uh-git version? fife uses now sdl2.

**Comment by LinuxDonald** [comment]
@M3tal-Warrior any feedback?

**Comment by LinuxDonald** [comment]
Moved to next milestone because of lack of feedback.
