### ISSUE TITLE
Text input cursor image not reset on widget exit while hovering input field, button

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2294]
* Load a game
* Press Esc, select Save
* Hover over "name" field, cursor should change now
* Press Esc

Expected: Widget closes, cursor resets to normal
Actual result: Widget closes, cursor does not reset

![](http://up.unknown-horizons.org/f/?a=v&id=662&n=2014-08-27.17-32-08.506997.png)

**Comment by squiddy** [comment]
Closing in favor of #2416
