### ISSUE TITLE
Window icon not shown with awesome wm

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2302]
Using the awesome Window Manager on a Linux distro the window icon isn't shown.

**Comment by stubb** [comment]
To gather some data: awesome wm with UH master HEAD + fife 0.3.5 shows the window icon, but not for the atlas creation window.

**Comment by squiddy** [comment]
Using awesome wm too and it shows up here as well.

Closing this, since implementing the icon for the atlas window isn't really beneficial overall, see https://github.com/unknown-horizons/unknown-horizons/pull/2509#issuecomment-253038095.
