### ISSUE TITLE
One point of memory leak with multi-selection of same object

### ISSUE THREAD

**Issue by pinkfloyda** [unknown-horizons/unknown-horizons#2308]
Below is a simple repro steps to demonstrate such mem leak:

Create a single user game, select the ship multiple times (wether using mouse click or hotkey select), observe that the memory usage is increasing with the times of selection (each selection consumes 3 MB or so). The same applies to selections of any buildings as well! And I suspect this is one of the reasons why the game becomes laggy and consumes huge memory over time.

It seems like each selection load something (xml file or image resource) into memory but never released.

**Comment by helios2000** [comment]
Yea I noticed that also a wile back. A part of that problem was Pychan. I fixed the circular references here https://github.com/fifengine/fifengine/commit/3607a657713836e84b5fb6af154b688483fc25bc
But the problem in UH remains. Make sure that you use fife master if you want to track down the problem.
I think that pinkfloyda is right, somehow all the gui stuff is created again and again. It's no problem to have thousands of widgets after a few minutes of gameplay.

**Comment by pinkfloyda** [comment]
After instrument using objgraph, I found out the below result (after running gc.collect()):

===============================================
(Pdb) objgraph.show_growth(50)
dict                                 493500   +422201
cell                                 297971   +283010
list                                  310898   +252431
tuple                               205077   +183697
instancemethod              115699    +98363
function                          111667    +94859
weakref                          61436    +51665
Callback                         29417    +26348
_MouseEventListener          26659    +25427
EventMapper                  26659    +25427
_ActionEventListener         26659    +25427
_KeyEventListener            26659    +25427
_WidgetEventListener         26659    +25427
Icon                         24548    +23869
GuiImage                     17889    +17317
Container                     9367     +9048
Label                         7613     +7020
TwoButton                     2592     +2495
ImageButton                   2403     +2339
HBox                          1657     +1560
Spacer                         966      +936
VBox                           861      +780
hr                             814      +780
CheckBox                       678      +624
ImageFillStatusButton          632      +624
Inventory                      474      +468
WeakMethod                    7512      +414
PychanChildFinder              318      +312
ScrollArea                     346      +312
Point                         2119      +312
BuySellInventory               316      +312
TabBG                          316      +312
Minimap                        160      +156
_MinimapImage                  160      +156
TradeTab                       158      +156
Rect                           164      +156
SharedImagePointer             195      +156
OkButton                       169      +156
SharedRenderTargetPointer      160      +156
RenameLabel                    159      +156
ShipOverviewTab                158      +156
RouteConfig                    158      +156
type                          1583      +124
SelectionTool                  125      +124
ExactModelCoordinate           339      +124
CmdListener                    125      +124
Timer                           46       +10
MouseEvent                      40        +9
set                          25872        +1
_ExtCallbackObject               7        +1
=======================================================

It looks like lots of named objects, such as _MouseEventListener, _ActionEventListener, _KeyEventListener, _WidgetEventListener, GuiImage, etc. are not GCed. 

May look deep why

**Comment by pinkfloyda** [comment]
Looks there is a long chain of circular reference, which leads to a batch of objects not released

**Comment by pinkfloyda** [comment]
Find one place can leak such memory: if there are multiple tabs in TabWidget, the non-current tab instance is created, which is added into widget_set of fife.pychan.internal.Manager, but this tab is not current active so it is not added as one of TabWidget's children, so this tab cannot be hidden when TabWidget is hidden. In this way, each time TabWidget opens up and closes, there are some non-current tab instance created in memory and not freed.

**Comment by stubb** [comment]
@pinkfloyda thanks for your investigation, iam excited to see your PR!

**Comment by pinkfloyda** [comment]
After investigating the code for a while, I find some common cases for mem leaks.

Actually, creating a pychan widget (whether directly or through subclass init) will add it into pychan.internals.manager.allwidgets. Currently, the most common way to get widget removed is through widget.hide(), mostly called by its parent in its view hierarchy.

But somewhere in-code, such widgets are created, even though they are invisible, without hidden, they cannot be removed from pychan.internals.manager.allwidgets.

I hope others can take this as a reference to help get rid of other places or mem leaks.

**Comment by stubb** [comment]
Seems like these changes introduced  #2315

**Comment by LinuxDonald** [comment]
Can that bug closed?

**Comment by pinkfloyda** [comment]
@LinuxDonald Yes, I think so.
