### ISSUE TITLE
Create a pasture will cause memory increase by 1-2 MB/second

### ISSUE THREAD

**Issue by pinkfloyda** [unknown-horizons/unknown-horizons#2311]
Potatofields and sugarfields can increase memory as well, but 0.x MB/second.

**Comment by stubb** [comment]
The correct terms are pasture, potatofield and sugarfield. I will edit your post, so it can be find easier.

**Comment by stubb** [comment]
We have to check out much it increases the memory use and if this value could be valid.

**Comment by LinuxDonald** [comment]
i will check this in the next days.

**Comment by LinuxDonald** [comment]
Should be fixed in 2017.2
