### ISSUE TITLE
Cattle run

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2312]
Can be simliar to the sheep pasture.

**Comment by janexx** [comment]
For what purpose should the cattle be? To produce milk or meat or both? I dont know if I should make male or female cattle or both.

**Comment by LinuxDonald** [comment]
For now I think only for meat

**Comment by stubb** [comment]
As @LinuxDonald  said its intended use is the production of meat. Feel free to create female and male gfx.

**Comment by janexx** [comment]
Here is a preview. I am still working on the animation.
![preview2](https://cloud.githubusercontent.com/assets/6216898/11770679/f5240df0-a204-11e5-93f4-ac41f50a8354.png)

**Comment by LinuxDonald** [comment]
looks very nice :)

**Comment by janexx** [comment]
finished with commits 468812ceed066f19d16e0c137fce8fe94302fcd1 and 60e6e6a8061828489f87cc2c6c742db3d0f63700
