### ISSUE TITLE
Button/Icon to represent discarding all resources currently loaded

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2313]
The trade ship overview tab has now a button to discard all resources currently being in the inventory. There is a placeholder used which should be replaced. For more details please read #986.

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/de11d05135c5e3a7c6b07cf16830b75ced2ca08b https://github.com/unknown-horizons/unknown-horizons/commit/fd70beed8e3cc3d0ccaddbc782d27e79d90766d1 https://github.com/unknown-horizons/unknown-horizons/commit/59a86137810cf7f3d182f41c95c5b72abfb301ea https://github.com/unknown-horizons/unknown-horizons/commit/5a572cd57dcde54851b8ca37c9cddefb8fb1156f https://github.com/unknown-horizons/unknown-horizons/commit/470866a523dc29f6f5665c7e2a03f1ac5310928a
fixed
