### ISSUE TITLE
Ubuntu packaging is out of date

### ISSUE THREAD

**Issue by vgezer** [unknown-horizons/unknown-horizons#2317]
The latest version on Ubuntu repositories is 2013.3 which is old. It will be very nice if you could provide repo for utopic and vivid versions of Ubuntu.

And also 2014.1

Thanks

**Comment by stubb** [comment]
Mostly fixed. There aren't any packages for Vivied yet.

**Comment by siccegge** [comment]
unknown-horizons 2014.1+ds1-2~ubuntu15.04.1 (Accepted)

Should be there in a minute
