### ISSUE TITLE
game crashes when you ally with one of the AIs

### ISSUE THREAD

**Issue by Huaraz2** [unknown-horizons/unknown-horizons#2321]
Here is a screenshot of my terminal when the game crashed

![screenshot from 2015-03-23 21 27 44](https://cloud.githubusercontent.com/assets/8998661/6866361/4a352338-d46f-11e4-9557-7027c06abfd2.png)

Any help on how to fix this would be greatly appeciated

**Comment by stubb** [comment]
Should be fixed now.
