### ISSUE TITLE
Archlinux AUR package broken

### ISSUE THREAD

**Issue by Sorunome** [unknown-horizons/unknown-horizons#2328]
The Archlinux AUR package is broken, it requires the dependency fife-git which requires fifechan-git which doesn't exist anymore, the non-git versions all exist, though, but they don't satisfy the PKGBUILD.

The same issue exists with the git version

**Comment by stubb** [comment]
Thanks for notifying us!
Have fun https://aur.archlinux.org/packages/fifechan-git/

**Comment by Sorunome** [comment]
Ok, now the new fifechan-git fails to build because allegro4 is missing, which is in the official repos, so a simple fix. But somehow when doing makepkg -is it failes to install that dependency from the official repos, not a crucial thing, though.
