### ISSUE TITLE
cocoa field (cocoa beans)

### ISSUE THREAD

**Issue by janexx** [unknown-horizons/unknown-horizons#2336]

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/d21c14f41a719d363dd229393bf31ed13841836e

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/60ecba5a4a6b05e5605db9d74d08ba53096fac25

**Comment by LinuxDonald** [comment]
Fixed wonderful work :-)

**Comment by janexx** [comment]
maybe I should made the gui-icon for the build menu? and propably there is also the resource icon left?

**Comment by LinuxDonald** [comment]
Okay do it please

**Comment by janexx** [comment]
Doen with commits: 9dec8df8555d5ee3b0a33c88784202dc9a30c722 , 31cc8ce006874e59ab207357264a67fd0228bcf7 and e55d16aff2de9f139d2d1ea9bc8da4933f54ec12 
Is something missing?

**Comment by LinuxDonald** [comment]
I will check this later. After come back from work. Thx for your work :-)

**Comment by LinuxDonald** [comment]
Some bugs with the field but that i can fix. It have nothing todo with you grafics :)

**Comment by LinuxDonald** [comment]
Fixed
