### ISSUE TITLE
Add grafics for cannon foundry

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2339]
Grafic paths can be found here:

https://github.com/unknown-horizons/unknown-horizons/commit/0a4c640d082137acb3b3050a1953979d6ce3b661

**Comment by janexx** [comment]
Should the cannon foundry have a size of 2x2 or 3x3? I have tested both options:
**Cannonfoundry 3x3:**
![cannonfoundry_3x3](https://cloud.githubusercontent.com/assets/6216898/13330870/292e71a0-dbfb-11e5-91c0-fd3dcaf9dd25.png)
**Cannonfoundry 2x2:**
![2x2](https://cloud.githubusercontent.com/assets/6216898/13330879/31a79d0c-dbfb-11e5-81c7-483b2caee52c.png)

**Comment by stubb** [comment]
In my opinion the 3x3 looks better and fits better into the size relations at all. You have done great work again!

**Comment by LinuxDonald** [comment]
Janexx: I and stubb have talked about on irc. And have decided that I should be 3x3 :-)

**Comment by janexx** [comment]
Ok fine, I will update it later :)

**Comment by janexx** [comment]
I updated the cannon foundry: 4e1e7f3ce8d34fcedc626bea73d370fd5897a84f
Maybe it can improved a bit (move the mold with the help of the cable pull) later. For now I close this issue.
