### ISSUE TITLE
Random lagspikes while playing

### ISSUE THREAD

**Issue by kozross** [unknown-horizons/unknown-horizons#2342]
Every couple of minutes of playing the game (particularly when selecting buildings), I get lagspikes lasting a fairly considerable time (several seconds, up to five seconds sometimes). During these, I can't move the mouse or do much of anything. Don't know if this is a bug or not, but I figured I'd report it.
##

**Comment by LinuxDonald** [comment]
Yeah that is an known bug. We hope that that bug get fixed next year.

**Comment by pinkfloyda** [comment]
@LinuxDonald Hi, do you know what is the previously known bug? Is there a link to that? I remembered previously (long time ago), I encountered this issue and I submit a fix already. The slowdown is due to the menu, there are so many menu items get loaded each time.

**Comment by LinuxDonald** [comment]
@pinkfloyda was that report here on git page or on the old trac bugtracker? Maybe you can find the old one. Where the patch is?

**Comment by pinkfloyda** [comment]
@LinuxDonald check this one "Tab shown delayed in selecting #2235"

**Comment by pinkfloyda** [comment]
@LinuxDonald I remembered, it is slowdown because of my memory leak, maybe this one is different to that one.

**Comment by LinuxDonald** [comment]
question is how to fix the problem.

**Comment by LinuxDonald** [comment]
This bug is fixed with UH 2017.2
