### ISSUE TITLE
Units are sometimes hidden from buildings

### ISSUE THREAD

**Issue by janexx** [unknown-horizons/unknown-horizons#2347]
Sometimes units are hidden behind graphics of buildings like the woman with the marketplace in this picture:

![women_behind_marketplace](https://cloud.githubusercontent.com/assets/6216898/12080885/ce7ff374-b269-11e5-9ed3-7d1868f68101.png)

The hiding happens randomly. Sometimes its all right and sometimes not.... very strange.

I use Arch Linux and nouveau as graphic driver (free driver for Nvidia graphic cards).
It seems that this behavior affects only me. Could be a driver problem.

**Comment by LinuxDonald** [comment]
![2016-01-16 00-57-36 618265](https://cloud.githubusercontent.com/assets/1757651/12368520/60e6f68c-bbec-11e5-8973-c89fb701a236.png)
Maybe the same problem?

**Comment by AndyMender** [comment]
In the case of the main square it might be related to https://github.com/unknown-horizons/unknown-horizons/issues/661.

**Comment by jmdejong** [comment]
@LinuxDonald I think the problem in your screenshot is different: fields are in another layer, and therefore always drawn behind other objects. You can see the difference that fields are consistenly behind other stuff, whereas the people are sometimes in front, and sometimes behind the main market.

**Comment by jmdejong** [comment]
I think the original problem is fixed with PR #2804.
@LinuxDonald the problem you mentioned can be fixed by putting fields in the OBJECTS layer instead of the FIELDS layer. The downside would be that #2814 would then also apply to fields.
https://github.com/unknown-horizons/unknown-horizons/blob/ab7c542814c5f682485ac2b901a05a8a814f7d34/horizons/world/building/nature.py#L43
Should I change it?

**Comment by LinuxDonald** [comment]
@AndyMender what do you thing about the layer change?

**Comment by AndyMender** [comment]
I think it's alright. Fields shouldn't be treated differently anyway.

**Comment by LinuxDonald** [comment]
@jmdejong do it you have the okay :)

**Comment by jmdejong** [comment]
fixed in #2804 and #2815
