### ISSUE TITLE
Stone deposit not works

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2357]
Stone deposit can´t be build. I think it must be implemented.

**Comment by LinuxDonald** [comment]
Maybe an workaround would be that mine produces not only one resource. With every tier the mine could be produce one more resource?

**Comment by stubb** [comment]
Like the clay pit, the stone pit is an own resource. The resources produced by the mine are independent from the pits at all. Worth to take a look at this page http://wiki.unknown-horizons.org/w/User:Eoc/DD/BL

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/pull/2359
