### ISSUE TITLE
Grafic for pastryshop

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2368]
Need grafic for pastryshop

**Comment by LinuxDonald** [comment]
@janexx we need some more pastryshop icons please see:

That is correct: unknown-horizons/content/gui/icons/buildmenu/063.png
Need update: unknown-horizons/content/gui/icons/buildmenu/063_h.png
and: unknown-horizons/content/gui/icons/buildmenu/greyscale/063.png

**Comment by janexx** [comment]
Ok. Or maybe make  complete new one?

**Comment by LinuxDonald** [comment]
Yeah one of Janexx style made one :-)

**Comment by janexx** [comment]
I added the pastry shop graphics: dfd5b3aee9071788732146cac187175aea6c71b8
![063](https://cloud.githubusercontent.com/assets/6216898/13826754/635f4dd6-ebb9-11e5-9a98-8bc27462db39.png)
