### ISSUE TITLE
Production Overview is broken

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2369]
![2016-03-11 18-59-56 415537](https://cloud.githubusercontent.com/assets/1757651/13710793/860122f8-e7bb-11e5-858e-017d80b284ba.png)

There is nothing showed...

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/pull/2372

**Comment by Jeeppler** [comment]
Is this fixed or open?

**Comment by LinuxDonald** [comment]
It's open. I only closed the pull request because that don't become finished.
