### ISSUE TITLE
Pastryshop not all proc lines are visible.

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2371]
The Pastryshop gui dont show alle proc line of it.

@stubb can you please take an look on it?

**Comment by LinuxDonald** [comment]
![2016-03-15 20-07-34 059199](https://cloud.githubusercontent.com/assets/1757651/13790638/be6331a0-eae9-11e5-8f93-744c545718ab.png)

**Comment by stubb** [comment]
Wee need to introduce a scrollbar here. For smaller screen sizes the widget will become too big
![2016-03-15 20-33-46 740645](https://cloud.githubusercontent.com/assets/373318/13791427/6100070a-eaed-11e5-8e7e-fcf832b82be3.png)
