### ISSUE TITLE
Homepage: please add very short instructions how to grab the source and compile it at http://www.unknown-horizons.org/download/linux/

### ISSUE THREAD

**Issue by shevegen** [unknown-horizons/unknown-horizons#2376]
Homepage: please add very short instructions how to grab the source and compile it at http://www.unknown-horizons.org/download/linux/

I always try to compile from source first.

I am sure I will find out somehow anyway but right now I am wondering how to obtain the source (ok, I can probably download the zip from github here, but still I think a sentence should mention that on the download link).

Thanks.

**Comment by stubb** [comment]
Within the left sidebar are links to the instructions.

**Comment by stubb** [comment]
Please reopen if anything is unclear about the instructions
