### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by zapashcanon** [unknown-horizons/unknown-horizons#2381]
Hi,

A friend of mine installed the game, using:

`apt-get install unknown-horizons`

She's running Debian Testing (amd64), I asked her to launch it from command line, here's the output:

```
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/horizons/engine/generate_atlases.py", line 64, in <module>
from run_uh import init_environment
ImportError: No module named run_uh
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
AL lib: (WW) ALCjackBackendFactory_init: jack_client_open() failed, 0x11
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
Traceback (most recent call last):
File "/usr/games/unknown-horizons", line 380, in <module>
main()
File "/usr/games/unknown-horizons", line 189, in main
ret = horizons.main.start(options)
File "/usr/lib/python2.7/dist-packages/horizons/main.py", line 192, in start
horizons.globals.fife.init()
File "/usr/lib/python2.7/dist-packages/horizons/engine/engine.py", line 178, in init
self._setting.apply()
File "/usr/lib/python2.7/dist-packages/horizons/engine/settings.py", line 91, in apply
change_language(language)
File "/usr/lib/python2.7/dist-packages/horizons/i18n/__init__.py", line 125, in change_language
horizons.globals.fife.pychan.loadFonts(fontdef)
File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/fonts.py", line 88, in loadFonts
for font in Font.loadFromFile(filename):
File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/fonts.py", line 73, in loadFromFile
fonts.append( Font(name,_get) )
File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/fonts.py", line 46, in __init__
self.font.setAntiAlias(self.antialias)
File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 3917, in setAntiAlias
return _fife.GuiFont_setAntiAlias(self, antiAlias)
TypeError: in method 'GuiFont_setAntiAlias', argument 2 of type 'bool'
AL lib: (EE) alc_cleanup: 1 device not closed
```

Any idea about why it doesn't start ?
##

**Comment by LinuxDonald** [comment]
The Version is very old. Maybe you should uninstall it. And compile fife/fifechan and UH by your self?

**Comment by Sancho-Panza** [comment]
Hum ok.. I think it's a little bit hard for her. I just told her to install the package from Debian Stable which seems to work, but ty anyway !

Are you (upstream) in relation with the debian package maintainers ? Or should I ask them to update the package ?

**Comment by LinuxDonald** [comment]
I´m not the packager from debian. But the problem is we don´t have released an new stable Version.
Maybe you should ask the Maintainer if he can update it to the lastest git version. fife and uh.

**Comment by Sancho-Panza** [comment]
Yep' I know you're not. ;) I was talking about the version from Debian Stable, it's older than the one from Testing, but this one works.

Ok, I'll ask the maintainer, thx !

**Comment by LinuxDonald** [comment]
can you maybe link both packages here? i know an debian maintainer

**Comment by Sancho-Panza** [comment]
Not sure if it's what you're asking, but [here's the link](https://packages.debian.org/search?keywords=unknown-horizons&searchon=names&suite=all&section=all&sourceid=mozilla-search).

**Comment by LinuxDonald** [comment]
Christop will fix that when he will find time. And push an new package into experimental.

**Comment by Sancho-Panza** [comment]
Ok, nice, thanks !

**Comment by Jeeppler** [comment]
@zapashcanon please let the debian packager know about your issue, maybe they can fix it in the stable release.

**Comment by LinuxDonald** [comment]
Our debian packager already know the problems and is the maintainer of the package but some packages in Debian are older versions of some libs but we need newer ones and that is the problem at the moment.

**Comment by Jeeppler** [comment]
@LinuxDonald oh, sorry he was talking about Debian Testing not stable. What would be needed to fix the problem?

**Comment by LinuxDonald** [comment]
@MasterofJOKers is working on that. Maybe he can explain it. I don't use Debian.

**Comment by zapashcanon** [comment]
@Jeeppler, to update the package of the dependencies. :p

**Comment by Jeeppler** [comment]
That sounds good :+1:

**Comment by sumpfralle** [comment]
The new version (2017.1) was uploaded to Debian and migrated to "stretch" (the upcoming stable release; entering the freeze tomorrow).
It starts up fine.
Thus this issue can be closed.

**Comment by LinuxDonald** [comment]
@sumpfralle is there any chance to get this git commit into the engine? https://github.com/fifengine/fifengine/commit/2efebb3a0940e2570d2e7abeb54957dcb6f110ea

Because it fixes an big memory leak in the engine :(

**Comment by sumpfralle** [comment]
@LinuxDonald: I am not a Debian Developer - thus I have no power over these issues :(

Debian's [freeze policy](https://release.debian.org/stretch/freeze_policy.html) describes the condiitions for uploads during freeze. Specifically here the following should be applicable:

> fixes for severity: important bugs in packages of priority: optional or extra, only when this can be done via unstable;

The `python-fife` package is "optional" and your description sounds like "important" - thus the minimal requirements are met.
Please read the freeze policy and decide whether an upload would be justified. In this case you should file a bug report against the [package](https://bugs.debian.org/python-fife) (which you should do anyway), mark it as *important* and propose this fix. A minimal and well explained change should be acceptable for the release managers.

The description above applies only to the upcoming stable release. If you are talking about regular uploads to unstable/testing then just file a bug report and/or wait for the next release.
