### ISSUE TITLE
Need irc channel rights 

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2382]
I need the irc channel rights. I'm planning to make an dev blog for uh. Because I have heard that the old site will be maybe closed and I want to make an blog with two languages German and English.

@ChrisOelmueller can you make give me the rights for it please?

**Comment by ChrisOelmueller** [comment]
@LinuxDonald 
To the best of my knowledge, my account holds none of the special permissions you're asking for. How did you associate me with this task?

On the other hand, I'm not sure what IRC "channel rights" are or how they relate to setting up a new website (?) or new blogs (?) so maybe I'm misunderstanding.

**Comment by LinuxDonald** [comment]
I mean that:

Topic for #unknown-horizons is: Welcome to #unknown-horizons | www.unknown-horizons.org | Read the FAQ: http://git.io/gHp13w | Get involved: http://tinyurl.com/uh-get-involved | Channel is logged! | File upload: http://up.unknown-horizons.org/ | http://bugs.unknown-horizons.org | http://translate.unknown-horizons.org
* Topic for #unknown-horizons set by ChrisOelmueller (Mon Apr  7 17:06:53 2014)

**Comment by ChrisOelmueller** [comment]
So you're actually asking for `+t`? Did you check who in the access list can grant that, or whether the channel is locked at all? Otherwise feel free to leave me a message/email with the new desired text and I'll stop by to set it sometime.

**Comment by LinuxDonald** [comment]
I will ask nihathrael for the rights.
Thx for your help eoc :-)

eoc when you will have time to come back into the irc?

**Comment by stubb** [comment]
Should be solved.
