### ISSUE TITLE
typo: two times import AmbientSoundComponent in ingamegui.py

### ISSUE THREAD

**Issue by MarkusHackspacher** [unknown-horizons/unknown-horizons#2392]
Hello,
in the file horizons/gui/ingamegui.py are two time the line 
`from horizons.component.ambientsoundcomponent import AmbientSoundComponent`
in line 29 and 52

https://github.com/MarkusHackspacher/unknown-horizons/blob/master/horizons/gui/ingamegui.py#L29
https://github.com/MarkusHackspacher/unknown-horizons/blob/master/horizons/gui/ingamegui.py#L52

**Comment by MasterofJOKers** [comment]
Did you check other files for duplicate imports, too? Then we could do this in one "Clean up duplicate imports" commit. Would you like to do a Pull-Request for this, then?

**Comment by MarkusHackspacher** [comment]
I use the service from https://www.quantifiedcode.com/ it is an automated code review. It found only  one time this fault.
I´m sorry, I do not want to make a pull request.

**Comment by LinuxDonald** [comment]
Thank you for the report. I will fix that :-)
