### ISSUE TITLE
Why does it take so long to merge pull requests?

### ISSUE THREAD

**Issue by Jeeppler** [unknown-horizons/unknown-horizons#2397]
There are 12 pull requests open, some of them are over three years old. Why does it take so long to merge them?

**Comment by LinuxDonald** [comment]
Because we don't have active Python devs at the moment and that's an big problem for us at the moment sorry

**Comment by Jeeppler** [comment]
There is a difference between merging pull requests and developing new features. Your comment does not answer my question. Is there anybody from the UH team active and capable of reviewing and merging new features?

Not merging work from contributors hinders new developer to participate in the UH development.

**Comment by LinuxDonald** [comment]
Reviewing couldn't be done by two members. Merge can be done by me.

**Comment by LinuxDonald** [comment]
The problem on the prs that we have is that none of them are done. They need all work before they can be merged.

**Comment by Jeeppler** [comment]
@LinuxDonald it would be a good idea to reach out to everyone of them ask for the status and if the person who created it is still working on them, otherwise somebody else can work on them.

**Comment by LinuxDonald** [comment]
I have already done this and no one of them have time to start working on them again.

**Comment by LinuxDonald** [comment]
i have added the link to the starter tasks

**Comment by LinuxDonald** [comment]
I have closed now the old prs. On that no one works at the momnet. Now it should looks better for new devs :)
