### ISSUE TITLE
Flag on Pirate ship shows in the wrong direction.

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2414]
![2016-07-28 18-47-21 671571](https://cloud.githubusercontent.com/assets/1757651/17221384/f9b2cd3c-54f3-11e6-9709-34da8ea306f3.png)

**Comment by MasterofJOKers** [comment]
Could you add a picture of how the flag should be? If I look at the sails, then the wind should be blowing from the back/side so the flag could be correct, couldn't it?

**Comment by MasterofJOKers** [comment]
If anything, the flag in the back of the ship might be wrong. It is at least not possible for this combination of flags to occur.

**Comment by janexx** [comment]
I would say the flag should be rotated around 180°? But I find the shape of the flag a bit weird anyway. Why is it so thin? Would this be right: ?
![pirateship_flag_180degree](https://cloud.githubusercontent.com/assets/6216898/17230142/ee6ed336-551a-11e6-9725-db1bd1ddcba0.png)
If not, please can show somebody how it would be right? Where can the image of the flag be found?

**Comment by MasterofJOKers** [comment]
So the wind is coming from the front, but its a sailing ship - how does it use the wind to go forward if the wind blows from the front?

**Comment by janexx** [comment]
Don't know where the wind is coming from. :) I just see that the ship moves left, so I thought the flag goes right. :) Don't know... Just say how it has to look like and I'll do it. :)

**Comment by LinuxDonald** [comment]
I see i´m wrong but that the pirate flag must be rotated by 180°

**Comment by janexx** [comment]
new suggestion:
![pirateship_flag2](https://cloud.githubusercontent.com/assets/6216898/17232023/8417bb14-5525-11e6-962e-065028bb0283.png)

... And I would delete this weird long flag. Looks weird and has no special function, hasn't it?

**Comment by janexx** [comment]
commit a4852e32d99f858202073634fef23838f0cddbb9

**Comment by LinuxDonald** [comment]
Very good work janexx :+1:
