### ISSUE TITLE
Cursor isn't changed back to normal when TextWidget is hidden

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2416]
https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/engine/pychan_util.py#L196

@stubb could you maybe help to fix this one?
@MasterofJOKers maybe you could write more details here for stubb

**Comment by MasterofJOKers** [comment]
The bug is, at least on my system, reproducible: When saving a game, click into the box to change the name, leave to cursor there, write a name and press enter. Click on the opening dialog and acknowledge it. The game continues and the mouse cursor is a Textcursor and an arrow at the same time.

**Comment by LinuxDonald** [comment]
@nihathrael do you know if this is an uh or fifechan bug?

**Comment by squiddy** [comment]
Whether it is an UH or Fifechan bug depends on ones point of view I guess. There is a comment in the code:

> 	# TODO: if the widget is hidden while the cursor is above it,
> 	# there is no exited event. A possible workaround would be to check
> 	# in short intervals whether the widget is still visible, possible also
> 	# whether the mouse is still above it (the later would be necessary in
> 	# case another widget is drawn above the original widget)
> 	# Since that would be quite ugly, it should only be done when consulting
> 	# pychan-savvy people yields no success.

So yes, there is no exited event. Unfortunately, not when a container is hidden, `hide` isn't called on its children, so we can't even call `unset_cursor` in `Widget.afterHide`. :(

**Comment by prock-fife** [comment]
I'd say this is a pychan bug, however, it might need some more discussion.  I'd suggest that when hide gets called on a widget that afterHide gets called for each child widget recursively.  Would this solve it for you guys?   My original thought was to fire the exit even however that's not really the case because the mouse never did exit.

**Comment by squiddy** [comment]
Hi prock. I think calling afterHide recursively should work, I can try that later today. Not that familiar with pychan, I'm wondering about possible performance implications.

**Comment by MasterofJOKers** [comment]
Another solution would be the ability to set the mouse cursor to another cursor (without manually using mouseEnter and mouseExit) while it's hovering a widget.

**Comment by squiddy** [comment]
But when do you reset the cursor?

**Comment by MasterofJOKers** [comment]
That's not our problem to solve then ;)

**Comment by squiddy** [comment]
Oh, I misunderstood you. You mean, specifying on a widget which icon to show when hovering. Got it. That neatly pushes responsibility to someone else. :D

**Comment by squiddy** [comment]
dulrich mentioned a new event in pychan here https://github.com/unknown-horizons/unknown-horizons/issues/2294#issuecomment-56252815

> It looks like this may be solved easily in a newer version of pychan, which has added several widget events, including widgetHidden.
> 
https://github.com/fifengine/fifengine/blob/ea7ec6f2427bdd6d5c7b845a1a47e414ee0cb9ea/engine/python/fife/extensions/pychan/events.py#L88

Perhaps this is relevant.

**Comment by prock-fife** [comment]
yeah I agree that is relevant.  I would go as far as saying we should perhaps add another event...   a parentWidgetHidden event.  Maybe this over-complicates things a bit.  I would have to put some more thought into it.

**Comment by MasterofJOKers** [comment]
https://github.com/fifengine/fifechan/pull/22/commits/0d44723afa67c1cb1c78bba6b357509988592715 <- is that related?

**Comment by LinuxDonald** [comment]
I could add this change to fifechan this week when it is needed.

**Comment by prock-fife** [comment]
@MasterofJOKers yeah I think you are onto something there.

**Comment by LinuxDonald** [comment]
I will make on the next days an pr for it.

**Comment by LinuxDonald** [comment]
My job is here done add pr on fifechan: https://github.com/fifengine/fifechan/pull/39
When you need another new function from pychan_port branch i will create an pr for it.

**Comment by squiddy** [comment]
Can someone explain how Slider functions relate to this issue, which is about TextWidgets?

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fifechan/pull/39 is now merged maybe it could help.
