### ISSUE TITLE
Memory corruption error

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2424]
First, I installed the game from the official repositories (I'm running Linux Mint), but after 30 seconds the program failed and closed. I didn't know which was that version.

> jorge@jorge-HP-Pavilion-15-Notebook-PC ~ $ unknown-horizons --version
Unknown Horizons <unknown>

So, I decided to clone and test this repository latest version: Unknown Horizons 84e7d32
But still couldn't play more than 30 seconds. I used the full-screen 1366x768 resolution.
Below is the error message I get.

python run_uh.py
*** Error in `python': malloc(): memory corruption: 0x00000000065466e0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7f756c985725]
/lib/x86_64-linux-gnu/libc.so.6(+0x819be)[0x7f756c98f9be]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f756c9915a4]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f7569cdbe78]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm+0x7d)[0x7f7569d6d87d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE8overflowEi+0xe5)[0x7f7569d61cd5]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt15basic_streambufIcSt11char_traitsIcEE6xsputnEPKcl+0x89)[0x7f7569d6be79]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l+0x1a6)[0x7f7569d5cec6]
/usr/lib/python2.7/dist-packages/fife/_fife.so(_ZN4FIFE8Instance6followERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_5RouteEd+0x3a0)[0x7f756a116150]
/usr/lib/python2.7/dist-packages/fife/_fife.so(+0x360b24)[0x7f756a336b24]
python(PyEval_EvalFrameEx+0x771d)[0x4cb26d]
python(PyEval_EvalCodeEx+0x255)[0x4c22e5]
python(PyEval_EvalFrameEx+0x6882)[0x4ca3d2]
python(PyEval_EvalCodeEx+0x255)[0x4c22e5]
python(PyEval_EvalFrameEx+0x6109)[0x4c9c59]
python(PyEval_EvalCodeEx+0x255)[0x4c22e5]
python(PyEval_EvalFrameEx+0x6109)[0x4c9c59]
python(PyEval_EvalFrameEx+0x5dff)[0x4c994f]
python(PyEval_EvalFrameEx+0x5dff)[0x4c994f]
python(PyEval_EvalFrameEx+0x5dff)[0x4c994f]
python(PyEval_EvalFrameEx+0x5dff)[0x4c994f]
python(PyEval_EvalFrameEx+0x5dff)[0x4c994f]
python(PyEval_EvalFrameEx+0x5dff)[0x4c994f]
python(PyEval_EvalCodeEx+0x255)[0x4c22e5]
python(PyEval_EvalCode+0x19)[0x4c2089]
python[0x4f1e6f]
python(PyRun_FileExFlags+0x82)[0x4ec802]
python(PyRun_SimpleFileExFlags+0x191)[0x4eaf81]
python(Py_Main+0x68a)[0x49e36a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f756c92e830]
python(_start+0x29)[0x49dbf9]
======= Memory map: ========
00400000-006e9000 r-xp 00000000 08:02 39457356                           /usr/bin/python2.7
008e9000-008eb000 r--p 002e9000 08:02 39457356                           /usr/bin/python2.7
008eb000-00962000 rw-p 002eb000 08:02 39457356                           /usr/bin/python2.7
00962000-00985000 rw-p 00000000 00:00 0 
021a8000-08c5c000 rw-p 00000000 00:00 0                                  [heap]
7f75317e8000-7f75327e9000 rw-p 00000000 00:00 0 
7f75337f0000-7f75347f1000 rw-p 00000000 00:00 0 
7f75357f7000-7f75377f9000 rw-p 00000000 00:00 0 
7f75387fd000-7f7539ffe000 rw-p 00000000 00:00 0 
7f7539ffe000-7f753c000000 rw-p 00000000 00:00 0 
7f753c000000-7f753c022000 rw-p 00000000 00:00 0 
7f753c022000-7f7540000000 ---p 00000000 00:00 0 
7f7540038000-7f7541ab8000 rw-p 00000000 00:00 0 
7f7542607000-7f7542707000 rw-s 111e31000 00:06 380                       /dev/dri/card1
7f754270e000-7f754278e000 rw-p 00000000 00:00 0 
7f75427b9000-7f75428b9000 rw-s 123c0b000 00:06 380                       /dev/dri/card1
7f75428b9000-7f75429b9000 rw-s 123b0b000 00:06 380                       /dev/dri/card1
7f75429bc000-7f7542abc000 rw-s 11a6d6000 00:06 380                       /dev/dri/card1
7f7542abf000-7f7544000000 rw-p 00000000 00:00 0 
7f7544000000-7f7544021000 rw-p 00000000 00:00 0 
7f7544021000-7f7548000000 ---p 00000000 00:00 0 
7f754802b000-7f754836b000 rw-p 00000000 00:00 0 
7f754838f000-7f754878f000 rw-p 00000000 00:00 0 
7f7548793000-7f7548893000 rw-p 00000000 00:00 0 
7f7548893000-7f7548993000 rw-s 113b8d000 00:06 380                       /dev/dri/card1
7f75489ad000-7f7548bed000 rw-p 00000000 00:00 0 
7f7548c05000-7f7548cc5000 rw-p 00000000 00:00 0 
7f7548cd5000-7f7548e15000 rw-p 00000000 00:00 0 
7f7548e15000-7f7548e16000 ---p 00000000 00:00 0 
7f7548e16000-7f7549616000 rw-p 00000000 00:00 0 
7f7549616000-7f754d617000 rw-s 00000000 00:15 5                          /dev/shm/pulse-shm-541253695
7f754d61e000-7f755161f000 rw-s 00000000 00:15 9                          /dev/shm/pulse-shm-2031771758
7f7551626000-7f7553b18000 r-xp 00000000 08:02 39452815                   /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
7f7553b18000-7f7553d18000 ---p 024f2000 08:02 39452815                   /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
7f7553d18000-7f7553fcd000 r--p 024f2000 08:02 39452815                   /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
7f7553fcd000-7f7553fcf000 rw-p 027a7000 08:02 39452815                   /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
7f7553fcf000-7f7553ff9000 rw-p 00000000 00:00 0 
7f7554000000-7f7554102000 rw-p 00000000 00:00 0 
7f7554102000-7f7558000000 ---p 00000000 00:00 0 
7f7558024000-7f7558124000 rw-p 00000000 00:00 0 
7f755812a000-7f755822a000 rw-p 00000000 00:00 0 
7f755822a000-7f755823a000 rw-s 10fed4000 00:06 380                       /dev/dri/card1
7f755823f000-7f755833f000 rw-s 10f7d1000 00:06 380                       /dev/dri/card1
7f7558344000-7f7558ec4000 rw-p 00000000 00:00 0 
7f7558ec4000-7f7558ec5000 ---p 00000000 00:00 0 
7f7558ec5000-7f7558fc5000 rw-p 00000000 00:00 0 
7f7558fc5000-7f7558fc6000 ---p 00000000 00:00 0 
7f7558fc6000-7f75597c6000 rw-p 00000000 00:00 0 
7f75597c6000-7f75597fd000 r-xp 00000000 08:02 39461762                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7f75597fd000-7f75599fc000 ---p 00037000 08:02 39461762                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7f75599fc000-7f75599fd000 r--p 00036000 08:02 39461762                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7f75599fd000-7f75599fe000 rw-p 00037000 08:02 39461762                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7f7559a05000-7f7559a06000 ---p 00000000 00:00 0 
7f7559a06000-7f755a206000 rw-p 00000000 00:00 0 
7f755a206000-7f755a219000 r-xp 00000000 08:02 34214285                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7f755a219000-7f755a418000 ---p 00013000 08:02 34214285                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7f755a418000-7f755a419000 r--p 00012000 08:02 34214285                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7f755a419000-7f755a41a000 rw-p 00013000 08:02 34214285                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7f755a41a000-7f755a41b000 rw-p 00000000 00:00 0 
7f755a41e000-7f755a44f000 r-xp 00000000 08:02 39460858                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7f755a44f000-7f755a64f000 ---p 00031000 08:02 39460858                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7f755a64f000-7f755a651000 r--p 00031000 08:02 39460858                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7f755a651000-7f755a652000 rw-p 00033000 08:02 39460858                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7f755a652000-7f755a656000 rw-p 00000000 00:00 0 
7f755a656000-7f755a66d000 r-xp 00000000 08:02 39460863                   /usr/lib/x86_64-linux-gnu/libelf-0.165.so
7f755a66d000-7f755a86c000 ---p 00017000 08:02 39460863                   /usr/lib/x86_64-linux-gnu/libelf-0.165.so
7f755a86c000-7f755a86d000 r--p 00016000 08:02 39460863                   /usr/lib/x86_64-linux-gnu/libelf-0.165.so
7f755a86d000-7f755a86e000 rw-p 00017000 08:02 39460863                   /usr/lib/x86_64-linux-gnu/libelf-0.165.so
7f755a86e000-7f755a875000 r-xp 00000000 08:02 39453243                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f755a875000-7f755aa74000 ---p 00007000 08:02 39453243                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f755aa74000-7f755aa75000 r--p 00006000 08:02 39453243                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f755aa75000-7f755aa76000 rw-p 00007000 08:02 39453243                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f755aa76000-7f755aa81000 r-xp 00000000 08:02 39457869                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f755aa81000-7f755ac80000 ---p 0000b000 08:02 39457869                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f755ac80000-7f755ac81000 r--p 0000a000 08:02 39457869                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f755ac81000-7f755ac82000 rw-p 0000b000 08:02 39457869                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f755ac86000-7f755ac8d000 r-xp 00000000 08:02 39453252                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7f755ac8d000-7f755ae8c000 ---p 00007000 08:02 39453252                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7f755ae8c000-7f755ae8d000 r--p 00006000 08:02 39453252                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7f755ae8d000-7f755ae8e000 rw-p 00007000 08:02 39453252                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7f755ae8e000-7f755b755000 r-xp 00000000 08:02 39850735                   /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
7f755b755000-7f755b954000 ---p 008c7000 08:02 39850735                   /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
7f755b954000-7f755b9c8000 r--p 008c6000 08:02 39850735                   /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
7f755b9c8000-7f755b9d7000 rw-p 0093a000 08:02 39850735                   /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
7f755b9d7000-7f755bc4d000 rw-p 00000000 00:00 0 
7f755bc4d000-7f755bc4e000 ---p 00000000 00:00 0 
7f755bc4e000-7f755c64e000 rw-p 00000000 00:00 0 
7f755c64e000-7f755c65d000 r-xp 00000000 08:02 39720934                   /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so
7f755c65d000-7f755c85c000 ---p 0000f000 08:02 39720934                   /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so
7f755c85c000-7f755c85d000 r--p 0000e000 08:02 39720934                   /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so
7f755c85d000-7f755c85f000 rw-p 0000f000 08:02 39720934                   /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so
7f755c866000-7f755c8a6000 rw-p 00000000 00:00 0 
7f755c8a6000-7f755c8b3000 r-xp 00000000 08:02 39720908                   /usr/lib/python2.7/lib-dynload/_elementtree.x86_64-linux-gnu.so
7f755c8b3000-7f755cab2000 ---p 0000d000 08:02 39720908                   /usr/lib/python2.7/lib-dynload/_elementtree.x86_64-linux-gnu.so
7f755cab2000-7f755cab3000 r--p 0000c000 08:02 39720908                   /usr/lib/python2.7/lib-dynload/_elementtree.x86_64-linux-gnu.so
7f755cab3000-7f755cab4000 rw-p 0000d000 08:02 39720908                   /usr/lib/python2.7/lib-dynload/_elementtree.x86_64-linux-gnu.so
7f755cab6000-7f755cbb6000 rw-p 00000000 00:00 0 
7f755cbb6000-7f755cbba000 r-xp 00000000 08:02 34214330                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f755cbba000-7f755cdb9000 ---p 00004000 08:02 34214330                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f755cdb9000-7f755cdba000 r--p 00003000 08:02 34214330                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f755cdba000-7f755cdbb000 rw-p 00004000 08:02 34214330                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f755cdbe000-7f755cdfe000 rw-p 00000000 00:00 0 
7f755cdfe000-7f755ce08000 r-xp 00000000 08:02 39466507                   /usr/lib/x86_64-linux-gnu/libenet.so.7.0.0
7f755ce08000-7f755d007000 ---p 0000a000 08:02 39466507                   /usr/lib/x86_64-linux-gnu/libenet.so.7.0.0
7f755d007000-7f755d008000 r--p 00009000 08:02 39466507                   /usr/lib/x86_64-linux-gnu/libenet.so.7.0.0
7f755d008000-7f755d009000 rw-p 0000a000 08:02 39466507                   /usr/lib/x86_64-linux-gnu/libenet.so.7.0.0
7f755d00e000-7f755d028000 r-xp 00000000 08:02 39722473                   /usr/lib/python2.7/dist-packages/enet.so
7f755d028000-7f755d227000 ---p 0001a000 08:02 39722473                   /usr/lib/python2.7/dist-packages/enet.so
7f755d227000-7f755d228000 r--p 00019000 08:02 39722473                   /usr/lib/python2.7/dist-packages/enet.so
7f755d228000-7f755d22c000 rw-p 0001a000 08:02 39722473                   /usr/lib/python2.7/dist-packages/enet.so
7f755d22e000-7f755d46e000 rw-p 00000000 00:00 0 
7f755d46e000-7f755d474000 r-xp 00000000 08:02 39720912                   /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
7f755d474000-7f755d673000 ---p 00006000 08:02 39720912                   /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
7f755d673000-7f755d674000 r--p 00005000 08:02 39720912                   /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
7f755d674000-7f755d675000 rw-p 00006000 08:02 39720912                   /usr/lib/python2.7/lib-dynload/_hashlib.x86_64-linux-gnu.so
7f755d676000-7f755d745000 r-xp 00000000 08:02 39461714                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f755d745000-7f755d945000 ---p 000cf000 08:02 39461714                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f755d945000-7f755d948000 r--p 000cf000 08:02 39461714                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f755d948000-7f755d94a000 rw-p 000d2000 08:02 39461714                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f755d94a000-7f755d94b000 rw-p 00000000 00:00 0 
7f755d94e000-7f755d960000 r-xp 00000000 08:02 39720924                   /usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so
7f755d960000-7f755db5f000 ---p 00012000 08:02 39720924                   /usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so
7f755db5f000-7f755db60000 r--p 00011000 08:02 39720924                   /usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so
7f755db60000-7f755db62000 rw-p 00012000 08:02 39720924                   /usr/lib/python2.7/lib-dynload/_sqlite3.x86_64-linux-gnu.so
7f755db66000-7f755db72000 r-xp 00000000 08:02 39720888                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7f755db72000-7f755dd71000 ---p 0000c000 08:02 39720888                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7f755dd71000-7f755dd72000 r--p 0000b000 08:02 39720888                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7f755dd72000-7f755dd73000 rw-p 0000c000 08:02 39720888                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7f755dd76000-7f755ddb6000 rw-p 00000000 00:00 0 
7f755ddb6000-7f755ddd3000 r-xp 00000000 08:02 39461962                   /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7f755ddd3000-7f755dfd3000 ---p 0001d000 08:02 39461962                   /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7f755dfd3000-7f755dfd4000 r--p 0001d000 08:02 39461962                   /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7f755dfd4000-7f755dfd5000 rw-p 0001e000 08:02 39461962                   /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7f755dfd6000-7f755e001000 r-xp 00000000 08:02 39722475                   /usr/lib/python2.7/dist-packages/_yaml.so
7f755e001000-7f755e200000 ---p 0002b000 08:02 39722475                   /usr/lib/python2.7/dist-packages/_yaml.so
7f755e200000-7f755e201000 r--p 0002a000 08:02 39722475                   /usr/lib/python2.7/dist-packages/_yaml.so
7f755e201000-7f755e205000 rw-p 0002b000 08:02 39722475                   /usr/lib/python2.7/dist-packages/_yaml.so
7f755e206000-7f755e346000 rw-p 00000000 00:00 0 
7f755e346000-7f755e358000 r-xp 00000000 08:02 34214333                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f755e358000-7f755e558000 ---p 00012000 08:02 34214333                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f755e558000-7f755e559000 r--p 00012000 08:02 34214333                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f755e559000-7f755e55a000 rw-p 00013000 08:02 34214333                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f755e55e000-7f755e5cc000 r-xp 00000000 08:02 34214418                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f755e5cc000-7f755e7cc000 ---p 0006e000 08:02 34214418                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f755e7cc000-7f755e7cd000 r--p 0006e000 08:02 34214418                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f755e7cd000-7f755e7ce000 rw-p 0006f000 08:02 34214418                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f755e7ce000-7f755e7e5000 r-xp 00000000 08:02 34214441                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f755e7e5000-7f755e9e5000 ---p 00017000 08:02 34214441                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f755e9e5000-7f755e9e6000 r--p 00017000 08:02 34214441                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f755e9e6000-7f755e9e7000 rw-p 00018000 08:02 34214441                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f755e9e7000-7f755e9e9000 rw-p 00000000 00:00 0 
7f755e9ee000-7f755ea7b000 r-xp 00000000 08:02 39461810                   /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f755ea7b000-7f755ec7a000 ---p 0008d000 08:02 39461810                   /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f755ec7a000-7f755ec96000 r--p 0008c000 08:02 39461810                   /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f755ec96000-7f755ec97000 rw-p 000a8000 08:02 39461810                   /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f755ec9e000-7f755ed11000 r-xp 00000000 08:02 39460361                   /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f755ed11000-7f755ef11000 ---p 00073000 08:02 39460361                   /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f755ef11000-7f755ef12000 r--p 00073000 08:02 39460361                   /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f755ef12000-7f755ef13000 rw-p 00074000 08:02 39460361                   /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f755ef16000-7f755ef2c000 r-xp 00000000 08:02 34214382                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f755ef2c000-7f755f12b000 ---p 00016000 08:02 34214382                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f755f12b000-7f755f12c000 r--p 00015000 08:02 34214382                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f755f12c000-7f755f12d000 rw-p 00016000 08:02 34214382                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f755f12d000-7f755f12f000 rw-p 00000000 00:00 0 
7f755f136000-7f755f20e000 r-xp 00000000 08:02 34214329                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f755f20e000-7f755f40d000 ---p 000d8000 08:02 34214329                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f755f40d000-7f755f40e000 r--p 000d7000 08:02 34214329                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f755f40e000-7f755f416000 rw-p 000d8000 08:02 34214329                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f755f416000-7f755f417000 rw-p 00000000 00:00 0 
7f755f41e000-7f755f43d000 r-xp 00000000 08:02 34214447                   /lib/x86_64-linux-gnu/libselinux.so.1
7f755f43d000-7f755f63c000 ---p 0001f000 08:02 34214447                   /lib/x86_64-linux-gnu/libselinux.so.1
7f755f63c000-7f755f63d000 r--p 0001e000 08:02 34214447                   /lib/x86_64-linux-gnu/libselinux.so.1
7f755f63d000-7f755f63e000 rw-p 0001f000 08:02 34214447                   /lib/x86_64-linux-gnu/libselinux.so.1
7f755f63e000-7f755f640000 rw-p 00000000 00:00 0 
7f755f646000-7f755f64b000 r-xp 00000000 08:02 39460614                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f755f64b000-7f755f84a000 ---p 00005000 08:02 39460614                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f755f84a000-7f755f84b000 r--p 00004000 08:02 39460614                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f755f84b000-7f755f84c000 rw-p 00005000 08:02 39460614                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f755f84e000-7f755f8b0000 r-xp 00000000 08:02 39461694                   /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f755f8b0000-7f755fab0000 ---p 00062000 08:02 39461694                   /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f755fab0000-7f755fab2000 r--p 00062000 08:02 39461694                   /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f755fab2000-7f755fab3000 rw-p 00064000 08:02 39461694                   /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f755fab3000-7f755fab7000 rw-p 00000000 00:00 0 
7f755fabe000-7f755fac6000 r-xp 00000000 08:02 34214475                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f755fac6000-7f755fcc5000 ---p 00008000 08:02 34214475                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f755fcc5000-7f755fcc6000 r--p 00007000 08:02 34214475                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f755fcc6000-7f755fcc7000 rw-p 00008000 08:02 34214475                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f755fcc7000-7f755fcc8000 rw-p 00000000 00:00 0 
7f755fcce000-7f755fd4e000 r-xp 00000000 08:02 34209858                   /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
7f755fd4e000-7f755fd51000 r--p 0007f000 08:02 34209858                   /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
7f755fd51000-7f755fd52000 rw-p 00082000 08:02 34209858                   /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
7f755fd52000-7f755fd53000 rw-p 00000000 00:00 0 
7f755fd56000-7f756160c000 r-xp 00000000 08:02 39461246                   /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f756160c000-7f756180b000 ---p 018b6000 08:02 39461246                   /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f756180b000-7f756180c000 r--p 018b5000 08:02 39461246                   /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f756180c000-7f756180d000 rw-p 018b6000 08:02 39461246                   /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f756180e000-7f7561819000 r-xp 00000000 08:02 39461304                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7f7561819000-7f7561a18000 ---p 0000b000 08:02 39461304                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7f7561a18000-7f7561a19000 r--p 0000a000 08:02 39461304                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7f7561a19000-7f7561a1c000 rw-p 0000b000 08:02 39461304                   /usr/lib/x86_64-linux-gnu/libjbig.so.0
7f7561a1e000-7f7561a3f000 r-xp 00000000 08:02 34214356                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f7561a3f000-7f7561c3e000 ---p 00021000 08:02 34214356                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f7561c3e000-7f7561c3f000 r--p 00020000 08:02 34214356                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f7561c3f000-7f7561c40000 rw-p 00021000 08:02 34214356                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f7561c46000-7f7561c6b000 r-xp 00000000 08:02 34214461                   /lib/x86_64-linux-gnu/libtinfo.so.5.9Aborted

**Comment by LinuxDonald** [comment]
What version of fife and fifechan do you use? For UH Git version do you need lastest fife and fifechan git versions:

https://github.com/fifengine/fifengine
https://github.com/fifengine/fifechan

**Comment by jorgesumle** [comment]
I can't install fifeengine. I followed each step but it fails.

jorge@jorge-HP-Pavilion-15-Notebook-PC ~/Code/fifengine $ scons
scons: Reading SConscript files ...
Checking for vorbisfile (using pkg-config)...no
Checking for vorbisfile (using vorbisfile-config)... no
Checking for C++ library vorbisfile... yes
Checking for python2.7 (using pkg-config)...no
Checking for python2.7 (using python2.7-config)... yes
Checking for openal (using pkg-config)...no
Checking for openal (using openal-config)... no
Checking for C++ library openal... yes
Checking for SDL2 (using pkg-config)...no
Checking for SDL2 (using SDL2-config)... no
Checking for C++ library SDL2... no
Required lib SDL2 not found!

**Comment by janexx** [comment]
You have to install SDL2. Please see http://www.unknown-horizons.org/download/sources/s-linux/
You need all the packages (dependencies) listed there.

**Comment by jorgesumle** [comment]
I've done all that and it crashes again.

**Comment by LinuxDonald** [comment]
With the same error? Have you removed the old version of fife and fifechan before you compiled the git versions?

**Comment by jorgesumle** [comment]
OK, I finally managed to install it, but got a warning: 
running build_i18n
warning: _build_i18n: Can't generate desktop files, needs intltool-merge. Try installing the package 'intltool'.

Discovered old settings file, auto-upgrading: 1 -> 38
Recreating all atlases

After installing it, despite the warning, I could play without problem. But I installed it to get the language support. I think it's a good idea to add intltool-merge to the dependencies list from http://www.unknown-horizons.org/download/sources/s-linux/

Also, there are some little errors in the spanish translation and sometimes English text is mixed with Spanish text. How can I help with that. I need some quick guide about how translations work and what should I install and do to make a useful pull request.

**Comment by LinuxDonald** [comment]
For deps i created an issue: 2428

Because of language translation you can find it here:
https://hosted.weblate.org/projects/uh/
You can log in there with your github accout and start to review and update the translation.
It would be nice when you could bring it up to date :)

**Comment by jorgesumle** [comment]
> It would be nice when you could bring it up to date :)
Of course, I'm doing it right now. There are some outdated spanish translations. That's why some parts of the tutorial sounded weird for me.
