### ISSUE TITLE
Translations scripts problem.

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2425]
I cant´t excute ./development/create_pot.sh without an error....

[linuxdonald@linuxdonald-pc unknown-horizons]$ ./development/create_pot.sh
        Warning:  Icon without name. Add unique name if desired: text="(like in the selection tabs)"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="(like in the selection tabs)"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
   * Regenerated xml translation file at horizons/gui/translations.py.
   * Wrote xml translation template to po/uh/unknown-horizons.pot.
Traceback (most recent call last):
  File "development/extract_strings_from_objects.py", line 116, in <module>
    from horizons.constants import TIER, RES, UNITS, BUILDINGS
ImportError: No module named horizons.constants
[linuxdonald@linuxdonald-pc unknown-horizons]$ 

@MarkusHackspacher could you maybe help here?

**Comment by LinuxDonald** [comment]
@stubb have you maybe time? :(

**Comment by MarkusHackspacher** [comment]
I test and the first run was
```
$ ./development/create_pot.sh
./development/create_pot.sh: 41: ./development/create_pot.sh: Syntax error: "(" unexpected
```
I change the first line into #!/bin/bash instant of #!/bin/sh
```
$ ./development/create_pot.sh
        Warning:  Icon without name. Add unique name if desired: text="(like in the selection tabs)"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="(like in the selection tabs)"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
        Warning:  Icon without name. Add unique name if desired: text="$res"
   * Regenerated xml translation file at horizons/gui/translations.py.
xargs: itstool: Datei oder Verzeichnis nicht gefunden
```
on my side is go no version info from sh, maybe sh is not on my computer.
```
$ bash --version
GNU bash, Version 4.3.30(1)-release (x86_64-pc-linux-gnu)
$ /bin/sh --version
/bin/sh: 0: Illegal option --
```

**Comment by LinuxDonald** [comment]
You need to install itstool see the last line from your first log.

**Comment by LinuxDonald** [comment]
I think this is now an new error :(
Now i become this error:

Traceback (most recent call last):
  File "development/extract_strings_from_objects.py", line 196, in <module>
    output = '%s%s%s' % (HEADER, '\n'.join(filesnippets), FOOTER)
  File "development/extract_strings_from_objects.py", line 194, in <genexpr>
    filesnippets = (content for content in filesnippets if content != '')
  File "development/extract_strings_from_objects.py", line 193, in <genexpr>
    filesnippets = (content_from_file(filename) for filename in list_all_files())
  File "development/extract_strings_from_objects.py", line 169, in content_from_file
    add_line(value, component, '', '', filename)
  File "development/extract_strings_from_objects.py", line 161, in add_line
    text = '_("{value}")'.format(value=value[2:])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 15: ordinal not in range(128)

**Comment by MarkusHackspacher** [comment]
Yes you get more UnicodeEncodeError, for this line, you add a `u`
text = u'_("{value}")'.format(value=value[2:])
 
u'...' is for unicode.
this works for the next fault, too.
But than you got this:
```
    file(sys.argv[1], 'w').write(unicode(output))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 4138: ordinal not in range(128)
```
Than you have to locate the fault, add a print output[4100:4150], because for looking `position 4138`
```
if len(sys.argv) > 1:
    print output[4100:4150]
    file(sys.argv[1], 'w').write(output)
```
The output like this: "Produces Cannon´s.", look for the string in the project and add a u.
