### ISSUE TITLE
Write an new dependencies site on the github Wiki.

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2428]
We need an updatet dependencies site.
We should create it here on the github wiki.

**Comment by jorgesumle** [comment]
Why don't we just update the website? (http://www.unknown-horizons.org/download/sources/s-linux/)

**Comment by janexx** [comment]
Unforuntately the owner of the website is not active/reachable anymore. Here on github everyone has access.
By the way I recently had problems to install UH because I had not installed tinyxml. This is also not mentioned as dependency.

**Comment by LinuxDonald** [comment]
Okay thx janexx :-) and yes the website maintainer is inactive.. :-(

**Comment by jorgesumle** [comment]
Have you tried contacting him: 

> Responsible Person for Content
> 
> Tobias Schröfel
> Hohlstraße 112
> 41747 Viersen
> Germany
> tschroefel@gmail.com


Or the domain owner (http://www.whois.com/whois/unknown-horizons.org):

> Admin Name: Thomas Kinnen
> Admin Organization:
> Admin Street: Georg-Wopfner-Str. 44
> Admin City: Muenchen
> Admin State/Province:
> Admin Postal Code: 80939
> Admin Country: DE
> Admin Phone: +49.17664170040
> Admin Phone Ext:
> Admin Fax: +32.229982891
> Admin Fax Ext:
> Admin Email: email@gmail.co

**Comment by MasterofJOKers** [comment]
Should we really post this personal information on github? I'm sure I would not want my address to be found here.

**Comment by LinuxDonald** [comment]
Yeah that is not good to post it here. On the other side is public on our homepage.

**Comment by jorgesumle** [comment]
I see no problem, it is already public and anyone can get them in a less than a minute. Everyone that has a website knows that. Edited and just left the emails, but it makes no difference is public anyway.

**Comment by MasterofJOKers** [comment]
It makes a difference in that the whois is not indexed by google afaik but github should be. Additionally, searching on github does not reveal whois information. So yes, it is public, but it is not ours to distribute.

**Comment by LinuxDonald** [comment]
I think we should create news Site and Forum and change our domain to our new site/blog than.

**Comment by LinuxDonald** [comment]
I have now admin access to the site i will fix deps today on the website.

**Comment by jorgesumle** [comment]
> I have now admin access to the site i will fix deps today on the website.

Change also the copyright year: 

- © The Unknown Horizons Developers 2011
+ © The Unknown Horizons Developers 2016

**Comment by LinuxDonald** [comment]
@nihathrael do you know where i can change the year?

**Comment by LinuxDonald** [comment]
Fixed.
