### ISSUE TITLE
Improve english text from tutorial

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2430]
I have encountered some little things that I thing could be improved from the English text. e.g. 

- From now on we'll refer to this area containing the mini-map and various buttons and tabs as the 'Overview'. 
+ From now on, we'll refer to this area containing the mini-map, various buttons and tabs as the 'Overview'. 
# From now on is an adverbial phrase (http://grammartips.homestead.com/adverbs1.html)
# Two 'and's together sound confusing, better a comma and an 'and'.

I'm new doing this, where should I change the English text? Also, if I made any mistake correct me, I'm not a native english speaker.

**Comment by LinuxDonald** [comment]
English text can be changed only from the dev team. Because English is the native language.

@janexx what do you think about that change?

**Comment by janexx** [comment]
The suggestion of @jorgesumle is good. I would say its correct (I am no native English speaker as well). I also don't know where to change the English text. Seems that this is not handled with weblate? @LinuxDonald, do you know where this must be changed?

**Comment by LinuxDonald** [comment]
I know how to change it. I will do it tomorrow. @jorgesumle when you find more that maybe should changed please post it here :-)

**Comment by jorgesumle** [comment]
@LinuxDonald Tell me so I can learn :)
Or can I learn simply viewing the commit?

**Comment by LinuxDonald** [comment]
@jorgesumle you must have access to the code to change this ;-)
(Source Code of the game) only dev Team members can do that. All other languages can be translated from all user of the world on weblate.

**Comment by LinuxDonald** [comment]
@jorgesumle I will show you tomorrow how to update it :-)

**Comment by LinuxDonald** [comment]
How todo:

Do your changes in: content/scenarios/tutorial_en.yaml
Excute:
sh development/create_scenario_pot.sh tutorial
./development/update_translations.py

both in the UH Main dir.

For all changes do it please with pull requests.
