### ISSUE TITLE
update_translations.py fails when I try to update the English text from the tutorial

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2432]
$ sh development/create_scenario_pot.sh tutorial
$ ./development/update_translations.py
Traceback (most recent call last):
  File "./development/update_translations.py", line 154, in <module>
    main()
  File "./development/update_translations.py", line 116, in main
    update_authors_per_file(f)
  File "./development/update_translations.py", line 98, in update_authors_per_file
    ], stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'shortlog', 'weblate-credits..', '--committer', 'Weblate', '-sn', '--', 'po/uh/lv.po']' returned non-zero exit status 128

**Comment by LinuxDonald** [comment]
Could you please excute both scripts on an clean git checkout? Both script runs fine for me on Arch Linux with lastest git of uh.

**Comment by LinuxDonald** [comment]
To test if it works without any changes on it.

**Comment by jorgesumle** [comment]
Then, I get a different error message.
![captura de pantalla de 2016-08-17 10 19 51](https://cloud.githubusercontent.com/assets/14212780/17729410/5b65cce4-6464-11e6-9ae3-81e46a732164.png)

**Comment by ChrisOelmueller** [comment]
Seems like there's an issue with the username being non-ascii in your case (the `ó`).

Guessing here, but could you try replacing the  `unicode(__file__)`  call with  `unicode(__file__, 'utf-8'))`  and see if that helps?

**Comment by jorgesumle** [comment]
Sorry for that, ignore it, I forgot to run ./setup.py build_i18n && ./run_uh.py. Anyway, tested again without changes and got the same error as before. Something wrong with translations.py

**Comment by jorgesumle** [comment]
error line 98. Line 100: #TODO Clearly the above can never fail, ever. But what if it did? 
XD

**Comment by jorgesumle** [comment]
There is maybe some issue with my git version: git version 1.9.1

**Comment by jorgesumle** [comment]
Here is the output I get running the command with git.
jorge@jorge-All-Series:~/unknown-horizons$ git shortlog weblate-credits.. --committer Weblate -sn -- po/uh/lv.po
fatal: bad revision 'weblate-credits..'
jorge@jorge-All-Series:~/unknown-horizons$ echo $?
128

**Comment by jorgesumle** [comment]
OK, I figured it out, I shouldn't have used `git clone --depth`. My fault.

**Comment by jorgesumle** [comment]
I got a different error. Again, I was trying to update translations. It's a clean git repository, I had just executed `git pull` and then changed tutorial_en.yaml and tried to update translations.
[tutorial_en.yaml.txt](https://github.com/unknown-horizons/unknown-horizons/files/441154/tutorial_en.yaml.txt)

jorge@jorge-All-Series:~/Programas/unknown-horizons$ sh development/create_scenario_pot.sh tutorial
jorge@jorge-All-Series:~/Programas/unknown-horizons$ ./development/update_translations.py
Updating po/uh-server/lv.po:
......... terminado.
Updating po/uh-server/zh_CN.po:
..... terminado.
Updating po/uh-server/frp.po:
......... terminado.
Updating po/uh-server/sk.po:
......... terminado.
Traceback (most recent call last):
  File "./development/update_translations.py", line 154, in <module>
    main()
  File "./development/update_translations.py", line 121, in main
    update_authors_per_file(f)
  File "./development/update_translations.py", line 108, in update_authors_per_file
    english_lang = LANGUAGENAMES.get_english(lang)
  File "/home/jorge/Programas/unknown-horizons/horizons/constants.py", line 612, in get_english
    return self.get(key, [key])[1]
IndexError: list index out of range

**Comment by LinuxDonald** [comment]
Maybe because we have now added sk language. I will check that later
