### ISSUE TITLE
Some English text little errors

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2433]
po/scenarios/es/tutorial.po, translation unit 29 
> in  construction or trade.
two spaces between "in" and "construction"

Throughout the tutorial words like overview, tent, main square...  should be uppercase when they refer to a game element.

**Comment by jorgesumle** [comment]
po/scenarios/es/tutorial.po, translation unit 32 
> You will need to have some food-producing companies, too,
I think the comma before 'too' is not necessary

**Comment by jorgesumle** [comment]
It shouldn't be 'Marineros' (sailors in spanish), should be Settler Overview. Also when I hover, the word sailor isn't even translated (also shouldn't be sailor, an error inherited from the english text). That tab references Sales y 
![captura de pantalla de 2016-08-16 12 40 10](https://cloud.githubusercontent.com/assets/14212780/17696467/cf50d04c-63ae-11e6-9cdb-8f9e9feac1da.png)

**Comment by LinuxDonald** [comment]
When you want you can do an pull request with your changes for: unknown-horizons/content/scenarios/tutorial_en.yaml

The po files i will create than until we we fixed your problem with translations.

For the GUI. I will take an look on it at the next days.

**Comment by LinuxDonald** [comment]
Is the screenshot from Main Square gui? Than it is correct. The English Version dont show an settler overview on that place.

**Comment by jorgesumle** [comment]
That part was correct, because it referenced the I-Tier buildings (which correspond to sailors). I was wrong with that. The other errors have been corrected.
