### ISSUE TITLE
Button to restart game after adjusting Settings when restart required? 

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2434]
What about asking the user if he wants to restart the game, when changes need a restart? We could leave the tick icon which is already there, and add a close button.
![captura de pantalla de 2016-08-16 13 31 31](https://cloud.githubusercontent.com/assets/14212780/17697632/2c60b764-63b6-11e6-9400-30d7fe2df03e.png)

**Comment by jorgesumle** [comment]
I got it working: https://github.com/jorgesumle/unknown-horizons. However, when you mess with changing to fullscreen and restarting the game from my prompt the os resolution is messed up. Am I'm missing something? How should I close Unknown Horizons properly?
![captura de pantalla de 2016-08-16 17 34 33](https://cloud.githubusercontent.com/assets/14212780/17705253/07bcfe96-63d8-11e6-9aa1-8f440153ab5e.png)
![captura de pantalla de 2016-08-16 17 34 55](https://cloud.githubusercontent.com/assets/14212780/17705271/1113d4e2-63d8-11e6-8f06-3c9fb6d99a4c.png)

**Comment by LinuxDonald** [comment]
Maybe say UH that is should close and excute run_uh.py ?
Or look how run_uh.py starts uh.

**Comment by jorgesumle** [comment]
I only have to exit fullscreen mode before restarting the game, but how do I do that?

**Comment by LinuxDonald** [comment]
Maybe that can help you? https://github.com/fifengine/fifengine/search?utf8=%E2%9C%93&q=setFullScreen

@stubb could you maybe help here please?

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fifengine/issues/521
https://github.com/fifengine/fifengine/issues/331

maybe this helps?

**Comment by jorgesumle** [comment]
Cool, it worked. If the pull request is accepted, you can close this issue.
