### ISSUE TITLE
Complete entry on Free Software Directory

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2439]
I've added Unknown Horizons to the [Free Software Directory](http://directory.fsf.org/wiki/Main_Page), so that more people can find it and hopefully we get more support from the free software community. But there is still some missing information that I don't know how to fill in. For example, the information to donate and person info (I think everyone should fill in their info personally). So if you want to edit the entry, feel welcome to do that, if you don't have an account, it's easy to create, but you can also contact anyone from the FSF via #fsf on freenode or tell me and I'll edit the entry. Right now the entry page is pending approval.
![captura de pantalla de 2016-08-22 07 39 04](https://cloud.githubusercontent.com/assets/14212780/17844669/02e53902-683c-11e6-8a01-27c79de60cb1.png)
![captura de pantalla de 2016-08-22 07 35 34](https://cloud.githubusercontent.com/assets/14212780/17844672/0972c5fa-683c-11e6-9795-45d3592e4bfb.png)

**Comment by MasterofJOKers** [comment]
There's a "Donate" link on our homepage linking to [this wiki page](https://github.com/unknown-horizons/unknown-horizons/wiki/Donation-History):

> we don't need money right now

**Comment by MasterofJOKers** [comment]
Should we add our dependencies there, too?

**Comment by jorgesumle** [comment]
OK, cool we should also mention bounties in that wiki page. I [edited](https://github.com/unknown-horizons/unknown-horizons/wiki/Donation-History) that.

> Should we add our dependencies there, too?

I prefer only mentioning the dependencies here because if we change the dependencies or add any new dependency, the entry becomes outdated. But if anyone wants to also add the dependencies there, is free to do that (I think it's the Software prerequisites tab where dependencies are added).

**Comment by jorgesumle** [comment]
OK, I think the entry has enough info now. We just have to wait until approval. The only incomplete thing is the person info. You can add your name and email there whenever you want. There is a wiki article [here](https://github.com/unknown-horizons/unknown-horizons/wiki/Who-is-who), but I don't want to add those people without telling them.
![captura de pantalla de 2016-08-22 09 41 36](https://cloud.githubusercontent.com/assets/14212780/17847358/dcb4bf0c-684d-11e6-810b-efb6e2d7fa3b.png)
This is how that section will look like when our entry is aproved (snapshot taken from the Emacs entry):
![captura de pantalla de 2016-08-22 09 41 36](https://cloud.githubusercontent.com/assets/14212780/17847330/b7663cd0-684d-11e6-9df2-a1f710c3a5cd.png)
If there is not any question or suggestion in a week, I'll close this issue.

**Comment by LinuxDonald** [comment]
Have you an link for me that i can add me?

**Comment by jorgesumle** [comment]
> Have you an link for me that i can add me?
You need an account, then you can edit any entry: [https://directory.fsf.org/wiki/Unknown_horizons](https://directory.fsf.org/wiki/Unknown_horizons). I can add you if you want, I just need your Real Name, Role and Email.

**Comment by LinuxDonald** [comment]
Real Name: Thomas Kowaliczek
Role: Project Leader
E-Mail: linuxdonald@posteo.de

**Comment by jorgesumle** [comment]
> Real Name: Thomas Kowaliczek
> Role: Project Leader
> E-Mail: linuxdonald@posteo.de

[Added](https://directory.fsf.org/wiki?title=Unknown_horizons&diff=36122&oldid=36119) :)

**Comment by janexx** [comment]
@jorgesumle  Can you please add me too?
Real Name: Jana Weigel
Role: Graphic Artist
E-Mail: jana@gnu.de.vc

**Comment by jorgesumle** [comment]
> Real Name: Jana Weigel
> Role: Graphic Artist
> E-Mail: jana@gnu.de.vc
[Added](https://directory.fsf.org/wiki?title=Unknown_horizons&diff=36127&oldid=36122) :)

**Comment by LinuxDonald** [comment]
Close this now because the article is online.

**Comment by janexx** [comment]
It can be found here:
http://directory.fsf.org/wiki/Unknown_horizons
