### ISSUE TITLE
Improve README.md, it's very misleading and confusing

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2441]
The "Dependencies, Building and Running" is useless and misleading, as it only shows how to install fife engine. Also, installation instructions are very difficult to spot for new people and I found some markdown error with the links. (`http://www.unknown-horizons.org/`, should be `[http://www.unknown-horizons.org/](http://www.unknown-horizons.org/)`, it displays well because GitHub automatically corrects it, but it's not proper written markdown).

**Comment by jorgesumle** [comment]
I have changed the README.md file. Please, tell me what you think. I have made a radical change, so be sure to point out any error I made. @konstin, I think is much more organized now, what do you think?

**Comment by MasterofJOKers** [comment]
I haven't looked at it (looked through my mails) and have a general advice: If you want to make radical changes, create a pull-request first to get opinions instead of chaning first and asking later.

**Comment by janexx** [comment]
Its not very radical I would say, the  changes/corrections you made are good. Thanks!

**Comment by LinuxDonald** [comment]
For me it looks good.

**Comment by konstin** [comment]
Am I missing something or is there still no link to the build guide?

**Comment by LinuxDonald** [comment]
@jorgesumle i think that should be linked to in the readme: http://www.unknown-horizons.org/download/sources/s-linux/

**Comment by jorgesumle** [comment]
> If you want to make radical changes, create a pull-request first to get opinions instead of chaning first and asking later.
Sorry for that, you're right. Next time I'll do that.
> Am I missing something or is there still no link to the build guide?
The old build guide, was incomplete and misleading: it only showed how to install fife engine, but with fifengine alone you can't play Unknown Horizons, the correct guide is here: http://www.unknown-horizons.org/download/sources/s-linux/. The link to fifengine and fifechan repos are still there, so there is no lost information.
> @jorgesumle i think that should be linked to in the readme: http://www.unknown-horizons.org/download/sources/s-linux/
It is, under Installation section: [https://github.com/unknown-horizons/unknown-horizons#installation](https://github.com/unknown-horizons/unknown-horizons#installation).

**Comment by jorgesumle** [comment]
> @jorgesumle i think that should be linked to in the readme: http://www.unknown-horizons.org/download/sources/s-linux/

>> It is, under Installation section: https://github.com/unknown-horizons/unknown-horizons#installation.


Sorry, I confused. I'll add that.

**Comment by jorgesumle** [comment]
This is my proposal for the Installation section, what do you think?

# Installation

## Simple installation

For installation instructions check the "Downloads" section on
[our website](http://www.unknown-horizons.org/download/).

## Installing from sources

If you want to get the latest version of the game, you have to
install it from source:
* [Instructions for GNU/Linux](http://www.unknown-horizons.org/download/sources/s-linux/)
* [Instructions for Windows](http://www.unknown-horizons.org/download/sources/s-windows/)
* [Instructions for OS X](http://www.unknown-horizons.org/download/sources/s-osx/)

**Comment by LinuxDonald** [comment]
looks goot for me.

**Comment by konstin** [comment]
What About the following:

---

## Installation

For installation instructions check the "Downloads" section on
[our website](http://www.unknown-horizons.org/download/)

## Building from source

If you want to get the latest version of the game, you have to
build it from source:

 * [Instructions for GNU/Linux](http://www.unknown-horizons.org/download/sources/s-linux/)
 * [Instructions for Windows](http://www.unknown-horizons.org/download/sources/s-windows/)
 * [Instructions for OS X](http://www.unknown-horizons.org/download/sources/s-osx/)

If you want to start hacking on Unknown Horizons, check out [this guide](https://github.com/unknown-horizons/unknown-horizons/wiki/Getting-started) and contact us to help you get started. We have easy tasks for starters [here](https://github.com/unknown-horizons/unknown-horizons/issues?q=is%3Aopen+is%3Aissue+label%3Astarter).

---

Markdown:
```
## Installation

For installation instructions check the "Downloads" section on
[our website](http://www.unknown-horizons.org/download/)

## Building from source

If you want to get the latest version of the game, you have to
build it from source:

 * [Instructions for GNU/Linux](http://www.unknown-horizons.org/download/sources/s-linux/)
 * [Instructions for Windows](http://www.unknown-horizons.org/download/sources/s-windows/)
 * [Instructions for OS X](http://www.unknown-horizons.org/download/sources/s-osx/)

If you want to start hacking on Unknown Horizons, check out [this guide](https://github.com/unknown-horizons/unknown-horizons/wiki/Getting-started) and contact us to help you get started. We have easy tasks for starters [here](https://github.com/unknown-horizons/unknown-horizons/issues?q=is%3Aopen+is%3Aissue+label%3Astarter).
```

**Comment by LinuxDonald** [comment]
Looks good to.

**Comment by janexx** [comment]
Even better, @konstin The only thing thats not so nice, is the double beginning with "If you want to". But I have no better proposal. So I think its good.

**Comment by konstin** [comment]
The repetition is indeed not so nice. Let's just remove the first if-you-want sentence.

**Comment by janexx** [comment]
Yeah maybe just: 
To get the latest version of the game, you have to build it from source:

**Comment by jorgesumle** [comment]
@konstin, I like it. With janexx suggestion 

> (To get the latest version of the game, you have to build it from source)

sounds really nice. Just make a pull request.

**Comment by konstin** [comment]
Done.
