### ISSUE TITLE
Missing copy of the GPL?

### ISSUE THREAD

**Issue by donaldr3** [unknown-horizons/unknown-horizons#2445]
It looks like the project doesn't actually contain a copy of the GPL, even though it's clear that this is a GPLed project. Including a copy of the license is a condition of the GPL, so please make sure to include a copy of the license. I caught this when reviewing this game for inclusion in the Free Software Directory, so message me when you get it fixed so I can complete the review and get your entry approved. Thanks.

**Comment by LinuxDonald** [comment]
The license file is here: https://github.com/unknown-horizons/unknown-horizons/blob/master/doc/licenses/GPL

**Comment by donaldr3** [comment]
Thanks, the entry has been approved.
