### ISSUE TITLE
Game is laggy

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2446]
Game is laggy through all the gameplay. Running mid-end PC.
i3-4130, GTX 650, 8Gb RAM, 7200RPM HDD

When you select building it laggs or even on scrolling
##

**Comment by LinuxDonald** [comment]
What version are you playing? (version of UH and fife)
And are you playing with a.i. or without?

**Comment by CrafterSvK** [comment]
I am running latest git version. But the same thing happens in 2014 version from AUR. I am playing with AI.

**Comment by LinuxDonald** [comment]
Ah okay. We know that there is an lag problem. And with a.i. it lags more. Sorry for that. We don't know if we can fix that for the next release. :-(

**Comment by CrafterSvK** [comment]
No problem. Good luck. Looking forward to it

**Comment by jorgesumle** [comment]
@CrafterSvK, I have reopened your issue, we will close it when we fix your problem.

**Comment by LinuxDonald** [comment]
Big lag problem is fixed with fife engine master git version. Fix with next stable release will be fife 0.4.1 and uh 2017.2.
