### ISSUE TITLE
Text out of its field

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2448]
Text is sometimes out of its field especially "building cost" where tools are out of its field.

**Comment by MasterofJOKers** [comment]
Could you add a screenshot, please?

**Comment by CrafterSvK** [comment]
![unknown-horizons](https://cloud.githubusercontent.com/assets/8365659/18048598/5ed17512-6de3-11e6-913b-ca9342cdc0a4.png)
Here you are

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/pull/2383

**Comment by CrafterSvK** [comment]
Is that a box with cost info and building info scripted or it is picture?

**Comment by ChrisOelmueller** [comment]
The bug here is that the icons inside the tooltip do not seem to resize. They're supposed to be much smaller (16x16 IIRC) and thus there should be more space for the text to fit in.

As far as tweaking the tooltips, once upon a time I started work on that, but it went nowhere.

**Comment by CrafterSvK** [comment]
They have to resize but they didn't?

**Comment by ChrisOelmueller** [comment]
The coins, boards, tools in the first line, yes.

**Comment by CrafterSvK** [comment]
That's weird. Can you send me a link onto exact python file please?

**Comment by ChrisOelmueller** [comment]
You can start digging here: https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/gui/tabs/buildtabs.py#L150

**Comment by CrafterSvK** [comment]
Too complicated for Java programmer. But it looks like it should work.
