### ISSUE TITLE
Scenario default language

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2451]
When you try to play scenario it selects first language available not the one you set in options. Would be great if it selects english as default or the one you selected in options when available.
##

**Comment by MasterofJOKers** [comment]
I cannot reproduce that. It works for me, even if I change the language, while the game is running.

**Comment by LinuxDonald** [comment]
For me it works too no problems. @CrafterSvK could you maybe recheck this?

**Comment by CrafterSvK** [comment]
It works for languages that have translated tutorial. If you have not it will select Catalana or something like that and than it doesn't recheck on the other scenario and keeps Catalana... (Sorry but I am ill. So i can't concentrate on what I am typing)

**Comment by MasterofJOKers** [comment]
That's a much better explanation. Thank you.

**Comment by squiddy** [comment]
@CrafterSvK Hi, I've submitted a patch with modified behaviour here: https://github.com/unknown-horizons/unknown-horizons/commit/3bc51f602a0f54fcf38fea9cdc035d196b409819 Perhaps you can try it out. :-)

**Comment by LinuxDonald** [comment]
I have tested it a bit. For me it works. That language that i select in the options get selectetd to in the scenario by default
