### ISSUE TITLE
Translation {key} problem

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2452]
I am working on Slovak translation. So I checked few translations so I know how to do {key}, {player} and so on.
![unknown-horizons2](https://cloud.githubusercontent.com/assets/8365659/18053945/123298c0-6e02-11e6-9536-ddcd99d43638.png)
 As you can see. Translation doesn't show the key but string called {key}

**Comment by LinuxDonald** [comment]
Can you give me the link on weblate where do you found the {key} that i can take an look on it

**Comment by CrafterSvK** [comment]
This is one of them https://hosted.weblate.org/translate/uh/uh/sk/?q=%7Bkey%7D&search=substring&source=on&target=on&type=all&ignored=False

**Comment by LinuxDonald** [comment]
Good question what is going wrong here :(

**Comment by jorgesumle** [comment]
git checkout 9ecf5e5a156f30d32ad14466543856d5e6c2b824 works fine, so this is a problem with a change we've done recently.

**Comment by MasterofJOKers** [comment]
Or a local problem.

**Comment by CrafterSvK** [comment]
Could not be. UH was reinstalled instead of pulled just in case.

**Comment by LinuxDonald** [comment]
Maybe edit the String from: Zrýchliť rýchlosť hry ({key})
to: "Zrýchliť rýchlosť hry" ({key})
but dont know if that works. Or we must maybe change something UH. Maybe UTF-8 Support  (when we dont have it allready)

We will take an look at that problem :)

**Comment by LinuxDonald** [comment]
But you can work on the Translation :) the {(key)} problem we will fix it.

**Comment by CrafterSvK** [comment]
Thanks I will still work on it :)

**Comment by MasterofJOKers** [comment]
So I've tinkered with it and it does work. But it requires a restart of the game after changing the language to fill the `{key}`s.

**Comment by CrafterSvK** [comment]
Yes it works just fine. It would be great to get pop-up message after changing translation or fix this problem. :) Thanks again

**Comment by MasterofJOKers** [comment]
That or even better: Initializing the translated messages correctly as done when starting the game. I prefern the second approach.

**Comment by CrafterSvK** [comment]
Well good luck then. :)

**Comment by MasterofJOKers** [comment]
Should be fixed in latest master.
