### ISSUE TITLE
Translation finished

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2453]
Slovak translation is finished. Can you please force wire it to the github. It was updated 27 minutes ago but it has been completed now.

**Comment by jorgesumle** [comment]
It will be done automatically. Don't worry about that. From my experience it never takes more than two days, sometimes within minutes is up.

**Comment by MasterofJOKers** [comment]
Your translations have now reached our repository. Thank you very much for your contribution (and the bug reports)!
