### ISSUE TITLE
Slovak language 

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2454]
Sorry for my spamming on your issues but I have translated the whole game into slovak language. Git was updated so I grab that revision using git pull. Slovak language is not translated in the game. There is a lot of english text.

**Comment by MasterofJOKers** [comment]
If you grabbed it from from git, you need to run `./setup.py build_i18n` to update the translations.

**Comment by CrafterSvK** [comment]
Sure thanks for that
