### ISSUE TITLE
Opinion

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2455]
Sitizens are upgrading their selves without need to fill their whole needs?
AI is only on tier 2?
You can grow anything everywhere?
Politics in this game isn't polished?
There is more going on. I can make some small changes but I am mainly Java programmer.

**Comment by LinuxDonald** [comment]
Yeah I have seen that problem too but for now I don't know why..

**Comment by CrafterSvK** [comment]
And also they don't use clay pits.

**Comment by LinuxDonald** [comment]
The a.i. Don't support that for now. And don't know to why not. A.i. Code is really big.

**Comment by CrafterSvK** [comment]
I am looking at it right now. Maybe I can update that

**Comment by LinuxDonald** [comment]
That would be very nice :-)

**Comment by CrafterSvK** [comment]
That's strange. There is Clay Pit corectlly implemented even it says that it must be built on clay deposit.

**Comment by janexx** [comment]
Are you sure that clay pit doesn't work in game? I didn't noticed problems with that. Or do you mean stone pit?

**Comment by CrafterSvK** [comment]
I mean clay pit. My AI is ignoring that deposit.

**Comment by LinuxDonald** [comment]
A.i. Should work up to tier 4.

**Comment by CrafterSvK** [comment]
AI works perfectly now. I think only small bug...
