### ISSUE TITLE
Background menu

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2456]
Background is okay but not suitable for anything bigger than 1280x720.

**Comment by janexx** [comment]
So we need a bigger background? What dimension would we need?

**Comment by CrafterSvK** [comment]
You don't need much bigger. 1920x1080 is common and you can scale it up and down for 16:9 displays

**Comment by janexx** [comment]
Does anyone know where the current backgrounds come from? Maybe I can make new ones...

**Comment by CrafterSvK** [comment]
Can you tell me location in the git so I can check them out?

**Comment by janexx** [comment]
https://github.com/unknown-horizons/unknown-horizons/tree/master/content/gui/images/background/mainmenu

**Comment by CrafterSvK** [comment]
They are painting of William Bradford

**Comment by CrafterSvK** [comment]
So I found a picture check it out if you can http://bestcraft.sk/cdn/uh/bg_1.png (That's my temporyry CDN)... I need someone to make scaling code.

**Comment by janexx** [comment]
Nice! Do find other images, too (maybe without ice)? And under which licence are the images?

**Comment by CrafterSvK** [comment]
Creative Commons license.

**Comment by CrafterSvK** [comment]
http://bestcraft.sk/cdn/uh/bg_1.png This one is with ice so It is not relevant
http://bestcraft.sk/cdn/uh/bg_2.png
http://bestcraft.sk/cdn/uh/bg_3.png
http://bestcraft.sk/cdn/uh/bg_4.png
http://bestcraft.sk/cdn/uh/bg_5.png
If they are okay let me know. :) (The script is needed)

**Comment by janexx** [comment]
The 5th one seems a bit pixelated, the others seem good to me. We need the ice image maybe later. There is an ice map planned (maybe someday in 10 years ;) ). 

@LinuxDonald Is the script task maybe something you can do? As I understand it, we need a script to scale the big images above to smaller sizes for different displays (monitor, tablet,...)

**Comment by CrafterSvK** [comment]
Okay. I can replace it no problem.

@LinuxDonald Nothing extra hard. Just pick resolution from options and scale the image so it can fill the whole screen.

**Comment by CrafterSvK** [comment]
5th picture was updated. It is different picture but seems to be nice aswell. This paint pictures are hard to find in high resolutions cause they were digitally taken 12 years ago.

**Comment by CrafterSvK** [comment]
There is another problem. 
![snimka obrazovky z 2016-08-30 15-42-33](https://cloud.githubusercontent.com/assets/8365659/18091367/a95c01de-6ec8-11e6-891d-083c9902d5e8.png)
In this picture you can see that the fade effect at the bottom of the screen is not wide as picture and on 1920x1080 resolution it also floats. Need some fixing there.

**Comment by ChrisOelmueller** [comment]
The "fade" effect is just another image: https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gui/images/background/mainmenu/quotearea.png

Could try tiling that (displaying next to each other multiple times) or increasing its size.

**Comment by CrafterSvK** [comment]
Yeah that would be cool.

**Comment by LinuxDonald** [comment]
Sorry but I think that is an job for @MasterOfJokers.

**Comment by MasterofJOKers** [comment]
![too_much_pressure](https://cloud.githubusercontent.com/assets/697766/18102560/3b943d94-6ef3-11e6-8d91-fdc8975f48c9.jpg)

**Comment by CrafterSvK** [comment]
Don't worry you have time. :)

**Comment by MasterofJOKers** [comment]
Because its simpler that way? Maybe we can update the loaded XML at run-time with the correct size. But is a cropped image better? Even so, what size would that image be?  x720? x1080? Aren't there 4K displays out there now? My laptop has x960 iirc. Scaling at run-time would be better, I guess but would also need additional computing resources.

**Comment by CrafterSvK** [comment]
I made 1920x380ish picture that can be stretched when higher res and cropped when lower res. 4k displays will have a lot of problems because it will be small the ui and stuff.

**Comment by CrafterSvK** [comment]
#2465
