### ISSUE TITLE
Funny quotations cannot be translated

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2462]
I cannot find funny quotations on weblate. It leaves untraslated text when turning them on.

**Comment by ChrisOelmueller** [comment]
Could you give an example of what you expected to work, and what happened instead?

**Comment by CrafterSvK** [comment]
Funny quotations aren't translatable 'cause you can't find them on weblate

**Comment by MasterofJOKers** [comment]
Funny quotes are in the database/an sql file, iirc.

**Comment by CrafterSvK** [comment]
Maybe rewrite them so u can use them with weblate? Please?

**Comment by MasterofJOKers** [comment]
I was hoping for a revelation from @ChrisOelmueller after this additional fact. Or rather something like "yeah, that never worked".

**Comment by CrafterSvK** [comment]
Hopefully he will respond and make something about it.

**Comment by ChrisOelmueller** [comment]
Yeah, that never worked. ;-)

No, seriously, I don't have the time right now to look for my crystal ball and guess 75% of the information needed for me to have UH conversations. If you could prepare a short description of what you tried to do, what you expected to happen and what happened instead, that would be extremely helpful for me.

**Comment by MasterofJOKers** [comment]
@CrafterSvK https://github.com/xseanl/unknown-horizons/blob/master/horizons/gui/modules/loadingscreen.py#L38
They are not supposed to be translated. Seems to be a design decision.

And the fact I added, was wrong, sorry.

**Comment by CrafterSvK** [comment]
Okay. Your game your decision. :)

**Comment by CrafterSvK** [comment]
Funny quotes are not supposed to be translated...
