### ISSUE TITLE
Background of menu and loading screen

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2464]
Picture for main menu and loading screen

http://bestcraft.sk/cdn/uh/bg_2.png
http://bestcraft.sk/cdn/uh/bg_3.png
http://bestcraft.sk/cdn/uh/bg_4.png
http://bestcraft.sk/cdn/uh/bg_5.png

WARNING! Hell of a lot of Math
Because of fife engine there were a problem with positioning the loading screen.

There is something we call position_technique which is way better but works only in VBox, HBox and on Container. NOT in it.

First of all (1920x1080)
There is a /content/gui/images/background/mainmenu/loading.png which is 250x137
We need to get center of this picture to right position to its center
250 / 2 = 125 //This will got the center of the image
137 / 2 = 68.5 //This will got the center of the image

Center of the screen is (1920/2) x (1080/2) = 960x540
960 - 125 = 835 //This will make a position to center
540 - 68.5 = 471 //Hups decimal places doesn't work. So we need to remove it :( 

Now we have /content/gui/images/background/mainmenu/loading.png icon centered.

Then there is /content/gui/images/background/mainmenu/quotearea.png this image which I have updated with higher resolution
http://bestcraft.sk/cdn/uh/quotearea.png

I didn't change the height only width
so the height is 207px
To get to the bottom screen we use

1080 - 207 = 873 //position 0,873

Now we have /content/gui/images/background/mainmenu/quotearea.png image at the bottom.

Then there is loading label which says "Loading" :)
We need to position it same as the loding.png icon + 10ish px width

835 + 25 = 860
471 same as picture loading.png

860,471 is good position

Now we have a problem, but still quite easy
qotl_type_label is "quote"
This needs to be bottom:center

960 - 50 = 910 //This is width
Now, because of quote area is 207px height
1080 - 100 = 980 //We need to have it inside of the quotearea but not in center
qotl_type_label is 910,980

qotl_label same as qotl_type_label but little more inside
960 - 50 = 910
1080 - 80 = 1000

qotl_label is 910,1000

version_label is at bottom:right AND IT IS NOT USED -_-

1920 - 150 = 1870
1080 - 100 = 980

version_label is 1670,980

loading_stage is at bottom:left
150 //width will be fixed value I think
1080 - 80 = 1000 //Everything will be alligned

loading_progress is at center:center
It will be right under loading_label
860
471 + 79 = 550 //Under the label

Easy and now abstract

Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO Moo MoO 

Just kidding

res_width = res.getWidth(options);
res_height = res.getHeight(options);

center_width = res_width / 2;
center_height = res_height / 2;

loading_pos_width = center_width - 125;
loading_pos_height = center_height - 68;

quotearea_pos_width = 0;
quotearea_pos_height = res_height - 207;

loading_label_pos_width = loading_pos_width + 25;
loading_label_pos_height = loading_pos_height;

qotl_type_label_pos_width = center_width - 50;
qotl_type_label_pos_height = res_height - 100; //center of quote area

qotl_label_pos_width = qoutl_type_label_pos_width;
qotl_label_pos_height = res_width - 80;

version_label_pos_width = res_width - 150; //not used
version_label_pos_height = res_height - 100; //not used

loading_stage_pos_width = 150;
loading_stage_pos_height = res_height - 80;

loading_progress_pos_width = loading_label_pos_width;
loading_progress_pos_height = loading_label_pos_height + 79;

It took 2.5ish hours to make this freaking thing.

**Comment by CrafterSvK** [comment]
Also here is XML file which works with 1080p monitor so test it out...

`<?xml version="1.0"?>
<Container size="1920,1080" name="loadingscreen">
	<Icon image="content/gui/images/background/mainmenu/loading.png" position="835,471" />
	<Icon image="content/gui/images/background/mainmenu/quotearea.png" position="0,873" />

	<Label name="loading_label" position="860,471" text="Loading…" font="large_load"
		max_size="250,50" min_size="150,50" />
	<Label name="qotl_type_label" position="910,980" font="headline_light" />
	<Label name="qotl_label" position="910,1000" font="default_load"
		max_size="315,75" min_size="315,75" wrap_text="1" />
	<Label name="version_label" position="1870,980" font="headline_light" />

	<Label name="loading_stage" position="150,1000" font="default_load" />
	<ProgressBar name="loading_progress" position="860,550" max_size="200,12" />
</Container>
`

**Comment by jorgesumle** [comment]
I have a 1080p, I can test it. Where is the code?

**Comment by CrafterSvK** [comment]
/content/gui/xml/mainmenu/loadingscreen.xml
But you need pictures above to do it. You wont see it anyways.

**Comment by jorgesumle** [comment]
OK, it seems to work fine for 1920x1080.
![captura de pantalla de 2016-08-31 17 31 59](https://cloud.githubusercontent.com/assets/14212780/18135185/4c4d2ec6-6fa1-11e6-9207-836fbd9b7d7d.png)
![captura de pantalla de 2016-08-31 17 32 28](https://cloud.githubusercontent.com/assets/14212780/18135215/6b90e58e-6fa1-11e6-8037-f0cbf3460562.png)
I have found though that the "Change background" text is very difficult to read. But that can be easily fixed with a text background:
![captura de pantalla de 2016-08-31 17 41 08](https://cloud.githubusercontent.com/assets/14212780/18135413/2016488c-6fa2-11e6-8937-a602fd1217ad.png)

**Comment by CrafterSvK** [comment]
Well thanks for testing. Now we need to automate it so it will pick right resolution on load :)

**Comment by CrafterSvK** [comment]
#2465

**Comment by janexx** [comment]
I have tested it, too. BG_5 has a bad image quality (pixelig). The other images are very good. And on my display the quote area is not large enough:

![neu_menu_footer_toosmall](https://cloud.githubusercontent.com/assets/6216898/18144044/0f35786c-6fc5-11e6-9245-336382f5eedf.png)
My screen resolution is 1680x1050.

**Comment by MasterofJOKers** [comment]
What resolution does your display have?

**Comment by CrafterSvK** [comment]
I have custom version. See #2465

**Comment by janexx** [comment]
1680x1050

**Comment by CrafterSvK** [comment]
You need to update /horizons/gui/modules/loadingscreen.py
with these http://bestcraft.sk/cdn/uh/loadingscreen.py

**Comment by janexx** [comment]
Ah sorry I wasn't in the branch GUI-Graphics-update. It works!

**Comment by CrafterSvK** [comment]
:) I will replace that pixelate picture I can't find any without ice with Creative Commons and no watermarks.

**Comment by janexx** [comment]
Maybe we could later add some graphics as background for the texts instead of using text-background? I mean it's ok, but not very beautiful and fancy. :)

**Comment by CrafterSvK** [comment]
Yeah that would be great :)

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/pull/2465

Fixed. Thx @CrafterSvK fot that :)
