### ISSUE TITLE
"Change background" text in main menu is almost impossible to read

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2468]
![captura de pantalla de 2016-09-01 00 50 10](https://cloud.githubusercontent.com/assets/14212780/18149042/0eb735ce-6fde-11e6-9fba-fd42b9e6c19f.png)

**Comment by CrafterSvK** [comment]
I know about this thing. @janexx Can you please change changebackground image with semi-transparent background please

**Comment by janexx** [comment]
How can this be changed? It is a code thing, not a graphic one, isn't it? Or shoud I create a background graphic for this text?

**Comment by ChrisOelmueller** [comment]
A few ideas: The button color could be changed, you could introduce some kind of opacity to make it stand out more, the button could get a background image assigned (if that is possible).

**Comment by CrafterSvK** [comment]
I've tried with @MasterofJOKers some kind of label magic. Gotta finish this today.

**Comment by CrafterSvK** [comment]
#2467

**Comment by CrafterSvK** [comment]
Latest merge solve the issue :)

**Comment by MasterofJOKers** [comment]
e3536a13
