### ISSUE TITLE
Please do a new release of UH and fife to fix crash on startup with Swig >= 3

### ISSUE THREAD

**Issue by apoleon** [unknown-horizons/unknown-horizons#2471]
Hello,

Unknown Horizons has become unplayable on Debian distributions due to the issue that was already reported at

https://github.com/unknown-horizons/unknown-horizons/issues/2295

Related Debian bug report is at

https://bugs.debian.org/797998

Debian ships the latest tagged releases of UH and fife and Swig 3 is now the default. Using Swig 2 is not an option. Could you do a new release for UH and fife that would address this issue please?

**Comment by CrafterSvK** [comment]
Do you mean 2014.1 version?

**Comment by apoleon** [comment]
On 03.09.2016 15:36, Jakub Janek wrote:
> Do you mean 2014.1 version?

Yes, 2014.1 is the latest tagged release which is also available in Debian.

**Comment by CrafterSvK** [comment]
Unknown Horizons team didn't release stable version of this game for a long time. They are doing it in their free time. As I said 2016.1 will be released this year.

**Comment by LinuxDonald** [comment]
Hello @apoleon the next stable release is planned for december. The new version of fife and fifechan will be release maybe before or togehther with UH.

**Comment by LinuxDonald** [comment]
See #2963
