### ISSUE TITLE
The Journal doesn't display some sentences well

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2474]
Sometimes, there are words that end on the next page of the Journal.
![error2](https://cloud.githubusercontent.com/assets/14212780/18227820/72e6a674-7231-11e6-9610-343b7ec14742.png)
![error3](https://cloud.githubusercontent.com/assets/14212780/18227823/7cdf07fc-7231-11e6-906a-9d1203ae1b8b.png)
We have also come across a missing end of sentence. But there may be more of these. I don't know.
![error1](https://cloud.githubusercontent.com/assets/14212780/18227817/60df62cc-7231-11e6-9a67-a8092fcc6a5e.png)

**Comment by jorgesumle** [comment]
Changed line 220 from horizons/gui/widgets/logbook.py
```
return Label(text=unicode(text), wrap_text=True,
				             min_size=(325, 0), max_size=(325, 335),
				             font=font)
```
\-				             min_size=(335, 0), max_size=(335, 508),
\+                                          min_size=(325, 0), max_size=(325, 335),

![captura de pantalla de 2016-09-04 02 48 56](https://cloud.githubusercontent.com/assets/14212780/18228338/85b465de-724a-11e6-8aa7-b6033f3141e8.png)
![captura de pantalla de 2016-09-04 02 50 30](https://cloud.githubusercontent.com/assets/14212780/18228333/68128fec-724a-11e6-9a2b-36c5ae4644ed.png)

That fixes the problem (I don't know how it works, but it fixes the problem). Someone helps me understand what I've done, the FIFE reference sucks.

With the solution comes a little possible problem. I've tested the entire tutorial and there is enough space for everything, but there are a languages that require more words to express things than English. With Spanish only one page from the entire tutorial has a little problem after the fix. 
![captura de pantalla de 2016-09-04 03 28 16](https://cloud.githubusercontent.com/assets/14212780/18228508/95fa500a-7251-11e6-971f-8c8a91b7e38a.png)

But there may be other languages affected. Please test your languages and tell me if there is a similar problem, I don't know if I should open an issue for this (if there are more and worst examples, we should), because I only found one page and can be fixed by using shorter words . Also, test the Unknown Horizons scenario, I can only test the first two pages because I haven't finished it :( (they work well in English and Spanish).

**Comment by CrafterSvK** [comment]
You changed maximal width of label which makes it smaller and i can fit onto page. min_size and max_size is little weird in fife.

**Comment by LinuxDonald** [comment]
+ min_size=(325, 0), max_size=(325, 335),
Bigger Valves not work?
For exmaple: min_size=(335, 0), max_size=(335, 400),

**Comment by jorgesumle** [comment]
>  Bigger Valves not work? For exmaple: min_size=(335, 0), max_size=(335, 400)

min_size=(325, 0), max_size=(325, 400) work too. But min_size=(335, 0), max_size=(335, 508) not.

**Comment by LinuxDonald** [comment]
does with 400 it fix the language problem?

**Comment by jorgesumle** [comment]
> does with 400 it fix the language problem?

It looks the same. I don't know how it works, from what I've read it is the second parameter from max_size is the height of the Label, but I'm not really sure. Also, I don't know if every page is an entire Label. I'm not sure and I'm not familiar with fife; this week I don't have enough time to solve this problem. @CrafterSvK, maybe you can solve this issue.

**Comment by jorgesumle** [comment]
The bug is now worse, but the file horizons/gui/widgets/logbook.py hasn't changed since the issue was reported. Only @squiddy changed the order of the imports and there is nothing weird in that change, so maybe the problem is not in horizons/gui/widgets/logbook.py
![captura de pantalla de 2016-10-16 03 05 36](https://cloud.githubusercontent.com/assets/14212780/19414436/9d415f30-934d-11e6-9d3d-44299a712274.png)
![captura de pantalla de 2016-10-16 03 01 20](https://cloud.githubusercontent.com/assets/14212780/19414423/da6b8684-934c-11e6-97e5-c602517cbd6e.png)

**Comment by LinuxDonald** [comment]
I will take on look today on it maybe I can fix it.

**Comment by squiddy** [comment]
I wonder if it's feasible to improve the layouting algorithm and have the content actually flow onto the second page, you know, like in a book.

If I remember correctly right now we're specifying what should be displayed on each page, we could instead specify the content, and the GUI should distribute the content across X pages of the logbook. Languages with longer translations (I'm looking at you, french) would simply use more pages of the logbook.

**Comment by LinuxDonald** [comment]
When we remove the scrollbars and add for example an third page what when the third page have only 3 sentence or some icons. Because there is no more from the text.

**Comment by squiddy** [comment]
Honestly, that's how it is then. I'm sure the current entries were written to fit into pages, which in the flow model wouldn't be necesssary anymore.

The issue I see here is that we present the user with an interface that looks like a book, acts like a book (you can click through pages)... but has scrollbars. Which means that in the worst case, I have two means of navigation: switching pages and scrolling.

I'm not saying we shouldn't have added scrollbars for the time beeing, I just think this could be an idea worth discussing at some later time. Because at some point people will run into these issues, especially with translations.

**Comment by MasterofJOKers** [comment]
I'm all for having a new layouting algorithm, but that is something, that has to be supported by the GUI, as we currently don't know the size of the text in the font of the GUI. Without that knowledge, it seems hard to get the correct size. We already have this problem with tooltips (e.g. #2365).
