### ISSUE TITLE
KeyError: 'produced_resource_5_Point(106, 125)_222'

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2475]
@janexx reported this error to me:
https://gist.github.com/janexx/b20f9cb81727d9c2b58f9c804ae0d537

I found the same crash log here:
https://github.com/unknown-horizons/unknown-horizons/issues/1916

but this should fixed by this:
https://github.com/unknown-horizons/unknown-horizons/pull/1810

**Comment by squiddy** [comment]
Added a gui test to reproduce the problem.

However, I'm starting to wonder if this really is a bug in the icon manager. The traceback from janexx shows, that the **same building** produced the **same resource** more than once in the **same tick**. Should that even be possible?

**Comment by squiddy** [comment]
So, the butchery has 2 productionlines for food (cattle and pigs), so the case I described above can actually happen. So I guess we need to further specialize the key function of the icon manager, to prevent that as well.

I *guess* using the production line ID should help. I don't think the same production line can finish two times in the same tick.

**Comment by squiddy** [comment]
Also, any building with more than one production line producing the same resource (e.g. pastry shop) could be affected.
