### ISSUE TITLE
Diacritics doesn't display in the load game menu

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2476]
Maybe there is a problem with Unicode and Python 2.
![captura de pantalla de 2016-09-06 02 48 30](https://cloud.githubusercontent.com/assets/14212780/18258913/54f71474-73de-11e6-8622-3cc0f5c73d62.png)
##

**Comment by MasterofJOKers** [comment]
Just a quick link to research this later: https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/savegamemanager.py#L123

**Comment by wattsra** [comment]
Since UH now supports only Python3. Can we close this issue?

Also I can't recreate this issue with Python3 as it stands.
