### ISSUE TITLE
Run gui tests on travis CI

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2479]
I think we used to run the GUI tests on the old Jenkins server, however with the switch to Travis CI (85d0cb83d59800df71a619fb65a43ad7a3bf80da) this is no longer the case as far as I can see. Which is sad since we do have a good number of test cases there.

If we wanted to run those on travis, we need to at the very least the following:

- [ ] install X server on Travis (or more likely xvfb)
- [ ] install the fife library (and guichan?) on travis

**Comment by MasterofJOKers** [comment]
Since we are planning to do nightly builds, the second part could be done by using our then-existing repo's packages.

**Comment by MarkusHackspacher** [comment]
The first point, install X server on Travis (or more likely xvfb):
Add the lines in .travis.yml "before_install"
```
before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
```
It work fine in https://travis-ci.org/MarkusHackspacher/pyLottoSimu

**Comment by MasterofJOKers** [comment]
travis-ci only supports trusty, which has libstdc++6 of version 4.8. We need proper fife packages. Then we can use @MarkusHackspacher's work from here: https://github.com/MarkusHackspacher/unknown-horizons/edit/patch-3/.travis.yml

**Comment by MasterofJOKers** [comment]
Done. Using packages manually built for Ubuntu trusty for now. Some tests are failing.
