### ISSUE TITLE
Fix the GUI tests

### ISSUE THREAD

**Issue by MasterofJOKers** [unknown-horizons/unknown-horizons#2480]
The GUI tests are running with travis-ci, but some of them are failing. Someone™ needs to fix the tests.

**Comment by squiddy** [comment]
I'm looking into it right now.

**Comment by squiddy** [comment]
Most tests seem to fail because the map generation code changed in fb256e1436ed1cf1858135e8c345bc4df22f8b5b (verified with git bisect).

Unfortunately, now the dev map with seed 42 contains a mountain at the position where many tests try to found a settlement.

**Comment by squiddy** [comment]
The build is fixed for now (https://travis-ci.org/unknown-horizons/unknown-horizons/builds/161119039).

There are about 4 tests that fail due to bugs (e.g. #2419) or incorrect implementation. The rest is flaky (see #2485).

**Comment by squiddy** [comment]
With the exception of the now deleted trade test, all tests have been stable for the last ~10 builds.
