### ISSUE TITLE
Discuss code style checks

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2482]
As someone that hasn't contributed to this project in years, it's easier for me to run a tool that will yell at me when code doesn't adhere to the style guide.

I guess we used to run the `pep8` tool, because there are some settings in `setup.cfg` related to it. However, c289a5173e744bf8f61adc8758ee7d982971e4c4 added a (seemingly more complete) configuration for pylint.

Unfortunately, running `pylint horizons` spits out thousands (26483 for me) of warnings and errors (whitespace issues, indentation, variable names...). I was going to suggest running code style checks in CI, but at this point it's just not feasible.

I guess we have two options:

1) fix warnings and/or adjust code style configuration
2) remove .pylintrc

Personally I'd vote for option 1.

**Comment by jorgesumle** [comment]
We could start with trailing whitespaces:
I've run this: `find . -type f -name '*.py' -exec sed --in-place 's/ \+$//' {} \+`.
This only works for Python .py files. Change the extension to make it work for other formats. I'm not sure if that's necessary.

**Comment by jakoch** [comment]
What about adding it to `travis.yml`:

```
install:
    # Install pylint
    - sudo apt-get install pylint
script:
    # Run pylint
    - pylint --errors-only --rcfile=".pylintrc" horizons/
```

You could set it to report only - but don't let the build fail. 
That should produce a log with things to fix and you can work through it step-by-step.

**Comment by MarkusHackspacher** [comment]
In my fork, I use in travis.yml this:
`  - python pylint-recursive.py`
The output are https://travis-ci.org/MarkusHackspacher/unknown-horizons/builds/160466819
That was also the reason, that I ask for delete the file `development/networkclient.py ` see #2487

**Comment by squiddy** [comment]
We already have a `.pylintrc` in the master branch, so I'm not sure what you're actually suggesting here.

Can you explain what `pylint-recursive.py` is for? If I run `pytest` myself, it will already recurse into subdirectories.

The main issue to me here is that with the current configuration, pylint attempts to do a lot of static analyzing, which fails with the codebase. For example, we probably should configure pylint to ignore the Enum class (there's lots of cases where pylint complains).

Perhaps we should drop the static analyzing for now and concentrate on consistent code style - which still is a lot to do.

**Comment by squiddy** [comment]
@MarkusHackspacher 

> We already have a .pylintrc in the master branch, so I'm not sure what you're actually suggesting here.

> Can you explain what pylint-recursive.py is for? If I run pytest myself, it will already recurse into subdirectories.

**Comment by MarkusHackspacher** [comment]
I saw the pylint-recursive.py in some other github projekts and tested it in my fork. Evaluate the style of each file. Best code style are 10 points.
But now I think this test need only lots of time and the assessment about the files is in the moment not important. As no major changes are made to the source text, than maybe could somebody look the rate goes down or up after the change.
In the moment I make in my fork not the pylint-recursive.py check. But maybe later.
This are my arguments to let the file .pylintrc in the project.

**Comment by squiddy** [comment]
I'm probably going to remove the pylint config in the near future.

The config is huge, the warnings/errors are many and the tool tries to do a lot at once. For type checking we'll be implementing type hints for mypy, code style issues can be found with pep8 & co. If we later need code complexity (McCabe..) checks, we can readd pylint.
