### ISSUE TITLE
Debian dependencies discrepancy on website

### ISSUE THREAD

**Issue by Pab0** [unknown-horizons/unknown-horizons#2489]
On the [Installing from sources in Linux](http://www.unknown-horizons.org/download/sources/s-linux/) page, the aptURL and the apt-get approaches for Debian are slightly different. Differences are:

- aptURL misses libtiny-xml-dev
- aptURL uses python2.6, apt-get python2.7
- apt-get lists swig twice

Also, when opening the aptURL link with aptURL on Ubuntu, it says:
`Url string 'apt:build-essential,scons ...' too long`
Opening the link with the Ubuntu Software Center seems to work, though.

**Comment by LinuxDonald** [comment]
Thx for te report i fixed it. With the to long error i dont know how to fix that. Maybe upstream error?

**Comment by Pab0** [comment]
Yes, it's a ~~bug~~ feature of aptURL, likely in response to a [bug](https://bugs.launchpad.net/ubuntu/+source/apturl/+bug/783594) which crashes the desktop environment with too long URLs. 

The maximum allowed URL length seems to be [hardcoded](http://bazaar.launchpad.net/~ubuntu-core-dev/apturl/ubuntu/revision/108/AptUrl/Parser.py) to 255 characters. Seeing as the dependencies are already at 300+ characters, there's nothing we can do as long as aptURL doesn't change its behavior.
As a sidenote, aptURL doesn't seem to like spaces, so the ones before the two last packages should be removed (on the off-chance that aptURL does change its behavior in the future).

Of course, the aptURL link doesn't have to be deleted, since
a) the 255 char limit seems to only be on the Ubuntu version of the package, and
b) the Ubuntu Software Center (and maybe other alternatives) seems to work fine with the URL.
