### ISSUE TITLE
Game crashing on Raspberry Pi 3

### ISSUE THREAD

**Issue by cmfrydos** [unknown-horizons/unknown-horizons#2492]
I have installed fife and uh from source on a raspberry pi 3.
It ran very slow, I couldn't even move the mouse pointer without extreme stuttering
So I decided to activate an in-dev OpenGL driver, and the game ran perfectly until I tried to build something, which crashed me to desktop.
After a second try I was able to build my contor but It crashed when I clicked on the lumberjack icon to build it. To provide u with some debug information I tried to start it another time in debug mode, but this time it crashed me out of the x11 server to console, I guess, due to an openGL error, and it killed even my internet connection.

**Comment by squiddy** [comment]
Hi there. First of all, I applaud your effort to get this running on RPi 3, did not expect that one. :+1: 

When starting UH in debug mode, it should write to stderr and a log file in `~/.unknown-horizons/logs/`. Could you check for logs there and, if possible, attach them to the issue?

**Comment by squiddy** [comment]
Closing this since we have no information to act on. If you can provide, for example, the debug logs, feel free to post them here and reopen. :)
