### ISSUE TITLE
Starting scenario from commandline is broken

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2507]
I would expect that this loads the tutorial scenario in with the correct language, instead it doesn't find anything.

```
$ python run_uh.py --start-scenario=tutorial
Error: Cannot find savegame or map 'tutorial'.
```

The [`find_matching_map`](https://github.com/unknown-horizons/unknown-horizons/blob/8ab63d15137625fd2079df4a8643dc3d1ca8f616/horizons/main.py#L480) function is the issue, or rather, its handling of the `savegames` parameter, which structure probably changed some time.

**Comment by AndyMender** [comment]
The output of zip(*savegames) is completely mangled. Will fix this if I can :).

**Comment by AndyMender** [comment]
Function rebuilt, supplied with extra safety checks and confirmed to work with the provided example:
`python3 run_uh.py --start-scenario=tutorial`

**Comment by LinuxDonald** [comment]
Maybe @squiddy could review the pr?

**Comment by squiddy** [comment]
Yes, please wait. There is no point in opening a pr if you're just going to merge it anyway.

**Comment by AndyMender** [comment]
Fixed here: https://github.com/unknown-horizons/unknown-horizons/pull/2651
Will close in favour of a future issue listing unittests that we may still require.
