### ISSUE TITLE
CI build fails when committer has no repo set up at coveralls

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2511]
The offending line: https://github.com/unknown-horizons/unknown-horizons/blob/65dfcdd/.travis.yml#L29

One needs to link a repository in coveralls (which requires logging first), in order to submit coverage stats. Right now, check builds for PRs from most submitters will fail because of this.

There is probably not much use in submitting stuff to coveralls other than for branches in the `unknown-horizons/unknown-horizons` repository. Find a way to either ignore that error or, possibly better, run that command only for the main repo.

**Comment by ChrisOelmueller** [comment]
Possibly check for inspiration: http://stackoverflow.com/questions/39501417/how-can-i-connect-coveralls-and-travis-in-github

**Comment by squiddy** [comment]
@ChrisOelmueller Thanks for the hint.
