### ISSUE TITLE
Remove __builtin__ modification for gettext

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2516]
Right now, we're doing a single `gettext.install('de', ...)` once in the code, and the rest of the modules magically have access to `_`, `_N` and other things.

This has some issues:
- danger of local shadowing by using `_` as "unused argument", e.g. when unpacking
- need to configure linters to ignore "not defined" errors when looking at `_`
- mypy doesn't understand it, because builtins aren't really supposed to be modified #2513

My suggestion would be:
- Expose `_` etc. on `horizons.i18n` and import it explicitly, like this:

``` python
from horizons.i18n import ugettext as _

_('Foobar')
```

We already do that for lazy translations, e.g. `from horizons.i18n import _lazy`.

The advantage when using `install` is, that all code continues to work after changing a language, and `_` always points to the active translations's `gettext`. I know the Django project has solved that somehow, you just `from django.utils.translation import gettext as _` and it works.

---

As a first step, I'd be fine with keeping the install, but adding the imports mentioned above everywhere we use `_`, `_N` etc.
- [x] Expose `_` & co. in `horizons.i18n`, so that `from horizons.i18n import ugettext as _, ugettext_lazy as _lazy` works.
- [x] Replaces uses of _ in files with imports

**Comment by MasterofJOKers** [comment]
I was wondering, how that worked. :+1: for changing it. "explicit is better than implicit"

**Comment by Niektory** [comment]
I seems `run_uh.py` was left out and needs `from horizons.i18n import gettext as _` too. Not sure where exactly to put it considering this warning: https://github.com/unknown-horizons/unknown-horizons/blob/master/run_uh.py#L49
