### ISSUE TITLE
One or two whitespaces before inline comment?

### ISSUE THREAD

**Issue by MarkusHackspacher** [unknown-horizons/unknown-horizons#2519]
This point we discus [2014](https://github.com/unknown-horizons/unknown-horizons/pull/2290#issuecomment-58741299) and today [2016](https://github.com/unknown-horizons/unknown-horizons/pull/2514#discussion_r83527304) both time with **only one spaces before inline comment** from two long term maintainers.

But I think:
Python's official style guide, PEP 8, is very clear about this issue:

> Inline comments should be separated by at least two spaces from the statement.
> They should start with a # and a single space.
- Other python projects like django use two or more spaces before inline comment. I that a look to flask and kivy but I see there no inline comments.
- Automate formatters can work: https://github.com/google/yapf
- Uniform requirements such as PEP8 facilitate co-operation

On the other hand I understand the opinions for one spaces before inline comment, too.
In this case, please make a change in the UH [coding-style](https://github.com/unknown-horizons/unknown-horizons/blob/master/CONTRIBUTING.md#coding-style) and add
- **only one** spaces before inline comment
##

**Comment by jorgesumle** [comment]
I prefer two, as it is more readable and also compliant with PEP8.
