### ISSUE TITLE
Text is cut off in the gui

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2535]
~~Why there is an black icon? before the Free Trader in the gui?~~

![2016-10-25 17-33-45 638768](https://cloud.githubusercontent.com/assets/1757651/19755183/349b61d6-9c14-11e6-9fad-2c95d908f9b8.png)
##

**Comment by squiddy** [comment]
It's the player emblem, which in UH apparently is just a rectangle with the player's color. So certainly not a bug.

The screenshot shows other issues though: the gold icon is cut off (might be another case where we need to activate scaling) and the text below the resource selection is overflowing.

**Comment by LinuxDonald** [comment]
In the gui the text is a little bit out of gui to see: will buy tools for 21 gold whenever...

**Comment by squiddy** [comment]
@LinuxDonald If you're fine with the player emblem thing, can you simple rename the issue, because it's not about the black thing anymore?

**Comment by LinuxDonald** [comment]
For the moment I fine with it. I will create an extra ticket for it and rename this here one.

**Comment by CrafterSvK** [comment]
Probably fixed see #2586..

**Comment by LinuxDonald** [comment]
Fixed with: #2586
