### ISSUE TITLE
Zooming the view continues when using mousewheel on GUI elements

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2538]
**Steps to reproduce**
1. Move mouse over GUI element
2. Use mousewheel

**What I expected**

The world view shouldn't zoom since my mouse is over the GUI.

**What happened**

The world view zoomed in and out as I used the mouse wheel. This is especially confusing when I'm focusing a scrollarea in the GUI, since now both the scrollarea and the world view change.

**Demo**

https://youtu.be/2OVtIh2ZHrU

**Comment by LinuxDonald** [comment]
I have this error to when I in the gui and what use the mouse scroll for scrolls in the gui but at same time it is zooming.

**Comment by helios2000** [comment]
Should also be fixed with https://github.com/fifengine/fifengine/commit/dad07deb991fa366480948bf64545ef81fafbbf4

**Comment by LinuxDonald** [comment]
Issue is fixed. Thx @helios2000
