### ISSUE TITLE
Playtest multiplayer and decide how to proceed with MP

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2540]
Before the new release, we should test the multiplayer, confirm existing bugs / usability issues and. find new bugs and issues. Then try to estimate whether we can fix that in time, or if we should disable multiplayer alltogether.

Disabling it may not be a popular choice, but a broken feature is just annoying.

Perhaps there are other solutions. Like disabling MP, but focusing on pushing nightly builds and thereby getting newer releases in the hands of players.

Issues related to multiplayer: https://github.com/unknown-horizons/unknown-horizons/issues?q=is%3Aopen+is%3Aissue+label%3AA-mp

**Comment by squiddy** [comment]
@LinuxDonald So if the current (unknown) state of the MP is no blocker, do we still care about its quality prior to the release?

**Comment by LinuxDonald** [comment]
I will disable it. Its better i think.

**Comment by LinuxDonald** [comment]
@squiddy how i can disable it? ...

**Comment by squiddy** [comment]
I suppose this can be closed then.

**Comment by MasterofJOKers** [comment]
Right. @LinuxDonald decided, that we would rather have feedback from users, what exactly is broken in MP, than disabling it (and never enabling it because we cannot possibly play enough multiplayer to get into every corner case).
