### ISSUE TITLE
Don't place tress on sand tiles

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2542]
I think it would be better if we wouldn't place trees on sand tiles, it looks a bit odd. Once we've added climate zones, we can re-enable this for desert zones with palm trees.

![2016-10-30 09-20-02 905539](https://cloud.githubusercontent.com/assets/50333/19835298/276d5116-9e82-11e6-81c7-08a1c440a215.png)

Game version: 36c39724b38798a5da8a54d14035750fcb67bc33
Map: development
##

**Comment by LinuxDonald** [comment]
Yes we should disable it. On climate branch u think we will find an way for it.
