### ISSUE TITLE
Fix savegame upgrades or set SAVEGAME_LEAST_UPGRADABLE_REVISION

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2548]
Savegame upgrades are broken (no further information is available).

We should either repair it, or deny upgrade of savegames from 2014 (`VERSION.SAVEGAME_LEAST_UPGRADABLE_REVISION`).

**Comment by LinuxDonald** [comment]
I will look tomorrow If I could found the commit what broke it.

**Comment by LinuxDonald** [comment]
i found what commit breaks the savegame updater.

**Comment by squiddy** [comment]
> It breaks the info in the savegame I think bla id produces something other id
> When I remember correctly all buildings have it own ids and own production line ids but with my change there is now another productline id
> The problem was that I had forgotten how to find out the old id and the new one.
> The code for that we already have in savegame upgrade for another id

-- LinuxDonald (IRC)

I checkout the commit (e2adf80cd62ce) before the one that supposedly breaks the savegames, build a brewery and loaded it into master (7b9aed499a809), it seems to work fine?!

[2548.sqlite.zip](https://github.com/unknown-horizons/unknown-horizons/files/569866/2548.sqlite.zip)

**Comment by LinuxDonald** [comment]
Yeah i have tested it now too with your savegame. and it works then i think it can be closed here.
