### ISSUE TITLE
No Terminology

### ISSUE THREAD

**Issue by Z-Fikar** [unknown-horizons/unknown-horizons#2551]
I made this issue because I found bugs in one of **Terminology** translation files and when I want to fix it, I couldn't **Terminology** in the [Weblate](https://hosted.weblate.org/projects/uh/).

So, I recently submit a Pull Request to fix it #2550 instead using Weblate.

The solution here is either you add **Terminology** in the Weblate so I can fix it there or just merge my PR.
<br>

**Comment by squiddy** [comment]
I created #2553 to figure out how to deal with this in the future.

**Comment by Z-Fikar** [comment]
👍
