### ISSUE TITLE
The games closes abrupted (after 10 seconds). 

### ISSUE THREAD

**Issue by Cesar1990** [unknown-horizons/unknown-horizons#2582]
Because this i can't play. How can i solve it? Help please.

**Comment by LinuxDonald** [comment]
What version of unknown-horizons and fife do you use?

**Comment by Cesar1990** [comment]
Hi! Fife version  "0.3.5-1build" and game is "2014.1+ds1-2". My OS is Mint Sarah (18) XFCE.   


Thanks!!!

**Comment by LinuxDonald** [comment]
Sorry this version is very old and yes the last stable from us. But we will make an new release this month or in the next one. Then UH should work again for you.
We are working on new release and have an open ticket for it: https://github.com/unknown-horizons/unknown-horizons/issues/2396

I close that here.
