### ISSUE TITLE
Update handling of FIFE exceptions

### ISSUE THREAD

**Issue by Niektory** [unknown-horizons/unknown-horizons#2583]
A recent FIFE patch (https://github.com/fifengine/fifengine/pull/945) changed the types of exceptions thrown to Python clients. Previously they were all converted to `RuntimeError`, while now they have custom types such as `fife.NotFound`. Because of this they are no longer caught properly by Unknown Horizons.

I see two ways to fix it:
- Update all exception handlers to the new types. This is difficult because it would require determining the correct type in each case which is not always clear from the code.
- Monkey-patch `fife.Exception` to inherit from `RuntimeError`. This is a bit hacky but it would allow old handlers to work unchanged (or be updated selectively), while new code could use the new exception types.

I'd go with the second option.

One other thing: Should it be implemented in a way that it works with both old and new FIFE versions, or is it not necessary and only new versions need to be supported?

**Comment by LinuxDonald** [comment]
Only new version because next uh release will need current fife release.

**Comment by LinuxDonald** [comment]
I like the second option. But i think when we hack/workaround this bug we should let open this ticket or open new one to remove (for lone time turn) the hack fix.
