### ISSUE TITLE
Scrolling in settings while in game scrolls the game too

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2585]
Changing settings while in game and scrolling through menu initiate scrolling in game too. Which looks kind of bad.

**Comment by LinuxDonald** [comment]
That's an know bug. I think we have already an bug report for it?

**Comment by squiddy** [comment]
Duplicate of #2538 (Zooming the view continues when using mousewheel on GUI elements)
