### ISSUE TITLE
Weblate doesn't include all strings

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2587]
Weblate doesn't include this string. So it cannot be translated.
![screenshot_2016-12-25_17-36-26](https://cloud.githubusercontent.com/assets/8365659/21472067/56f5d024-cac0-11e6-938f-757b662f8d7b.png)

**Comment by LinuxDonald** [comment]
Maybe it's not translated?

**Comment by CrafterSvK** [comment]
It is not translatable. Can't find any string with that name on weblate but it is included in the code.

**Comment by LinuxDonald** [comment]
Okay I will take an look on it tonight.

**Comment by LinuxDonald** [comment]
fixed with: https://github.com/unknown-horizons/unknown-horizons/commit/0b03ebeb26ecbf85e3f02c92b41a8bd73fc257ac
