### ISSUE TITLE
Website links to outdated ebuild for gentoo

### ISSUE THREAD

**Issue by oz123** [unknown-horizons/unknown-horizons#2588]
The ebuild linked here http://www.unknown-horizons.org/download/linux/ for gentoo
is useless. It has not been maintained in over 5 years, and  it causes more headache then helps.

Please remove it from the listing ...

**Comment by LinuxDonald** [comment]
Fixed. I removed complete the linux download page and linked it now to wiki. There will be in the future an more up-to-date Page of Downloads.
