### ISSUE TITLE
Remove/repair bountysource integration

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2599]
Perhaps it's just me, but for the last couple months the bounty source link doesn't show up correctly at the bottom of issues.

**Screenshot**
![2017-01-14 11_04_21-modify run_uh bat issue 2598 unknown-horizons_unknown-horizons](https://cloud.githubusercontent.com/assets/50333/21954130/3dffc5fa-da49-11e6-8d3e-f24045361401.png)

Is this a configuration problem? Can we fix it? I couldn't find anything in the administration panel (neither under webhooks or integrations). Is it actually useful? Could we just remove it?

From what I could see, the issue seems to be that the code is wrapped in `<bountysource-plugin>` tags, which breaks the markup inside.

**Comment by MasterofJOKers** [comment]
IIRC @LinuxDonald already tried to remove it. He also said, we need to contact bountysource to get removed properly and cannot do it ourselves. Did you also look at "Authorized Applications"?

**Comment by LinuxDonald** [comment]
Yes I already removed it from my account and uh. I will write today an mail to bounty source.

**Comment by LinuxDonald** [comment]
Mail to bountysource is out.

**Comment by jorgesumle** [comment]
Then we should also remove "But you can add a bounty if you want via BountySource." from https://github.com/unknown-horizons/unknown-horizons/wiki/Donation-History wiki page or change the donation method?

**Comment by LinuxDonald** [comment]
Done

**Comment by squiddy** [comment]
I've set the "Third-party application access policy" (https://github.com/organizations/unknown-horizons/settings/oauth_application_policy)  to restricted, which changes "Approved applications by organization members can access all data in this organization." to  "Only approved applications can access data in this organization.".

Hopefully this should do it. I couldn't find any trace of bountysource in the organization or project's setting, so I assume one of the members has it activated.

This may not be enough though:

> If an organization disables third-party application restrictions, and later re-enables them, previously approved applications will automatically be granted access to the organization's resources.

https://help.github.com/articles/about-third-party-application-restrictions/#re-enabling-access-restrictions

**Comment by squiddy** [comment]
New issues don't get the bounty source code added afterwards, so the settings seems to have helped.

However, since that should affect all integrations we need to check if everything is still working:

We late
Travis CI
Coveralls

I'm probably missing some here.

**Comment by MasterofJOKers** [comment]
We could enable it again and kick users out of the organization instead. One by one. Someone seems to have it enabled ...

**Comment by squiddy** [comment]
If possible, the application access policy should stay restricted, as it is now. Approving applications for UH should be done on the organization level, so if e.g. Travis is broken now, we should approve it for the organization instead (if possible).

**Comment by squiddy** [comment]
Looks like bountysource isn't able to mess up new tickets anymore.

Authorized applications can be seen here (by admins I suppose): https://github.com/organizations/unknown-horizons/settings/oauth_application_policy

As of now, that is: travis, quantified code and coveralls
