### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by jorgesumle** [unknown-horizons/unknown-horizons#2600]
Change "© The Unknown Horizons Developers 2016" to "© The Unknown Horizons Developers 2017".

Update [Windows downloads page](http://www.unknown-horizons.org/download/windows/):
change "Milestone 2014.1 is the latest official release of Unknown Horizons. Click to download it:" to "Milestone 2017.1 is the latest official release of Unknown Horizons. Click to download it:"

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41034710-update-website?utm_campaign=plugin&utm_content=tracker%2F287396&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F287396&utm_medium=issues&utm_source=github).

**Comment by LinuxDonald** [comment]
fixed.
