### ISSUE TITLE
Add media/screenshots of the new release on the website

### ISSUE THREAD

**Issue by janexx** [unknown-horizons/unknown-horizons#2603]
I would like to see some new screenshots here:
http://www.unknown-horizons.org/media/screenshot-gallery/
:-)

**Comment by LinuxDonald** [comment]
I will do this on the next days :)

**Comment by MasterofJOKers** [comment]
There was someone on IRC asking about it, because they want to write an article about the new release. So please hurry :)

**Comment by LinuxDonald** [comment]
http://www.unknown-horizons.org/index.php?mact=Album,m037b7,default,1&m037b7albumid=36&m037b7returnid=53&page=53

Sorry not all buliding are on it. But the freeze bug is really not fun anymore. It will get longer and longer...
