### ISSUE TITLE
Game hangs on exit

### ISSUE THREAD

**Issue by bentley** [unknown-horizons/unknown-horizons#2604]
When I select the ‘quit’ menu option in unknown-horizons, sometimes the game freezes and I have to kill it manually.

Unfortunately I haven’t noticed any pattern to when it hangs or succeeds.

I’m testing on OpenBSD 6.0, with unknown-horizons-2017.1, fifechan-0.1.3, and fifengine-0.4.0.

**Comment by LinuxDonald** [comment]
This is will be fixed in fife 0.4.1 fifechan 0.1.4 UH 2017.2
