### ISSUE TITLE
Update enet to version 1.3.13.2

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2609]
Our last enet version is 1.3.3 https://github.com/unknown-horizons/unknown-horizons/commit/e011d0fed373f521aa44e5c6f4de61cd85759bce

Newest version is: pyenet 1.3.13.2

https://pypi.python.org/pypi/pyenet

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/542fa47ad257d2e4053ba728d88f041611070d7a

**Comment by squiddy** [comment]
Weird, it seems [pyenet on pypi](https://pypi.python.org/pypi/pyenet) is gone. It consistently returns 404 for me, and the search for `pyenet` only returns a match for `pygnetic`.

**Comment by squiddy** [comment]
Obviously FIFE is free to do what they want with their time, but I don't think we would gain much, would we?

**Comment by LinuxDonald** [comment]
yeah maybe that it is. But fife itself needs network lib too. Not for us. We have it already.
But broken.... (Out-of-sync)

**Comment by squiddy** [comment]
What needs to be done here? Merely building new versions of pyenet that we ship with the game?

**Comment by LinuxDonald** [comment]
Need version of pyenet still for Windows for all supported python3 versions. For Linux an python3 3.5 Build? On freebsd we need to builds. Or we must talk with the maintainer that they create an python3 package.

**Comment by LinuxDonald** [comment]
We need now python3-enet rebuild for python3 3.5. Debian 9 is out now an we should switch to min python 3.5 Support now?

**Comment by MasterofJOKers** [comment]
Why do we need 3.5 packages? As long as we're using 3.4 on travis, we don't have to rebuild packages. Once we only want to support 3.5, that rebuild can be done, I guess. But we should probably change to docker on travis first, as I would have to replicate the python3.5 environment available on travis to build a 3.5 package for travis, which sounds like too much effort really.

**Comment by LinuxDonald** [comment]
My plan is to change travis to python3 3.5
Maybe we should upload the enet and python3-enet to opensuse build service and build there the packages?

**Comment by LinuxDonald** [comment]
When it takes to much time to rebuild it. It can wait.

**Comment by jmdejong** [comment]
We don't ship our own version of pyenet anymore. We just have it as dependency.
We also have instructions now for [[installing-pyenet]].

I think we can close this.
