### ISSUE TITLE
Autoresizecontainer pychan

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2613]
Auto resize container looks like it is broken on pychan.
I dont now why.

See pr for pychan update: https://github.com/unknown-horizons/unknown-horizons/pull/2612

**Comment by squiddy** [comment]
Can you be more specific? If anyone wanted to fix it, they wouldn't have any clue what this is about.

**Comment by LinuxDonald** [comment]
The problem here is that on gui where we use AutoResizeContainer they not get "rendered" you only see am empty gui. And no error message get showed.

**Comment by LinuxDonald** [comment]
An option would be to completely remove it and rewrite the gui parts that it use.

**Comment by LinuxDonald** [comment]
Fixed with https://github.com/unknown-horizons/unknown-horizons/commit/386b90ec42494c0cf7f6f30284c5434dbf6cd808
