### ISSUE TITLE
Create Tier 5 Residential house

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2623]
The first building that we need for tier5 is an Residential house.
The DD say only "estate".

@janexx thats something for you ;)

1 living tent
2 log house
3 half-timbered house
4 stone house
5 estate
6 manor

**Comment by LinuxDonald** [comment]
@janexx any news about it? :(

**Comment by janexx** [comment]
Yes! I have a building. :)
![0](https://cloud.githubusercontent.com/assets/6216898/26008762/702c9fa8-3746-11e7-97b9-1d26ac6ff203.png)


 Where can I upload it for testing?

**Comment by AndyMender** [comment]
@janexx, if that doesn't trouble you too much, could I also participate in creating the models? I do have some past experience in making armors and clothing for The Elder Scrolls Oblivion and Skyrim in Blender. I am currently re-learning the new Blender interface and I would love to put that knowledge into practice :).

**Comment by janexx** [comment]
@AndyMender No, sure you can join. :) At least one more model is needed. I am working at the moment on the second house.

**Comment by LinuxDonald** [comment]
Done with PR: https://github.com/unknown-horizons/unknown-horizons/pull/2701
