### ISSUE TITLE
Run 2to3 against codebase

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2632]

**Comment by AndyMender** [comment]
I'm working my way through the many .py files with 2to3, but trying to tackle one file at a time, because:
- Python2.7.x was receiving incremental adjustments throughout past months to make the transition to Python3.x easier.
- Per above, some files may not need to be changed at all or require only a simple 2to3 run-through.
- Messing up the whole codebase with 2to3 and then randomly trying to fix everything may not be very productive.

**Comment by squiddy** [comment]
Well, I don't agree with that approach, but I guess I'll just wait till your done.

**Comment by AndyMender** [comment]
How would you rather do this then? :)

**Comment by squiddy** [comment]
Never mind my comment. What's important is the result, not so much how we get there. :)

**Comment by AndyMender** [comment]
I managed to introduce some fixes, however I hit a wall in horizons/util/python/decorators.py. There is a strangely constructed recursive function called _make_constants. More details on the specific problem here: https://github.com/AndyMender/unknown-horizons/commit/3ac02a5e5e08732f2a6fe28627ba0b1caf0e3911

I noticed you removed _make_constants and bind_all in your python3 branch and used recursive lambdas instead. Is this necessary? :)

**Comment by squiddy** [comment]
See issue #2634 

I replaced them with lambdas to make them no-op, because at the time I didn't want to waste time fixing some performance-bytecode-hacks, which may not even be needed, and therefore doesn't help the goal to complete the port.

Can't tell you more about it, because I haven't spend time looking into the issue, and honestly, don't plan to do so. Maybe after the port is working.

**Comment by AndyMender** [comment]
Ah, I remember that issue now. It was one of those "may or may not require extra attention". if I cannot find a clean fix for it quickly (as in, today), I will simply use the lambdas you suggested and proceed further.

**Comment by squiddy** [comment]
If you manage to fix it, we should evaluate later if these optimizations still help us.

**Comment by AndyMender** [comment]
As the py3 branch was merged into master, we assume everything is at least Python3-compliant :).
