### ISSUE TITLE
Build FIFE (python3 branch) for Travis

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2633]

**Comment by MasterofJOKers** [comment]
Just tell me, when you need it and I'll upload a package for travis to use. Can I replace the current one or do you need a new repo for the py3 branch to get the package from?

**Comment by squiddy** [comment]
Actually, I've noticed that we would need two new builds.

1) A separate repo for the python3 branch (this issue)
2) An update on the current repo for master (#2638). We can't run tests on master currently, because of the merge of our pychan_port branch.

**Comment by squiddy** [comment]
About the when.. well, the sooner the better. :) I'd like to start working on the py3 port again soon, if Travis could run tests as well, that would help a lot.

**Comment by MasterofJOKers** [comment]
I'll get to it later today and then tell you the repo you should use in the .travis.yaml for the py3 branch, once the packages are in place.

**Comment by squiddy** [comment]
Cool, thanks. :+1:

**Comment by AndyMender** [comment]
@LinuxDonald adjusted the .travis.yml config so that fifechan and fifengine are built on the Travis CI virtual machine, but it takes 10 min 30 sec to complete the tests each time. Therefore, we most likely still need packaged python3-fife for Debian/Ubuntu.

**Comment by squiddy** [comment]
For the time being, we can evaluate the caching feature of Travis (https://docs.travis-ci.com/user/caching/) and/or experiment with `ccache` (whose output we can cache, see travis) to speed future compilations.

**Comment by LinuxDonald** [comment]
@MasterofJOKers are you maybe avaliable for this task?

**Comment by MasterofJOKers** [comment]
@LinuxDonald Building packages for fife python3 you mean? I should find some time this week. Just have to look at what changed on fife's side. We did merge py3 into master, didn't we? So I don't need to keep the py2-stuff around and just change to py3, which would simplify the integration into my script.

**Comment by LinuxDonald** [comment]
Yes only python3 now. Python3 is now merged into master on fife and uh. Fife master support too py2 but we don't need it. But if your system defaults to python2 you need an switch see our travis file.

**Comment by MasterofJOKers** [comment]
Package python3-fife is available at `deb [trusted=yes] https://debian.unknown-horizons.org/travis/ /`

**Comment by LinuxDonald** [comment]
fixed with: https://github.com/unknown-horizons/unknown-horizons/commit/bf1420b25c06af95213569bc343ba2b7e95538a3
