### ISSUE TITLE
Update FIFE build for Travis CI

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2638]
Right now all the GUI tests are failing again because our FIFE build for Debian, that we use for Travis, is too old.

@MasterofJOKers Could you please update the build in your repository and/or explain the steps taken for the build?

**Comment by MasterofJOKers** [comment]
I've written a build-script to build fife/fifechan packages for debian-base distros to get packages into https://debian.unknown-horizons.org/
I don't know if I feel comfortable with showing it yet, though. We should switch to https://debian.unknown-horizons.org with travis once nightly-builds and proper version dependencies are available in that repo.

**Comment by squiddy** [comment]
> I don't know if I feel comfortable with showing it yet, though.

Sure, no problem. We've all been there. :)

> We should switch to https://debian.unknown-horizons.org with travis once nightly-builds and proper version dependencies are available in that repo.

Is there still work to do? If yes, is anyone working on that? I'm pretty much clueless what's going on right now regarding packages.

**Comment by MasterofJOKers** [comment]
These are official unofficial packages built by "us" (me) to bring older versions of debian/ubuntu new fife packages to run the latest UH release. The plan was (and still is) to also build UH packages and have two types of repos available: nightly builds and stable builds. Currently, there are only packages of the latest stable fife (0.4.1) for trusty, xenial, yakkety and stretch.

I'm working on that occasionally.

**Comment by MasterofJOKers** [comment]
Updated.
