### ISSUE TITLE
Animations loaded with an x, y offset in a loop

### ISSUE THREAD

**Issue by AndyMender** [unknown-horizons/unknown-horizons#2642]
**CORRECTED:** This is a new issue that seems to have appeared in the Python 3 code base. Each animation has **only** the first frame in the animated object's correct position, while the remaining animation plays with an offset in x and y. In the case of animals and animated ships they look as if they were jumping. It's more problematic for buildings, because then it's difficult to place them properly.

This is not a breaking bug, but significantly impairs the usability of UH :). Maybe @helios2000 or one of the animators has an idea?

**Comment by AndyMender** [comment]
The culprit was looping overriding of the `XShift` and `YShift` parameters of the img object. If this happens again, consider using `getXShift` and `getYShift` calls of the img object to get/check the shift values.

**Comment by LinuxDonald** [comment]
Maybe we should fix isseu #1379 
i dont like the idea about gif support. Because we have Atlas Support.

**Comment by AndyMender** [comment]
I discussed the matter of .gif loading and usage on the #python irc channel today and the general consensus is "find a different approach". It's doable, but involves dirty solutions and we don't want those.
