### ISSUE TITLE
Soldiers can't be selected (and some more bugs)

### ISSUE THREAD

**Issue by technikamateur** [unknown-horizons/unknown-horizons#2645]
Hi unknown-horizons developer,
first of all I want to say: Thank you for this game! It is awesome, what a free community can build. I've played the game for about 20 hours (in one savegame) and want to share some bugs / strange things with you:

- soldiers can't be selected - wich means if I click on a soldiers, the game insteandly crashes
- There is a huge imbalance with food and salt: On the one hand I need 2 fisher to get enough food for ~ 400 People. On the other hand I need more than 20 salt gardens to have enough salt. This is a bit strange. Isn't it?
- War ships are out of control. I don't know what they are doing but I am not able to fight against a ship. They ignore my command. But suddenly they start attacking random ships of one player. A cool thing is that some war ships are able to swim trough certain islands, which makes them to great trader ships because it saves a lot of time ;)
- stage 4 settlers need a lot of time for downgrading. If they have got no market, church, tobacco, a tavern and food, they will need about 10 minutes for a downgrade. During this time, the forest grows twice.
- version 2017.02 is older than version 2017.01

Thanks for your attention and I hope this can be fixed.

**Comment by LinuxDonald** [comment]
Thank you for the feedback.
The Solider problem is knowed problem. Because its not yet implmented.
For War Ships the same there is an bug.
For balance we want to fix that later after we fixed some bugs.

**Comment by AndyMender** [comment]
@technikamateur Also, if the game ever crashes on something reproducibly and it's not a Segmentation Fault do open an issue ticket and we'll try to fix it :). Look through the issue tracker as well, since some issues and bugs have been there already.

**Comment by technikamateur** [comment]
Thanks for your replies. I'll keep that in mind.
