### ISSUE TITLE
Reset upgradable savegame revision to 76

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2658]
Currently our savegame upgrade (seems) to work for revisions as old as 46, which is part of of the 2012.1 release. That's 5 years of upgrades.

In my opinion we should remove the upgrade of versions older than 76, version 75 was part of release 2015.1. I doubt anyone is using such old versions and expect the savegames to upgrade. Even if, so many features were added that it's probably a better experience to start a new game.

This reduces code and can simplify/fix some tests relying on fixtures with very old savegame revisions. However, it also means recreating some of those test fixtures.

**Comment by AndyMender** [comment]
This code? github.com/unknown-horizons/unknown-horizons/blob/master/horizons/util/savegameupgrader.py

I agree that we should not expect the game to be compatible with extremely old savegame files. So the assumption is that version 76 (current?) is the new `SAVEGAME_LEAST_UPGRADABLE_REVISION` as defined in `horizons.constants.VERSION`?

**Comment by squiddy** [comment]
Yes.

**Comment by LinuxDonald** [comment]
What about an complety savegame break? It would make it alot easier to fix this ticket for example: https://github.com/unknown-horizons/unknown-horizons/issues/2345

**Comment by squiddy** [comment]
I'm curious, why would it make it easier?

Also I wouldn't really break compatibility with other releases from this year unless necessary.

**Comment by LinuxDonald** [comment]
Wouldn't it break savegame when I/we change Produktion lines from numbers to "Words/Text"?

**Comment by LinuxDonald** [comment]
Yeah breaking an release from this year is really not an good idea...

**Comment by squiddy** [comment]
> Wouldn't it break savegame when I/we change Produktion lines from numbers to "Words/Text"?

That's what the savegame upgrader is for. I'm not suggesting here to remove it entirely, just the upgrade path from everything < 76. Which essentially means all upgrade code will be removed, but the infrastructure stays.

**Comment by AndyMender** [comment]
I removed all upgrade methods and all upgrade calls for all savegame revisions prior to 76. However, I left a `_upgrade_to_rev77` placeholder and a `rev > 77` check so that it's immediately obvious in the future how to apply savegame upgrades.

**Comment by squiddy** [comment]
Aaaand you broke the tests again. :|

That's why I explicitly mentioned that the tests need fixing. Now the master is broken again. 

Perhaps we should force change to go through pull requests for everyone to avoid this in the future...

**Comment by AndyMender** [comment]
My apologies and I agree :(. For future bigger commits I will branch and create pull requests to avoid problems.

**Comment by AndyMender** [comment]
I also noticed that https://github.com/unknown-horizons/unknown-horizons/blob/master/tests/game/test_savegame_upgrade.py and https://github.com/unknown-horizons/unknown-horizons/blob/master/tests/game/test_traderoute.py relied on a revision 49 savegame file, but they could not be loaded due to a `KeyError` with map coordinates and were eventually removed from the test suite. Also, test test_savegame_upgrade.py is nothing but a placeholder right now:
```py
from tests.game import game_test
from tests.utils import mark_expected_failure

# FIXTURE is a savegame revision 49
@mark_expected_failure
@game_test(use_fixture='savegame-rev-49')
def test_upgrade(s):
	"""
	Simply let's do nothing except loading the fixture
	"""
	pass
```
I think it would be good to have at least the test_traderoute.py running properly with a brand new savegame.

**Comment by squiddy** [comment]
Yeah, that upgrade test should be removed now. Or, better yet, the fixture replaced with a new version and the mark-decorator removed. This way, once someone adds a new upgrade it will be tested automatically.

**Comment by squiddy** [comment]
And yes, all the tests should run. I've opted to skip the two failing tests because otherwise the test runs would be falling all the time and we'd gain nothing from automated tests.

**Comment by squiddy** [comment]
@AndyMender Sorry about my earlier comment, it was unnecessary harsh. I might be a bit too sensitive when it comes to tests. :) When I joined this project, there was a custom test runner (which I replaced  387b7a6cc7b5f82a46fa7a78ff3ff78953042c16) with maybe 3 tests, two of them broken. I invested a lot of time into the infrastructure for tests, so it's sad to see them broken.

I didn't mean to discourage you, you're doing great work!

**Comment by AndyMender** [comment]
I was not discouraged in the least bit. Rather, more encouraged to test my work before submitting.. I would like to learn more about the test infrastructure as I too believe that unittests and proper coverage are important for larger projects. We don't want our commits to start breaking stuff allover the place, right? :)

**Comment by squiddy** [comment]
I adjusted the fixture for the test, we're done here.
