### ISSUE TITLE
i cant install

### ISSUE THREAD

**Issue by mbol8309** [unknown-horizons/unknown-horizons#2678]
hi, i have fedora 25 and i followed all the steps of several pages and cant installit, please need detailed instuction how to installit in fedora 25, the errors when i tried to run it is:
Failed to use FIFE from <module 'fife' from '/home/****/fifengine/engine/python/fife/__init__.py'>
cannot import name 'fife'
Error: Failed to load module fife
Below directory paths were tested:
/home/****/fifengine/engine/python

**Comment by AndyMender** [comment]
Have you followed this guide? http://docs.fifengine.net/developer-manual/en/
Also, how do you launch Unknown Horizons from the command-line specifically? It seems like the game is trying to pick up the FIFE module from a non-standard path and fails.

**Comment by mbol8309** [comment]
i download from github in my home folder
then i run ./setup.py build_i18n and then ./run_uh.py
i followed a guide that show me that. and that guide that you told me, i followed that

PD:sorry for my bad english.

**Comment by AndyMender** [comment]
Do you perhaps have both the unknown-horizons repository and the fifengine repository in the same parent directory like so?
parent_dir/unknown-horizons
parent_dir/fifengine

This is known to not work properly due to the way run_uh.py searches for the FIFE module. Just in case, whereto did you install the FIFE module?

**Comment by LinuxDonald** [comment]
@mbol8309 fedora rpms for the engine you can find here:
fifengine: https://github.com/unknown-horizons/linux-packages/tree/master/fedora/fife/RPMS/F25
fifechan: https://github.com/unknown-horizons/linux-packages/tree/master/fedora/fifechan/RPMS/F25

For UH i dont have rpms yet.

**Comment by squiddy** [comment]
Closing because we got no feedback. If you encounter new problems or have new information, please feel free to reopen this issue. We're happy to help.

**Comment by gonthalo** [comment]
Same thing happened to me, i fixed it after noticing another package named 'fife' was already installed (pip3 list) I had installed it thinking fifengine was a prenamed python library
After uninstalling and reinstalling fifengine, i only had to restart the terminal and it works.
