### ISSUE TITLE
Game not starting for non-admin on Windows 7/10

### ISSUE THREAD

**Issue by kruug** [unknown-horizons/unknown-horizons#2679]
Operating System: Windows 10 x64
Game Version: 2017.2

Problem:
Go to start UH, CMD windows pops up with

    Starting Unknown Horizons
    Output will be written to logfile

A white windows appears, disappears, and then CMD says "Press any key to continue..."  No logfile appears to be written either.

Not a local admin.  Installed using admin account to C:\Unknown-Horizons.  Trying to run the game under normal account.

**Comment by AndyMender** [comment]
Are you running the game from cmd.exe / command line? Any extra error output, like Python tracebacks?

**Comment by kruug** [comment]
I am running the game from the Start Menu entry.  Points to `C:\Unknown-Horizons\unknown-horizons\run_uh.bat`

When trying to run it from CMD, same issue.

No extra error output.  Nothing from python.

**Comment by AndyMender** [comment]
Did you install the game by running setup.py in the git repository? Also, do you have FIFE and fifechan installed?

**Comment by kruug** [comment]
No, I installed the game by running the downloaded `Unknown-Horizons-2017.2.147-Setup-VC14-x86.exe`.

**Comment by kruug** [comment]
Works with an account with Admin rights.  Doesn't work on "Regular" user account.

**Comment by kruug** [comment]
Found this in fife.log:

Controller:LOG:Fifengine v"0.4.1"+bbd1e9bc
Controller:LOG:================== Engine initialize start =================
Controller:LOG:Time manager created
Controller:LOG:Creating VFS
Controller:LOG:Adding root directory to VFS
VFS:DEBUG:VFSDirectory created with root path ./
VFS:LOG:new provider: OS Directory
Controller:LOG:Adding zip provider to VFS
VFS:LOG:new provider: ZIP
Controller:LOG:Engine pre-init done
Controller:LOG:Creating event manager
Controller:LOG:Creating resource managers
Controller:LOG:Creating render backend
Controller:LOG:OpenGL Render backend created
Controller:LOG:Initializing render backend
Controller:WARN:Selected video driver is not supported for your Operating System!  Reverting to default driver.
Controller:LOG:Querying device capabilities
Controller:LOG:Creating main screen
Video:LOG:RenderBackendOpenGLVideomode 1024x768 at 0 bpp with 60 Hz
Controller:LOG:Main screen created
Controller:LOG:Creating sound manager
Controller:LOG:Creating renderers
Controller:LOG:Creating model
Controller:LOG:Adding pathers to model
Controller:LOG:Adding grid prototypes to model
Hexgrid:DEBUG:Constructing new HexGrid
Hexgrid:DEBUG:HEX_WIDTH 1
Hexgrid:DEBUG:HEX_TO_EDGE 0.5
Hexgrid:DEBUG:HEX_TO_CORNER 0.57735
Hexgrid:DEBUG:HEX_EDGE_HALF 0.288675
Hexgrid:DEBUG:VERTICAL_MULTIP 0.866025
Controller:LOG:Engine initialized
VFS:DEBUG:Opening: content/audio/music/menu\main_theme.ogg
VFS:DEBUG:Opening: content/gui/images/cursors/cursor.png
Exception:ERROR:_[SDLException]_ , SDL reported something bad :: Fatal Error when loading image into a SDL_Surface: Failed loading libpng16-16.dll: The specified module could not be found.

**Comment by squiddy** [comment]
Can confirm the same problem in Windows 7, using a non-admin account.

**Comment by squiddy** [comment]
I made this issue a blocker for the next release. It is easily reproduced and we shouldn't / can't expect our players to be running admin accounts.

**Comment by LinuxDonald** [comment]
I will test it an provide an new installer if it works :)

**Comment by squiddy** [comment]
> I will test it [...] if it works :)

Better keep the issue open then.

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/releases/download/2017.2/Unknown-Horizons-2017.2.158-Setup-VC14-x86.exe

FIXED. Windows 10 will now give an Warning at the Installation Process. Because its not an signed Installer and its install a little depper into System see: https://github.com/unknown-horizons/uh-installer/commit/94f18c0acfc475c25c74610afe5ea796cad2f885

**Comment by squiddy** [comment]
Works on Windows 7. :+1:

**Comment by kruug** [comment]
Works on Windows 10. :thumbsup:
