### ISSUE TITLE
Release 2017.2 advertising 2017.1 as newer release

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2682]
Just installed `Unknown-Horizons-2017.2.147-Setup-VC14-x86.exe` on Windows 7 and was greeted with this:

![2017-05-17 17_47_21-program manager](https://cloud.githubusercontent.com/assets/50333/26163187/306f5158-3b29-11e7-894b-41d9afeb05ef.png)

> There is a newer version (2017.1) available than the one you're currently using (2017.2)

I would expect to not see this message at all. Also, the logfile path seems broken, I'm assuming it has something to do with the formatting.

**Comment by LinuxDonald** [comment]
It's an error with Web server. Last time Nightraven must update it on server side. I don't know how and where to change it to an new system.

**Comment by squiddy** [comment]
> I don't know how and where to change it to an new system.

I haven't put much thought into it, but essentially it's just some static information at a given URL. Probably some JSON with the newest release version and link.

Something we could easily host with GitHub on our new homepage, e.g. `http://unknown-horizons.org/release-data.json`

**Comment by squiddy** [comment]
`http://updates.unknown-horizons.org/current_version.php` is the URL we're calling, the response is simply

```
2017.1
http://www.unknown-horizons.org
```

I see no reason why we couldn't update the URL for the new release to `http://unknown-horizons.org/current-version.json` and host that information statically.

**Comment by squiddy** [comment]
@LinuxDonald It would still be good to have the current file be updated, I was quite surprised to see that pop up right after start.

**Comment by LinuxDonald** [comment]
@squiddy could you maybe add that file? I don't know how to write/ how it must look like.

**Comment by squiddy** [comment]
I'm going to open a new issue to track the implementation. We should leave this one open to fix the current version info.

**Comment by squiddy** [comment]
@Linuxdonald Any news on this? The next release will use the new version check, but this should still be fixed if possible.

**Comment by LinuxDonald** [comment]
For an fix we would need an backport. Then we could release an hot fix.

**Comment by squiddy** [comment]
Why can't we just change the version on the existing server? You said:

> Last time Nightraven must update it on server side. 

Why can't we do it now one last time?

**Comment by LinuxDonald** [comment]
Because its very hard to get into contact with him :( Sometime it takes months

**Comment by squiddy** [comment]
I see. Perhaps a backport is indeed necessary here.

**Comment by LinuxDonald** [comment]
Next release will be 2018.1 not update planed for the old release anymore.
