### ISSUE TITLE
Run multiplayer tests on travis by providing enet bindings

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2691]
~~For example here: https://travis-ci.org/unknown-horizons/unknown-horizons/builds/234343626~~

~~The tests apparantly won't continue to run until Travis decides to abort the build due to inactivity.~~

See https://github.com/unknown-horizons/unknown-horizons/issues/2691#issuecomment-307438696

**Comment by LinuxDonald** [comment]
The gui test don't need the enet lib right?

**Comment by squiddy** [comment]
They do, they open up a master server and test the lobby.

**Comment by LinuxDonald** [comment]
At the moment we only provide pyenet for 64 bit linux System See: https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/network/libs/enet.txt

Pyenet git master + enet 1.3.13

**Comment by LinuxDonald** [comment]
Hm travis is 64 bit. But maybe pyenet needs to compiled on an older distro than arch linux.

**Comment by squiddy** [comment]
The game with the gui test seems to start, but get's stuck after `Preloading done`:

https://travis-ci.org/unknown-horizons/unknown-horizons/builds/234588106

**Comment by LinuxDonald** [comment]
On my local maschine the test runs fine.

**Comment by squiddy** [comment]
Next steps:

1. Figure out whether enet is loaded. Probably just a python one liner of "find_enet.
2. Find out what happens after "preloading done"

**Comment by squiddy** [comment]
Enet can't be loaded on Travis. I recently added a check to skip mp tests on systems without enet, and that's exactly what happens.

>SKIP [1] tests/unittests/mp/test_run_server.py:44: No enet bindings available

**Comment by LinuxDonald** [comment]
But we have an enet in master for python3 versions 3.4 and 3.6 and travis use 3.4?

**Comment by squiddy** [comment]
Yes. When attempting to import enet, we probably ignore the exception message.

Perhaps it's something as simple as libenet missing on Travis? If that library has to be installed, I'm not sure whether that's included in the python enet files.

**Comment by LinuxDonald** [comment]
It should be included in the enet.so file. Because on creating the enet python lib you need the enet source files/cpython and the python version that wanted to be used.

**Comment by squiddy** [comment]
> Because on creating the enet python lib you need the enet source files/cpython and the python version that wanted to be used.

Well, that doesn't necessarily mean that the library is statically linked. You need header files to link dynamically as well. Will try this out later today, I'm pretty sure I had to install libenet a couple days ago.

**Comment by LinuxDonald** [comment]
Yepp you are right @squiddy https://packages.debian.org/experimental/python3-enet
I have added it to travis

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/bf1c847f5ff9255baae8636f0e23351da1ef0e72

why travis dont have yet Ubuntu 16.04 LTS version :(

**Comment by squiddy** [comment]
Travis won't switch in the foreseeable future, they said in a github issue. Switching incurs huge costs. 

If we really wanted we could use their docker feature and use a newer release.

**Comment by LinuxDonald** [comment]
But setting up docker on travis would costs time.
Maybe We could setup docker on travis in the future or use appveyor (Windows System) for the tests.

**Comment by squiddy** [comment]
Ah no, I didn't mean to suggest to do that **now**. Was just providing extra information about why Travis doesn't switch.

To fix this, I'd rather see us build a proper enet package for debian and use that.

Running tests on appveyor **additionally** would be nice.

**Comment by MasterofJOKers** [comment]
Did I understand correctly, that "proper package" means backport of a newer package? If yes, I could take a look at that.

**Comment by LinuxDonald** [comment]
@MasterofJOKers we need python3-enet package created against Ubuntu 14.04 Because chrirstop_debian package is only for new debians.

**Comment by squiddy** [comment]
Changed the topic to keep the discussion focused. The tests running forever are caused by the missing enet bindings, I just confirmed it locally.

**Comment by LinuxDonald** [comment]
@squiddy does it on arch linux dont work too? How i can only do this one test?

**Comment by squiddy** [comment]
It does work on arch. I merely *simulated* missing enet bindings and confirmed that the multiplayer gui tests run forever. That's why this is no special problem with Travis, but with the tests & missing enet bindings.

**Comment by squiddy** [comment]
Fixed in b36013da163ea6a1a73deec56f25b4ae03127f3a

Unfortunately it seems that I've broken the multiplayer a bit more, that's why the tests are failing right now.
