### ISSUE TITLE
Fix failing traderoute gui test

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2692]
```
$ pytest --gui-tests tests/gui/ingame/test_traderoute.py                                                                                                     env [9:38]
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/reiner/projekte/unknown-horizons, inifile:
plugins: xdist-1.16.0, warnings-0.2.0, mock-1.6.0, cov-2.4.0
collected 1 items 

tests/gui/ingame/test_traderoute.py F

=============================================================================== FAILURES ===============================================================================
___________________________________________________________________________ test_traderoute ____________________________________________________________________________
Traceback (most recent call last):
  File "/home/reiner/projekte/unknown-horizons/tests/gui/__init__.py", line 128, in _tick
    cooperative.schedule()
  File "/home/reiner/projekte/unknown-horizons/tests/gui/cooperative.py", line 86, in schedule
    g.switch(*args, **kwargs)
  File "/home/reiner/projekte/unknown-horizons/tests/gui/ingame/test_traderoute.py", line 59, in test_traderoute
    gui.trigger('overview_trade_ship/configure_route')
  File "/home/reiner/projekte/unknown-horizons/tests/gui/helper.py", line 339, in trigger
    raise Exception("Widget '{}' not found".format(widget_name))
Exception: Widget 'overview_trade_ship/configure_route' not found
```

I'm pretty sure one issue is that the second ship can't found a settlement, when running locally, the building was red and couldn't be placed.

**Comment by squiddy** [comment]
I'm gonna try to fix this one today evening.

**Comment by AndyMender** [comment]
Perhaps a new savegame fixture is needed for this test?

**Comment by squiddy** [comment]
It might even just be something as simple as a tree blocking the way. Anytime the random map generation code is changed, tests using fixtures might break.

I'm toying with the idea of generating the map/fixture programmatically, like we do in game tests. I don't like the dependence on specific maps that ship with the game or the random map algorithm.

**Comment by squiddy** [comment]
Copying from the commit message:

Two issues had to be fixed:

> 
>   1. The second settlement couldn't be build anymore because a claypit
>      was in the way. We do use the same random seed for all test runs,
>      however, even the slightest change in the random map / nature
>      population algorithm can break tests because resources change
>      positions.
> 
>   2. The recent changes to the trade route widget broke some widget
>      names in the test, such as traderoute_resources which doesn't exist
>      anymore.

**Comment by AndyMender** [comment]
I'm afraid I might be responsible for issue 2. Apologies and good job on fixing this :).
