### ISSUE TITLE
Create Tier 5 Public Bath

### ISSUE THREAD

**Issue by AndyMender** [unknown-horizons/unknown-horizons#2698]
I would like to contribute to the graphics aspect of Unknown Horizons as well. Per discussions with @LinuxDonald, one of the new, yet not implemented tier 4 buildings is a bath house. I have experience with 3D modeling in Blender, but none insofar regarding Unknown Horizons models. Therefore, I would need some initial "hand holding" and feedback from @janexx. 

This might serve as an initial inspiration: https://vignette2.wikia.nocookie.net/anno1404guide/images/9/9f/Bathhouse.png/revision/latest/scale-to-width-down/250?cb=20091118174520 . I am open to any and all feedback (style fitting other tier 4 buildings? general time period and culture?).

**Comment by janexx** [comment]
Nice @AndyMender ! I just find it a bit unpractical that people have to climb up in the swimming pool. Maybe better make a kind of whole in the ground, maybe with a small stair? You could also add some seats. Just my ideas... :)

**Comment by AndyMender** [comment]
Yes, this of course makes a lot more sense. I will try to make a square pool in the middle with some stairs. Would look a lot better, I'm sure!

**Comment by janexx** [comment]
Good! Looks better now. I would make the stairs over the whole width of the pool. I am looking forward to see the it with textures! I recommend to make preview renderings in the final image size. :)

**Comment by AndyMender** [comment]
I'll try to UV-map and texture/shade the thing and we'll see what still needs to be done. @janexx do you perhaps have custom texture sets for roof tiles and stone brick walls, used for other buildings in Unknown Horizons?

**Comment by LinuxDonald** [comment]
Maybe add some flowers or something like decoration?

**Comment by squiddy** [comment]
Also, the walls/roof should probably look like it was made from actual single stones / tiles. Right now, it's just a texture on top. Isn't there some magic like normal maps / bumpmapping to improve the visuals here?

**Comment by AndyMender** [comment]
There is. The texture lacks a normal map, but that can be added and fed to the right shader. Alternatively, I could create the tiles in Blender entirely (using the current textures as base). This takes a bit more time for rendering afterwards, of course.

**Comment by janexx** [comment]
@AndyMender  We have already roofs. You can use and mybe modify them (copy or via append). Just look at other models with roofs, e.g. other habitant houses. For the bricks, you can try just a bump map or model the bricks yourself. Or you can use some of the stone wall: 
https://github.com/unknown-horizons/gfx/blob/master/janexx/buildings/wall/wall_stone/wall_stone_BLENDER-v278.blend
Also look at the small rendered image, not just at the 960px × 540px image.

**Comment by AndyMender** [comment]
Thank you @janexx . I will do that then :).

**Comment by AndyMender** [comment]
Update: new version with hand-crafted roof tiles and bricks. 
![bathhouse0001](https://user-images.githubusercontent.com/15969405/26914058-55bbf540-4c1f-11e7-824e-7b4bd661aa6e.png)

**Comment by LinuxDonald** [comment]
Maybe the roof should be in an other color? what do you think @janexx ?
And still no ground texture.
Thr floor should be gone texture maybe instand of wood.

**Comment by janexx** [comment]
The roof is better now. The single roof tiles just seem a bit small? I don't know how it looks in 128x128 pixel size (or what tile size should it have @LinuxDonald ?) Please give me also the render image in final size. :)
But I also would say, that the roof and the walls should have at least a bit different colour. The whole ground could maybe get a stone texture? I guess the ground texture inside the house (now the wood) won't be visible at the end. Looks a bit modern. :) When we use wood for building before, we modeled them because elswise you see just a brown plane.

**Comment by LinuxDonald** [comment]
Yeah @janexx is right @AndyMender please do what jana have written :)
Size should be 2x2 i think?

**Comment by janexx** [comment]
Ehm I just want to add that are not orders, just ideas and hints. :)

**Comment by LinuxDonald** [comment]
@janexx you are the chief grafic artist :P And i like your ideas you make wonderful grafics :)

**Comment by AndyMender** [comment]
Yes, now that I look at it again, the roof should definitely have a different color (maybe some brighter red?). I will remove the wooden floor texture, too. Finally, I was thinking of adding some greyish plaster in-between the bricks. Will this be visible in the final render?

No ground texture was planned, but if the building is supposed to be a 2x2 and not 2x3, then I might want to add some grass or something similar. Frankly, I didn't look at the dimensions properly yet :(.

**Comment by janexx** [comment]
> Will this be visible in the final render?

Try it out!

@LinuxDonald  Is also 2x3 possible? I think that would look good.

**Comment by LinuxDonald** [comment]
3x3 would be better. Because eoc said to me long time ago that grafics with sizes for example: 3x2 or 4x3 and so on would be make problems. You cold make some stone or something on both sides. To fit into 3x3.

**Comment by AndyMender** [comment]
I decided not to add a grey plaster in-between the bricks since it would not be visible anyway. The building is mostly finished and if possible, I would like to get back to working on the Python code and leave generating the renders to @janexx. 
![bathhouse0001](https://user-images.githubusercontent.com/15969405/27253254-5ede2f7c-5371-11e7-9ba0-5431c216b0a1.png)
To that end, how do I upload the .blend since I don't have access to the gfx repository?

**Comment by LinuxDonald** [comment]
You have now the needed rights for uploading @AndyMender maybe @janexx could do some final work on the bath?

**Comment by janexx** [comment]
@AndyMender  Ok, I can do the rendering. I thought you render it at least once in the final render size so that we see how it will look like. But OK, I can do that and then post it here. Is it OK for you when I do some final work then or do you want to do that yourself then?
Can you add a new folder in the gfx repository with your name and upload the blend file there?

**Comment by AndyMender** [comment]
@janexx , yes, I am perfectly fine with you doing some extra adjustments if you feel they're needed :). I don't have much experience with rendering, unfortunately. The added .blend file is here: https://github.com/unknown-horizons/gfx/commit/1ce8b205688eb6b69b8c667d9311dfb3ca4fca4d

**Comment by janexx** [comment]
@AndyMender Thanks, I have it now. I adapted it so that it fits into our default szene and rendered it:
![000](https://user-images.githubusercontent.com/6216898/27254605-e0842dbe-538b-11e7-87ea-48bc8fd8b21c.png)
![000](https://user-images.githubusercontent.com/6216898/27254608-ed474b12-538b-11e7-81c0-3356774b929a.png)
In the default UH camera view now one almost can't see any water. I would propose to add more and bigger entrances, maybe more roundly.

**Comment by AndyMender** [comment]
Maybe we should make the side entrances to the pool go through the external walls or open up part of the front with Roman-style columns?

**Comment by janexx** [comment]
Yes, that sounds nice! I haven't even noticed that there are side entrances...  :) Do you want to model that? I can do that too if you rather want to code again, but I don't want to take away your model. I could upload the current blend file with the proper settings (camera, light).

**Comment by janexx** [comment]
Also the render script is in, you would just have to press alt+P in the text editor view.

**Comment by AndyMender** [comment]
If you could upload the improved .blend. I will take care of the side entrances :). Thanks a lot for providing the script!

**Comment by AndyMender** [comment]
@janexx , I added the extra doorways as we discussed: https://github.com/unknown-horizons/gfx/commit/c366e3112c6060d9b4c4bf6fe000ea312914c70f
Unfortunately, even with your script the renders don't show anything for me, because I have some nVidia related issues with the Cycles Render engine as of late.

**Comment by janexx** [comment]
@AndyMender Hm OK. I would say, its not bad, but there is still some room for improvement.. :)
![000](https://user-images.githubusercontent.com/6216898/27264244-a7ade940-547a-11e7-9677-fde0b5f3e12e.png)
![000](https://user-images.githubusercontent.com/6216898/27264251-bca9a1f4-547a-11e7-8afa-94a8be837461.png)
 E.g. Colors, nicer/round entrances and windows, columns...  :D

**Comment by LinuxDonald** [comment]
Maybe Glas walls?

**Comment by AndyMender** [comment]
![bathhouse0001](https://user-images.githubusercontent.com/15969405/27264799-47f7899a-5487-11e7-9a28-1ae45316cbfb.png)
With columns. Added to the unknown-horizons/gfx repository.

**Comment by janexx** [comment]
@AndyMender That looks nice with the columns. Now the nice water is visible. I like that water with the white rings. Only the red brick I don't like so much and the windows. Now with the grey columns, the red bricks look even weirder for me. I just made it now like I would like it and uploaded the file. The windows are now added a bit quick and dirty... Maybe you can do something with it.
By the way with windows now my script also fails. :/

Here a picture:
![bathchanges](https://user-images.githubusercontent.com/6216898/27303294-a669be40-553a-11e7-94e9-36d6798f4c5f.png)

**Comment by LinuxDonald** [comment]
Good work :-) I like it

**Comment by AndyMender** [comment]
I really like the grey-yellow walls and I feel the windows look alright :). Perhaps the remaining doorway could get a similar treatment? Other than that, it's a great improvement over the initial model already.

**Comment by LinuxDonald** [comment]
Its already done.
