### ISSUE TITLE
2017.2 crashes in AI code when player/ship name contains non-ascii characters

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2699]
I have become an mail about an crash on the 2017.2 release version on Windows 10:

```
Traceback (most recent call last):
  File "run_uh.py", line 380, in <module>
    main()
  File "run_uh.py", line 190, in main
    ret = horizons.main.start(options)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 247, in start
    horizons.globals.fife.run()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 291, in loop
    f()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 113, in check_tick
    f(self.tick_next_id)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 96, in tick
    callback.callback()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 332, in tick_long
    self.strategy_manager.tick()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\strategy\strategymanager.py", line 334, in tick
    self.handle_strategy()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\strategy\strategymanager.py", line 319, in handle_strategy
    mission = self.owner.behavior_manager.request_strategy(**environment)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\behavior\__init__.py", line 88, in request_strategy
    return self.request_behavior(type, strategy_name, self.profile.strategies, **environment)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\behavior\__init__.py", line 82, in request_behavior
    return getattr(final_action, action_name)(**environment)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\behavior\behaviorcomponents.py", line 617, in neutral_player
    self.handle_diplomacy(self.parameters_neutral, **environment)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\behavior\behaviorcomponents.py", line 509, in handle_diplomacy
    format(self.owner.name, player.name, balance, relationship_score, action))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 15: ordinal not in range(128)
```

I created an branch from the 2017.2 release commit. Please fix the issue on this branch to.
Dont forget you need last stable fife and fifechan for it and python2.

@AndyMender @squiddy

**Comment by squiddy** [comment]
This looks like the same issue as #2130

**Comment by squiddy** [comment]
Also, just from a quick look at all the `self.log.debug` in `horizons/ai/aiplayer/behavior/behaviorcomponents.py` alone I'm pretty sure this will break everywhere, granted you choose to use non-ascii characters in the player's or ship's name.

**Comment by squiddy** [comment]
> I created an branch from the 2017.2 release commit.

I don't think there is any need for that, we do have tags for that. https://github.com/unknown-horizons/unknown-horizons/tree/2017.2

**Comment by AndyMender** [comment]
How do we approach this then? Do we use a decoder that can handle non-ascii characters or print a warning (or pop-up widget?) that non-ascii characters are not allowed? :)

**Comment by squiddy** [comment]
I think it probably is the same fix as for #2130 which I linked: https://github.com/unknown-horizons/unknown-horizons/commit/f96b802b40e7ef293ae6ca0eaf7a36b33de3101b

**Comment by squiddy** [comment]
Honestly thought, I'd rather concentrate on getting **2017.3** out. With python3's unicode by default, problems like this shouldn't happen.

**Comment by LinuxDonald** [comment]
Version 2017.3 is planned for the end of the year. Fife the same.

**Comment by squiddy** [comment]
Do we really want to wait so long? We've completed a major change, the migration to python 3. The sooner we get feedback, the better, right?

**Comment by squiddy** [comment]
Sure, we can fix this single bug. But I don't think it's worth the time to check the whole codebase for more issues like that.

**Comment by LinuxDonald** [comment]
The Problem is that we dont have big changes. Python 3 Port is an big change but its not an big change for the gamer. The Main Problem is still the broken multiplayer for years now :(
And helios2k is not avaliable at the moment. He wanted todo some work on fife. and jakock too (he want port fife from tinyxml to pugixml)

**Comment by LinuxDonald** [comment]
I will talk with the Bug report user. To workaround this Bug. I open an new ticket for new release discuss.

**Comment by AndyMender** [comment]
I agree with squiddy. Except for the multiplayer, which doesn't work yet anyway, most of the stuff is in a good enough condition to push for 2017.3. If the unicode issue is gone with Py3, fixing it explicitly for Py2 across the entirety of the codebase might not be a good idea.

**Comment by LinuxDonald** [comment]
I cant do an release again with nothing new. We have only codebase changes. I listen only from other that we dont have anything new in our releases only small changes for years now.
I get feedback from players. And they all say they love our game. And they will be happy to see an new version. But are they happy to see an release with nothing new related to an gamer?
When you guys want i can make an new release after Sommer. I must talk first with helios2k about new fife/fifechan release. When MP is still broken than we need to disable it for release.

**Comment by AndyMender** [comment]
Well, we're coders so what changes mostly is the codebase. I started working in Blender again so maybe I'll be able to push in some buildings, but apart from me there is only Jana in the "content department". Perhaps we could advertise the project a bit more?

Still, that's for a separate issue, I believe.

**Comment by LinuxDonald** [comment]
We dont need new content we have enough. We have alot work that coders only can do. For example ship fight. We have already cannon balls grafics. We have alot issuse with features that needs coders to get done.

**Comment by AndyMender** [comment]
@LinuxDonald can be closed as "will be fixed in the next release" or should we leave it open still?

**Comment by LinuxDonald** [comment]
Maybe squidds will do an backport.
