### ISSUE TITLE
Can't create atlas files when using unknown-horizons-git from AUR

### ISSUE THREAD

**Issue by a123qwertz567** [unknown-horizons/unknown-horizons#2716]
**Edit (squiddy):** Was `ModuleNotFoundError: No module named 'run_uh'`

When I start the game to main menu I get this error. I have serious perfomance hits and lags in the scenario, too. The lags appear when I have about 200-250 population and half of the island full with production buildings.

```manjaro@> unknown-horizons 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/horizons/engine/generate_atlases.py", line 64, in <module>
    from run_uh import init_environment # isort:skip
ModuleNotFoundError: No module named 'run_uh'
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
^C
Oh my god! They killed UH. 
You bastards!
AL lib: (EE) alc_cleanup: 1 device not closed
```
Last part is probaly from me killing the program in the terminal :)

My setup:

- Installed git version via AUR
- Linux manjaro.network 4.7.10-1-MANJARO #1 SMP PREEMPT Sat Oct 22 19:15:11 UTC 2016 x86_64 GNU/Linux
- Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
- 12 GB RAM
- AMD RX 480 with xf86-video-amdgpu 1.3.0-1

**Comment by a123qwertz567** [comment]
The thing is, I cant find any reference in the repo to this module...can I install it by hand? Where should it me included?

**Comment by LinuxDonald** [comment]
Are you using fifechan-git/fife-git/unknown-horizons-git packages? With lastest changes?

**Comment by a123qwertz567** [comment]
Quick answer: I installed this with `yaourt` from AUR. I will do some digging.

**Comment by squiddy** [comment]
> The thing is, I cant find any reference in the repo to this module...can I install it by hand? Where should it me included?

That file is contained in the root directory of this repo, `run_uh.py`. The thing is, according to it's content, the main code under `horizons` can be somewhere else in the filesystem than the launcher. Which is fine, because in `run_uh.py` we're trying to figure out where the rest of the code is.

However, once we're in the horizons code, we can't possible figure out where run_uh is..

We should move more code into `horizons`, that makes the code size of `run_uh` smaller and should avoid such problems.

**Comment by a123qwertz567** [comment]
Can anyone say something to this part of my post?
> I have serious perfomance hits and lags in the scenario, too. The lags appear when I have about 200-250 population and half of the island full with production buildings.

The game gets really unplayable. Is this normal or just my setup?

**Comment by LinuxDonald** [comment]
For testing I would need your savegame that slow down the game.

**Comment by squiddy** [comment]
@a123qwertz567 If you could re-install that package and try again, I just pushed a change that should fix the error you're seeing. If all is well, atlases should then be generated on your system, helping with performance.

**Comment by a123qwertz567** [comment]
@LinuxDonald I will first try squiddys suggestion maybe this avoids some work for you

@squiddy with a reinstall I got 3 new dependencies:
`Packages (3) python2-olefile-0.43-2  python2-pillow-4.1.1-1  python2-yaml-3.12-2`
But the simple reinstall `yaourt -S unknown-horizons-git` gave a dependency cycle between `fife-git` and `fifechan-git` . I had to perform a complete uninstall and install.

Finally you were right the message disapeared. But a new one came up:

```
manjaro@> unknown-horizons 
Recreating all atlases
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/horizons/engine/generate_atlases.py", line 428, in <module>
    generator.recreate()
  File "/usr/lib/python3.6/site-packages/horizons/engine/generate_atlases.py", line 266, in recreate
    self.save()
  File "/usr/lib/python3.6/site-packages/horizons/engine/generate_atlases.py", line 216, in save
    with open(PATHS.ATLAS_DB_PATH, 'w') as atlas_db_file:
PermissionError: [Errno 13] Permission denied: 'content/atlas.sql'
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```
Despite this fact the game was fine for the 10 minutes a played, some mini-lags (I think the autosave?!) but thegame was playable. I will do some more testing soon.

Would it maybe be better if I build directly from git? Shouldn't make a difference...?

**Comment by squiddy** [comment]
> Would it maybe be better if I build directly from git? Shouldn't make a difference...?

If you would *run* directly from git it should work. That is:

```
$ git clone git://github.com/unknown-horizons/unknown-horizons.git
$ cd unknown-horizons
$ python run_uh.py
```

This is a weird situation: Typically users will install a regular release, and the atlas files will be included already. For developers, running from git directly will create the atlas files.

Here we're trying to run a development version of UH that has been installed systemwide. And I'm guessing it is now attempting to write the generated atlas files into wherever the `content` dir is, probably `/usr/share/something`, giving us the PermissionError.

**Comment by a123qwertz567** [comment]
Runs without the error. I will play a little bit to check the performance.

```
manjaro@> python run_uh.py 
Recreating all atlases
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Thank you for using Unknown Horizons!
manjaro@> 
```
Maybe the AUR package can create the atlases during the installation when the installer has permissions to write on `/usr/share/whatever`.

**Comment by squiddy** [comment]
Glad it works now.

> Maybe the AUR package can create the atlases during the installation when the installer has permissions to write on /usr/share/whatever.

Sounds like a good idea. Can we do that @LinuxDonald?

**Comment by LinuxDonald** [comment]
I will take an look at it. But I think it should work :-)

**Comment by AndyMender** [comment]
@LinuxDonald still an issue or was it fixed?

**Comment by LinuxDonald** [comment]
not yet fixed

**Comment by LinuxDonald** [comment]
Completely forgotten this...

**Comment by jmdejong** [comment]
I think a simple `python3 horizons/engine/generate_atlases.py 2048` could solve this.
Should it be fixed in PKGBUILD or in setup.py?

**Comment by LinuxDonald** [comment]
I think in setup.py it would be better than all Linux distros could use it.

**Comment by LinuxDonald** [comment]
Should be fixed now.

**Comment by o01eg** [comment]
I get error while installing via setup.py: 
```
intltool-merge -d po/uh/ content/packages/unknown-horizons.desktop.in build/share/applications/unknown-horizons.desktop
Merging translations into build/share/applications/unknown-horizons.desktop.
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    cmdclass=cmdclass)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 230, in run
    generate_atlases(2048)
NameError: name 'generate_atlases' is not defined
```

**Comment by jmdejong** [comment]
Good find. I hadn't finished testing yet.
I just pushed a fix.

**Comment by o01eg** [comment]
Next error:

```
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    cmdclass=cmdclass)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 230, in run
    self.generate_atlases(2048)
  File "setup.py", line 151, in generate_atlases
    process = subprocess.Popen(args)
NameError: name 'subprocess' is not defined
```

**Comment by jmdejong** [comment]
pushed a fix again

**Comment by o01eg** [comment]
Thanks, it works now.

**Comment by LinuxDonald** [comment]
Thank you for testing :-)

**Comment by jmdejong** [comment]
By the way, this atlas generation now happens anytime someone is running setup.py
We should make sure that releases that include the atlases do not run setup.py, or we should make an option in setup.py

**Comment by LinuxDonald** [comment]
We don't need to add atlas to release version. Now package maintainer could run setup.py. I will add that into the release notes for package maintainer.

**Comment by jubalh** [comment]
@jmdejong which was your pushed fix? a reference to the commit would be helpful

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/eae6e39a800590e480301289a061a6c57c5ebbfc
https://github.com/unknown-horizons/unknown-horizons/commit/3bb44e64d1bc381889bc938e37d643f1786c214e
https://github.com/unknown-horizons/unknown-horizons/commit/2a964d5575aa3dc4a803b5c4e7be39a1f56f60a4

**Comment by jubalh** [comment]
Thanks @LinuxDonald. It seems all those commits are part of 2019.1. So it's strange that https://github.com/unknown-horizons/unknown-horizons/issues/2892 is affected by the same issue.

**Comment by LinuxDonald** [comment]
#2892 is an packing problem of debian its not complete the same problem.
