### ISSUE TITLE
Change min python3 version from 3.4 to 3.5?

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2718]
We could now set python3 3.5 to min requirement because Debian 9 have now on default 3.5. And we could use than too 3.5 features.

**Comment by AndyMender** [comment]
I think it's a safe move since most of us use Python 3.5 or even Python 3.6 anyhow.

**Comment by MasterofJOKers** [comment]
"most of us" means "most of our users", right? How do we know that?

**Comment by AndyMender** [comment]
By "most of us", I meant most of us developers. Not sure about the users here.

**Comment by LinuxDonald** [comment]
Debian should be the base. And Debian 9 is out and should be the new base. We can't wait years for an python3 version Upgrade. The next Debian Release will take again years that we can switch to 3.6

**Comment by squiddy** [comment]
Let's start by listing the 3.5 features we so desperately need to warrant dropping support for 3.4. ;)

**Comment by LinuxDonald** [comment]
https://docs.python.org/3/whatsnew/3.5.html the list is very long :P

**Comment by squiddy** [comment]
That's not what I was asking for though. :) Really, what's the motiviation behind this issue? We've just completed the switch to python 3.4. Python 3.5 was released already when we discussed the version we're planning to support.

**Comment by squiddy** [comment]
I mean, does it help with the release of 2017.3? Otherwise I don't think this is worth the time right now.

**Comment by LinuxDonald** [comment]
At the time we have discssed. Debian 9 was not released.
We dont must switch the python version instand but we should plan it from now that we can use someting from py3.5

**Comment by squiddy** [comment]
Sure, we can talk about things. I just doubt we'll get to ship more features / more content any quicker by switching to Python 3.5 right now.

**Comment by MasterofJOKers** [comment]
Debian 9 was released today. I don't think we have to switch right away, since users take their time to upgrade. Now oldstable (jessie) is supported for quite some time, too: https://wiki.debian.org/LTS

**Comment by AndyMender** [comment]
I see it that way - if we incur a requirement on the players, they will have to update to either Debian 9 or whatever other distribution that defaults to Python 3.5 or higher. Unless we really need features from Python 3.5 that would make our work easier or the code more efficient/readable, I would not bump the in-code requirement to Python 3.5. Let's leave it at 3.4 or higher and use whichever version we prefer that's still backwards compatible with 3.4.

**Comment by AndyMender** [comment]
@LinuxDonald, do we get some sort of consensus on this? I looked around a bit and at least openSUSE Leap 42.2 still uses Python 3.4.x and I'm sure they will keep on using it for longer.

**Comment by LinuxDonald** [comment]
Ah okay.
