### ISSUE TITLE
Don't offer route configuration with only one settlement

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2721]
If the player only has one settlement, it is still possible to open the route configuration menu, only to find out that one has to select at least two settlements.

Shouldn't we just disable this feature until two settlements were build?

**Comment by AndyMender** [comment]
As in, provide a pop-up widget informing the player that 2+ settlements are required to configure a route, at the time the traderoute config menu is being generated?

**Comment by MasterofJOKers** [comment]
One could grey-out the "traderoute menu icon" and provide information why in a mouseover. No need to let the user think, he/she can click it.

**Comment by AndyMender** [comment]
I think that's an even better solution, true :).

**Comment by squiddy** [comment]
Yeah, greying it out was what I was thinking of as well.

**Comment by yhoyhoj** [comment]
I'd like to try this.
I have already found the files to modify but I am not sure of the desired behaviour.  

Considering the player can also trade with other players or IA, it should check the total number of warehouses on the map. Should it also check if the warehouses are allowed in a route (ie. owned by an ally) ?
And given that there are multiple reasons to grey that button out, would a tooltip saying something like : "There are no available destination for a trade route yet" be enough ?

**Comment by MasterofJOKers** [comment]
Yes, please also check for allied warehouses.
Yes, that tooltip-text should be enough.
