### ISSUE TITLE
Link to build instructions on page "Get involved" is dead

### ISSUE THREAD

**Issue by krichter722** [unknown-horizons/unknown-horizons#2725]
The link to "install from git" instructions on http://unknown-horizons.org/get-involved/ is dead. There's no (easy) way to get to the build instructions from the home page.

Workaround: build instructions are linked in `README.md`.

**Comment by LinuxDonald** [comment]
Fixed with: https://github.com/unknown-horizons/unknown-horizons.github.io/commit/510ca4808b7a5e1f2a59d69be9d73fa14d77abe0

And thank you for your report 👍
