### ISSUE TITLE
Offset problem

### ISSUE THREAD

**Issue by janexx** [unknown-horizons/unknown-horizons#2728]
I added the public bath in branch "public_bath". The building can't be placed properly. For example it can be placed on streets and on other buildings. 
Screenshot: 
![bath](https://user-images.githubusercontent.com/6216898/27763027-6c508748-5e7c-11e7-8fda-58d3e4067f68.png)
@AndyMender Can you maybe have a look on it if it's an offset problem again?

**Comment by AndyMender** [comment]
@janexx, just to make sure, was the building added to the game as 2x2? I fixed all offsets for 2x2 buildings already so it might be coming from someplace else :(.

**Comment by janexx** [comment]
@AndyMender Yes, its 2x2 (128x128 Pixel). I fixed it now (commit e36a458501bb9ce2b39e481a9a3b76b43edb9cff) . The camera was too high and so there was too much empty space at the lower side of the graphics. By the way I made the ground plate a bit wider so that the building fills out the whole square.
