### ISSUE TITLE
[support] game crash on startup with fontdef deprecatedException

### ISSUE THREAD

**Issue by icyvapor** [unknown-horizons/unknown-horizons#2731]
I've just installed the required dependencies .. at least as far as I understand :)

when I tried starting up the game, got deprecatedException about 'fontdef' : 

Traceback (most recent call last):
  File "./run_uh.py", line 380, in <module>
    main()
  File "./run_uh.py", line 190, in main
    ret = horizons.main.start(options)
    ...
  File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/fonts.py", line 101, in loadFonts
    for font in Font.loadFromFile(filename):
  File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/fonts.py", line 80, in loadFromFile
    raise DeprecatedException(str(filename)+" is not a xml file. Fontdef files are deprecated.")
fife.extensions.pychan.exceptions.DeprecatedException: content/fonts/libertine.fontdef is not a xml file. Fontdef files are deprecated.
AL lib: (EE) alc_cleanup: 1 device not closed

How should I fix this? 

Thanks a lot!

**Comment by LinuxDonald** [comment]
What version of fife and uh do you use?

**Comment by icyvapor** [comment]
Fife is v0.4.1.
Not sure where the version label is in uh, but the tar file name has '2017.2' in it

Thanks a lot!

**Comment by LinuxDonald** [comment]
What is the fifechan version? Have you compiled your self or rebuilded package?

**Comment by icyvapor** [comment]
Fifechan is  v0.1.4

I git checkout both fife and fifengine and built them locally.

**Comment by LinuxDonald** [comment]
Try fifechan git master version and recompile fife

**Comment by AndyMender** [comment]
@icyvapor, just so you know, we no longer support Python 2.7. Now it's only the Python 3.x line, starting from Python 3.4.

**Comment by LinuxDonald** [comment]
Mender27 he is using last stable version that is based on python2.

**Comment by AndyMender** [comment]
Ah, my apologies then.

**Comment by icyvapor** [comment]
Still had no luck. Both fifechan and fife were up-to-date on master. 
Although when I was building fifengine, I didn't specify about Python version, so it was building for 2.7.

I'm thinking I should probably start trying to build for python3, and sounds like it's the future anyways.

And another thing I saw when building from a git-checkout was an ImportError about not finding 'fife' module. Not boding well for me to contribute :(

**Comment by LinuxDonald** [comment]
When you take fife master you need uh master too. And compiled fife with python3 support. Info are on the fife docs too

**Comment by icyvapor** [comment]
Finally got it! 
After rebuilding uh with python3 option, and then rebuilding fifechan. Got ImportError on 'future'. Tried 'pip install future' but that only installed for python 2.7. Searched to found I need pip3 for python3. 

So glad to be looking at the splash menu screen. \O/
