### ISSUE TITLE
self._finalSetting['SDLRemoveFakeAlpha'] is not a bool

### ISSUE THREAD

**Issue by MarkusHackspacher** [unknown-horizons/unknown-horizons#2736]
I tested it with debian testing and python 3.5. And have the newest fifengine build.
The orginal codeline is: `self.engine_settings.setSDLRemoveFakeAlpha(self._finalSetting['SDLRemoveFakeAlpha'])`
It works with: `self.engine_settings.setSDLRemoveFakeAlpha(True)`
but not with `self.engine_settings.setSDLRemoveFakeAlpha(1)`

And `print(self._finalSetting['SDLRemoveFakeAlpha'])`give a 1 back and should give back a True.

My fault:
```
$ python3 run_uh.py
1
Traceback (most recent call last):
  File "run_uh.py", line 376, in <module>
    main()
  File "run_uh.py", line 127, in main
    ret = horizons.main.start(options)
  File "unknown-horizons/horizons/main.py", line 110, in start
    horizons.globals.fife = Fife()
  File "unknown-horizons/horizons/engine/engine.py", line 51, in __init__
    self.load_settings()
  File "unknown-horizons/horizons/engine/engine.py", line 74, in load_settings
    self.engine_settings.setSDLRemoveFakeAlpha(self._finalSetting['SDLRemoveFakeAlpha'])
TypeError: in method 'EngineSettings_setSDLRemoveFakeAlpha', argument 2 of type 'bool'
```

**Comment by AndyMender** [comment]
I'll have a look at it.

**Comment by LinuxDonald** [comment]
@MarkusHackspacher it should be an problem on your local settings.xml. Our template set: https://github.com/unknown-horizons/unknown-horizons/blob/2bac2fa8a3d50a5adf9bfd9ecf679f8688788437/content/settings-template.xml#L10

**Comment by MarkusHackspacher** [comment]
@LinuxDonald I have not a local settings.xml:
```
unknown-horizons$ grep SDLRemoveFakeAlpha * -r 
content/settings-template.xml:		<Setting name="SDLRemoveFakeAlpha" type="bool"> True </Setting>
Übereinstimmungen in Binärdatei horizons/engine/__pycache__/engine.cpython-35.pyc
horizons/engine/engine.py:		print(self._finalSetting['SDLRemoveFakeAlpha'])
horizons/engine/engine.py:		self.engine_settings.setSDLRemoveFakeAlpha(True)# self._finalSetting['SDLRemoveFakeAlpha'])
```

**Comment by LinuxDonald** [comment]
Your local settings.xml should be in your home folder under .unknown-horizons

**Comment by MarkusHackspacher** [comment]
Ok, I found the local setting, I delete the old file. And it works.
