### ISSUE TITLE
arabic lang

### ISSUE THREAD

**Issue by Omaranwa** [unknown-horizons/unknown-horizons#2742]
is this game support this lang?

**Comment by LinuxDonald** [comment]
On the weekend I will look into this. I have seen your weblate request.

**Comment by Omaranwa** [comment]
ok when you do write here.
thanks

**Comment by LinuxDonald** [comment]
Arabic = اَللُّغَةُ اَلْعَرَبِيَّة in your language?

**Comment by LinuxDonald** [comment]
Added ar files only for now for weblate https://github.com/unknown-horizons/unknown-horizons/commit/6ed499af4679484e575fb577cfaea6cbd85bced8

**Comment by LinuxDonald** [comment]
https://github.com/unknown-horizons/unknown-horizons/commit/6e26cb20a5c3a2f30563ddd31acc60722f57493f

Added into the game.

**Comment by Omaranwa** [comment]
> Arabic = اَللُّغَةُ اَلْعَرَبِيَّة in your language?
yes thes what they mean
 i will begin translete it soon

**Comment by LinuxDonald** [comment]
its still not avaiable on weblate i will post here if weblate has updated it. Then you can start :)

**Comment by Omaranwa** [comment]
ok waiting>>>>>

**Comment by LinuxDonald** [comment]
It will take longer time. Last Night Weblate had mantaince and now they have server problems.....

**Comment by Omaranwa** [comment]
hahaha bad luck 
still waiting

**Comment by LinuxDonald** [comment]
Its now in weblate have fun on translation and thank you for your help :)

**Comment by Omaranwa** [comment]
ok will do :)
