### ISSUE TITLE
Help with unit testing.. 

### ISSUE THREAD

**Issue by icyvapor** [unknown-horizons/unknown-horizons#2746]
Where is run_tests.py ? 

I'm trying to do some unit testing before opening a pull request.. 
The info on the page about testing seems to be a bit out-dated?

Thanks!

**Comment by LinuxDonald** [comment]
On travis we use this command: https://github.com/unknown-horizons/unknown-horizons/blob/master/.travis.yml#L31

When you open an pull request travis run the tests too.
