### ISSUE TITLE
Follow XDG basedir specification

### ISSUE THREAD

**Issue by Lucki** [unknown-horizons/unknown-horizons#2749]
Right now a new folder for configurations and userdata is created in `$HOME/.unknown-horizons`.
To be more flexible it would be nice to implement the [XDG Base Directory Specification][1].

> `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.
> `$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.
> `$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used.

An easy explanation can be found in the [gnome wiki][2].

This would result in the following folders:

- `$XDG_CONFIG_HOME/unknown-horizons/<SETTINGS.XML>` defaulting to `$HOME/.config/unknown-horizons/<SETTINGS.XML>` when `$XDG_CONFIG_HOME` is not set or empty.
- `$XDG_DATA_HOME/unknown-horizons/<LOG|MAPS|SAVE|SCREENSHOTS>` defaulting to `$HOME/.local/share/unknown-horizons/<LOG|MAPS|SAVE|SCREENSHOTS>` when `$XDG_DATA_HOME` is not set or empty.
- `$XDG_CACHE_HOME/unknown-horizons/<YAMLDATA.CACHE>` defaulting to `$HOME/.cache/unknown-horizons/<YAMLDATA.CACHE>` when `$XDG_CACHE_HOME` is not set or empty.

Advantages are:
- No predefined paths. The user can decide where his or her data is located.
- No cluttered home directory. Some selectors will automatically show dotfiles, finding the files you want will be easier.
- A shared storage location for data. Application data does not have to be searched for, as these are no longer located in different places. This also benefits a backup.
- Resetting the settings and keeping the application data at the same time becomes easier, as there is a clear separation.

[1]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
[2]: https://wiki.gnome.org/Initiatives/GnomeGoals/XDGConfigFolders#Guidelines

**Comment by LinuxDonald** [comment]
We hope we can do this for the next release.

**Comment by jmdejong** [comment]
Seems easy enough to fix this, but what should the default folders be on windows?
Something like the suggestions from this [stackoverflow question](https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows)?

Also, this will make users unable to find back earlier saves.
Should there be some kind of migration check?
If these folders are empty but the $HOME/.unknown-horizons directory exists, should it automatically move/copy user data?

**Comment by AndyMender** [comment]
"Yes" to both of the last questions. If you want to use XDG, "$HOME/.unknown-horizons" should be a fallback directory with a notice to the user that it will be deprecated in the next release (whenever that is...).

**Comment by jmdejong** [comment]
@AndyMender What kind of notice do you mean? A popup when starting UH? A readme.txt file in "$HOME/.unknown-horizons"?

**Comment by AndyMender** [comment]
Either a small Tk popup window or a `print()` to the terminal or both.

**Comment by jmdejong** [comment]
How about using symlinks instead for older installs? Something like `ln -S $HOME/.unknown-horizons $XDG_DATA_HOME/unknown-horizons/` (and similar for config)
I believe we don't need a message for cache migration by the way.

**Comment by LinuxDonald** [comment]
We can put an note into the Changelog. That UH uses than an new home folder.
