### ISSUE TITLE
Left/right scrolling with touchpad in main game mode crashes UH

### ISSUE THREAD

**Issue by frsfnrrg** [unknown-horizons/unknown-horizons#2753]
On Arch Linux, having just installed `unknown-horizons-git`.

When I left or right scroll using the touchpad (`xinput test #` button presses 6 or 7),
if I am in the main menu or the New-Game Single Player screen, nothing happens
as soon as a game loads, L/R scrolling immediately exits the program with error

    Traceback (most recent call last):
    RuntimeError: Caught a director exception

    Unknown Horizons exited uncleanly via SIGINT
    AL lib: (EE) alc_cleanup: 1 device not closed

If I disable touchpad L/R scrolling, via `xinput set-button-map ## 1 2 3 4 5 0 0`
where `##` corresponds to the touchpad, the crash does not occur.

**Comment by LinuxDonald** [comment]
Is this the only output from the crash?
