### ISSUE TITLE
update check crashes game

### ISSUE THREAD

**Issue by Ismoez** [unknown-horizons/unknown-horizons#2754]
If i open the game it crashes after a couple of seconds:

The problem is in unknown-horizons/horizons/util/checkupdates.py

line 93:
`text = T("There is a more recent release of Unknown Horizons ({new_version}) "
				 "than the one you are currently using ({old_version}).").format(
				new_version=info.version,
				old_version=VERSION.RELEASE_VERSION)`

the content of info.version is a html 
i uploaded it as a html info_version.html here the link:
[http://ranbu.org/unknown_horizons/info_version.html](url)

as a workaround im just setting a random string for new_version:
`text = T("There is a more recent release of Unknown Horizons ({new_version}) "
				 "than the one you are currently using ({old_version}).").format(
				new_version="a",
				old_version=VERSION.RELEASE_VERSION)`

**Comment by jmdejong** [comment]
The update check code has been changed in commit 76776357cb422392838fa824835c0d72084e9f10
This should be fixed in the current development version (the current code on github

**Comment by LinuxDonald** [comment]
yeah thats an bug of the last release version. We will release an new fixed version this Summer.
