### ISSUE TITLE
Main Menu Stuck On Being Oversized

### ISSUE THREAD

**Issue by EldonTheNoble** [unknown-horizons/unknown-horizons#2756]
Hey Guys, so I haven't really had a chance to play the game yet. I don't know how many people are like this but when I first launch a game the first place I go to is settings. I was working with the aspect ratio for the screen output and when I chose one it made the game screen super sized and zoomed in and to where I could not select anything at all. I did not think that was a big deal so I completely uninstalled it removing everything associated with it and reinstalled it, and as soon as I launched it, it was stuck on the same screen. I have tried repeating the process multiple times making sure I delete everything and I have restarted my computer and nothing... I am hoping for some help because I am really looking forward to trying this game. Thank You

**Comment by LinuxDonald** [comment]
Have you maybe an Screenshot of the error?

**Comment by LinuxDonald** [comment]
Closed because no feedback.
