### ISSUE TITLE
Crash on any attemption to "Build settlement".

### ISSUE THREAD

**Issue by stadnichenko-a-s** [unknown-horizons/unknown-horizons#2760]
Crash on any attempt to "Build settlement" and other actions at game start in Linux (Mint 18.1 4.4.8-79-generic amd64). Game receive from Ubuntu repository, not downloaded from site.

Output : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/horizons/engine/generate_atlases.py", line 64, in <module>
    from run_uh import init_environment
ImportError: No module named run_uh
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.

*** Error in `/usr/bin/python': malloc(): memory corruption: 0x000000000695ce90 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f36771427e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f367714d13e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f367714f184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f367437be78]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm+0x7d)[0x7f367440d87d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE8overflowEi+0xe5)[0x7f3674401cd5]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt15basic_streambufIcSt11char_traitsIcEE6xsputnEPKcl+0x89)[0x7f367440be79]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l+0x1a6)[0x7f36743fcec6]
/usr/lib/python2.7/dist-packages/fife/_fife.so(_ZN4FIFE8Instance6followERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_5RouteEd+0x664)[0x7f36747b0414]
/usr/lib/python2.7/dist-packages/fife/_fife.so(+0x360b24)[0x7f36749d0b24]
/usr/bin/python(PyEval_EvalFrameEx+0x745e)[0x4cb45e]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x4c2765]
/usr/bin/python(PyEval_EvalFrameEx+0x68d1)[0x4ca8d1]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x4c2765]
/usr/bin/python(PyEval_EvalFrameEx+0x6099)[0x4ca099]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x4c2765]
/usr/bin/python(PyEval_EvalFrameEx+0x6099)[0x4ca099]
/usr/bin/python(PyEval_EvalFrameEx+0x5d8f)[0x4c9d8f]
/usr/bin/python(PyEval_EvalFrameEx+0x5d8f)[0x4c9d8f]
/usr/bin/python(PyEval_EvalFrameEx+0x5d8f)[0x4c9d8f]
/usr/bin/python(PyEval_EvalFrameEx+0x5d8f)[0x4c9d8f]
/usr/bin/python(PyEval_EvalFrameEx+0x5d8f)[0x4c9d8f]
/usr/bin/python(PyEval_EvalFrameEx+0x5d8f)[0x4c9d8f]
/usr/bin/python(PyEval_EvalCodeEx+0x255)[0x4c2765]
/usr/bin/python(PyEval_EvalCode+0x19)[0x4c2509]
/usr/bin/python[0x4f1def]
/usr/bin/python(PyRun_FileExFlags+0x82)[0x4ec652]
/usr/bin/python(PyRun_SimpleFileExFlags+0x191)[0x4eae31]
/usr/bin/python(Py_Main+0x68a)[0x49e14a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f36770eb830]
/usr/bin/python(_start+0x29)[0x49d9d9]
======= Memory map: ========
00400000-006ea000 r-xp 00000000 08:03 7603605                            /usr/bin/python2.7
008e9000-008eb000 r--p 002e9000 08:03 7603605                            /usr/bin/python2.7
008eb000-00962000 rw-p 002eb000 08:03 7603605                            /usr/bin/python2.7
00962000-00985000 rw-p 00000000 00:00 0 
018de000-09be2000 rw-p 00000000 00:00 0                                  [heap]
7f3648000000-7f3648021000 rw-p 00000000 00:00 0 
7f3648021000-7f364c000000 ---p 00000000 00:00 0 
7f364dcd9000-7f364dcda000 rw-p 00000000 00:00 0 
7f364dcda000-7f364dcea000 rw-s 00000000 00:05 1604201                    /drm mm object (deleted)
7f364dcea000-7f364dcfa000 rw-s 00000000 00:05 1604200                    /drm mm object (deleted)
7f364dcfa000-7f364dd22000 rw-s 00000000 00:05 1606497                    /drm mm object (deleted)
7f364dd22000-7f364dd4a000 rw-s 00000000 00:05 1606496                    /drm mm object (deleted)
7f364dd4a000-7f364dd4b000 rw-s 00000000 00:05 1606495                    /drm mm object (deleted)
7f364dd4b000-7f364dd5b000 rw-s 00000000 00:05 1606494                    /drm mm object (deleted)
7f364dd5b000-7f364dd6b000 rw-s 00000000 00:05 1604934                    /drm mm object (deleted)
7f364dd6b000-7f364dd73000 rw-s 00000000 00:05 1604199                    /drm mm object (deleted)
7f364dd73000-7f364dd81000 rw-s 00000000 00:05 1604198                    /drm mm object (deleted)
7f364dd81000-7f364ddc1000 rw-p 00000000 00:00 0 
7f364ddc1000-7f364ddd1000 rw-s 00000000 00:05 1606493                    /drm mm object (deleted)
7f364ddd1000-7f364dde1000 rw-s 00000000 00:05 1606492                    /drm mm object (deleted)
7f364dde1000-7f364ddf1000 rw-s 00000000 00:05 1606491                    /drm mm object (deleted)
7f364ddf1000-7f364de01000 rw-s 00000000 00:05 1606490                    /drm mm object (deleted)
7f364de01000-7f364de04000 rw-s 00000000 00:05 1604197                    /drm mm object (deleted)
7f364de04000-7f364de14000 rw-s 00000000 00:05 1604196                    /drm mm object (deleted)
7f364de14000-7f364de24000 rw-s 00000000 00:05 1604195                    /drm mm object (deleted)
7f364de24000-7f364de34000 rw-s 00000000 00:05 1604194                    /drm mm object (deleted)
7f364de34000-7f364de44000 rw-s 00000000 00:05 1606489                    /drm mm object (deleted)
7f364de44000-7f364de54000 rw-s 00000000 00:05 1603277                    /drm mm object (deleted)
7f364de54000-7f364de64000 rw-s 00000000 00:05 1603276                    /drm mm object (deleted)
7f364de64000-7f364de74000 rw-s 00000000 00:05 1603275                    /drm mm object (deleted)
7f364de74000-7f364de84000 rw-s 00000000 00:05 1603889                    /drm mm object (deleted)
7f364de84000-7f364de94000 rw-s 00000000 00:05 1603888                    /drm mm object (deleted)
7f364de94000-7f364dea4000 rw-s 00000000 00:05 1603887                    /drm mm object (deleted)
7f364dea4000-7f364deb4000 rw-s 00000000 00:05 1603274                    /drm mm object (deleted)
7f364deb4000-7f364dec4000 rw-s 00000000 00:05 1603886                    /drm mm object (deleted)
7f364dec4000-7f364dec5000 rw-s 00000000 00:05 1603885                    /drm mm object (deleted)
7f364dec5000-7f364dec7000 rw-s 00000000 00:05 1603884                    /drm mm object (deleted)
7f364dec7000-7f364decf000 rw-s 00000000 00:05 1603883                    /drm mm object (deleted)
7f364decf000-7f364def7000 rw-s 00000000 00:05 1603882                    /drm mm object (deleted)
7f364def7000-7f364df17000 rw-s 00000000 00:05 1603881                    /drm mm object (deleted)
7f364df17000-7f364df3f000 rw-s 00000000 00:05 1603880                    /drm mm object (deleted)
7f364df3f000-7f364df40000 rw-s 00000000 00:05 1603879                    /drm mm object (deleted)
7f364df40000-7f364df4a000 rw-s 00000000 00:05 1603878                    /drm mm object (deleted)
7f364df4a000-7f364df4b000 rw-s 00000000 00:05 1603877                    /drm mm object (deleted)
7f364df4b000-7f364df4f000 rw-s 00000000 00:05 1603876                    /drm mm object (deleted)
7f364df4f000-7f364df53000 rw-s 00000000 00:05 1603875                    /drm mm object (deleted)
7f364df53000-7f364dfc3000 rw-s 00000000 00:05 1603874                    /drm mm object (deleted)
7f364dfc3000-7f364dfc4000 rw-s 00000000 00:05 1603873                    /drm mm object (deleted)
7f364dfc4000-7f364dfc6000 rw-s 00000000 00:05 1603872                    /drm mm object (deleted)
7f364dfc6000-7f364dfce000 rw-s 00000000 00:05 1603871                    /drm mm object (deleted)
7f364dfce000-7f364dfde000 rw-s 00000000 00:05 1603870                    /drm mm object (deleted)
7f364dfde000-7f364dfee000 rw-s 00000000 00:05 1603273                    /drm mm object (deleted)
7f364dfee000-7f364dffe000 rw-s 00000000 00:05 1603272                    /drm mm object (deleted)
7f364dffe000-7f364e00e000 rw-s 00000000 00:05 1603271                    /drm mm object (deleted)
7f364e00e000-7f364e01e000 rw-s 00000000 00:05 1603270                    /drm mm object (deleted)
7f364e01e000-7f364e02e000 rw-s 00000000 00:05 1606488                    /drm mm object (deleted)
7f364e02e000-7f364e03e000 rw-s 00000000 00:05 1604933                    /drm mm object (deleted)
7f364e03e000-7f364e04e000 rw-s 00000000 00:05 1603269                    /drm mm object (deleted)
7f364e04e000-7f364e05e000 rw-s 00000000 00:05 1603869                    /drm mm object (deleted)
7f364e05e000-7f364e09e000 rw-s 00000000 00:05 1603868                    /drm mm object (deleted)
7f364e09e000-7f364e0ae000 rw-s 00000000 00:05 1603268                    /drm mm object (deleted)
7f364e0ae000-7f364e0be000 rw-s 00000000 00:05 1603867                    /drm mm object (deleted)
7f364e0be000-7f364e0ce000 rw-s 00000000 00:05 1603866                    /drm mm object (deleted)
7f364e0ce000-7f364e0d2000 rw-s 00000000 00:05 1603865                    /drm mm object (deleted)
7f364e0d2000-7f364e0d4000 rw-s 00000000 00:05 1603864                    /drm mm object (deleted)
7f364e0d4000-7f364e0e4000 rw-s 00000000 00:05 1603863                    /drm mm object (deleted)
7f364e0e4000-7f364e0f4000 rw-s 00000000 00:05 1603862                    /drm mm object (deleted)
7f364e0f4000-7f364e0f5000 rw-s 00000000 00:05 1603763                    /drm mm object (deleted)
7f364e0f5000-7f364e0f9000 rw-s 00000000 00:05 1603861                    /drm mm object (deleted)
7f364e0f9000-7f364e179000 rw-p 00000000 00:00 0 
7f364e179000-7f364e17a000 rw-s 00000000 00:05 1603860                    /drm mm object (deleted)
7f364e17a000-7f364e17b000 rw-s 00000000 00:05 1603859                    /drm mm object (deleted)
7f364e17b000-7f364e17c000 rw-s 00000000 00:05 1603858                    /drm mm object (deleted)
7f364e17c000-7f364e17d000 rw-s 00000000 00:05 1603857                    /drm mm object (deleted)
7f364e17d000-7f364e17e000 rw-s 00000000 00:05 1603856                    /drm mm object (deleted)
7f364e17e000-7f364e182000 rw-s 00000000 00:05 1603855                    /drm mm object (deleted)
7f364e182000-7f364e186000 rw-s 00000000 00:05 1603854                    /drm mm object (deleted)
7f364e186000-7f364e187000 rw-s 00000000 00:05 1603853                    /drm mm object (deleted)
7f364e187000-7f364e188000 rw-s 00000000 00:05 1603852                    /drm mm object (deleted)
7f364e188000-7f364e189000 rw-s 00000000 00:05 1603851                    /drm mm object (deleted)
7f364e189000-7f364e18a000 rw-s 00000000 00:05 1603850                    /drm mm object (deleted)
7f364e18a000-7f364e18b000 rw-s 00000000 00:05 1603849                    /drm mm object (deleted)
7f364e18b000-7f364e18c000 rw-s 00000000 00:05 1603848                    /drm mm object (deleted)
7f364e18c000-7f364e1c4000 rw-s 00000000 00:05 1603847                    /drm mm object (deleted)
7f364e1c4000-7f364e1c5000 rw-s 00000000 00:05 1603846                    /drm mm object (deleted)
7f364e1c5000-7f364e1c6000 rw-s 00000000 00:05 1603845                    /drm mm object (deleted)
7f364e1c6000-7f364e1d6000 rw-s 00000000 00:05 1603844                    /drm mm object (deleted)
7f364e1d6000-7f364e1de000 rw-s 00000000 00:05 1603843                    /drm mm object (deleted)
7f364e1de000-7f364e1df000 rw-s 00000000 00:05 1603842                    /drm mm object (deleted)
7f364e1df000-7f364e1e0000 rw-s 00000000 00:05 1603841                    /drm mm object (deleted)
7f364e1e0000-7f364e1e1000 rw-s 00000000 00:05 1603840                    /drm mm object (deleted)
7f364e1e1000-7f364e1e2000 rw-s 00000000 00:05 1603839                    /drm mm object (deleted)
7f364e1e2000-7f364e1e3000 rw-s 00000000 00:05 1603838                    /drm mm object (deleted)
7f364e1e3000-7f364e1e5000 rw-s 00000000 00:05 1603837                    /drm mm object (deleted)
7f364e1e5000-7f364e1e6000 rw-s 00000000 00:05 1603836                    /drm mm object (deleted)
7f364e1e6000-7f364e1ea000 rw-s 00000000 00:05 1603835                    /drm mm object (deleted)
7f364e1ea000-7f364e1ee000 rw-s 00000000 00:05 1603834                    /drm mm object (deleted)
7f364e1ee000-7f364e1f2000 rw-s 00000000 00:05 1603833                    /drm mm object (deleted)
7f364e1f2000-7f364e1f3000 rw-s 00000000 00:05 1603832                    /drm mm object (deleted)
7f364e1f3000-7f364e1f7000 rw-s 00000000 00:05 1603831                    /drm mm object (deleted)
7f364e1f7000-7f364e1fa000 rw-s 00000000 00:05 1603830                    /drm mm object (deleted)
7f364e1fa000-7f364e1fb000 rw-s 00000000 00:05 1603829                    /drm mm object (deleted)
7f364e1fb000-7f364e213000 rw-s 00000000 00:05 1603828                    /drm mm object (deleted)
7f364e213000-7f364e223000 rw-s 00000000 00:05 1603827                    /drm mm object (deleted)
7f364e223000-7f364e233000 rw-s 00000000 00:05 1603826                    /drm mm object (deleted)
7f364e233000-7f364e237000 rw-s 00000000 00:05 1603825                    /drm mm object (deleted)
7f364e237000-7f364e23b000 rw-s 00000000 00:05 1603824                    /drm mm object (deleted)
7f364e23b000-7f364e23f000 rw-s 00000000 00:05 1603823                    /drm mm object (deleted)
7f364e23f000-7f364e243000 rw-s 00000000 00:05 1603822                    /drm mm object (deleted)
7f364e243000-7f364e24a000 rw-s 00000000 00:05 1603821                    /drm mm object (deleted)
7f364e24a000-7f364e252000 rw-s 00000000 00:05 1603820                    /drm mm object (deleted)
7f364e252000-7f364e25a000 rw-s 00000000 00:05 1603819                    /drm mm object (deleted)
7f364e25a000-7f364e26a000 rw-s 00000000 00:05 1603818                    /drm mm object (deleted)
7f364e26a000-7f364e272000 rw-s 00000000 00:05 1603817                    /drm mm object (deleted)
7f364e272000-7f364e273000 rw-s 00000000 00:05 1603816                    /drm mm object (deleted)
7f364e273000-7f364e27d000 rw-s 00000000 00:05 1603815                    /drm mm object (deleted)
7f364e27d000-7f364e27e000 rw-s 00000000 00:05 1603814                    /drm mm object (deleted)
7f364e27e000-7f364e281000 rw-s 00000000 00:05 1603813                    /drm mm object (deleted)
7f364e281000-7f364e285000 rw-s 00000000 00:05 1603812                    /drm mm object (deleted)
7f364e285000-7f364e289000 rw-s 00000000 00:05 1603811                    /drm mm object (deleted)
7f364e289000-7f364e299000 rw-s 00000000 00:05 1603810                    /drm mm object (deleted)
7f364e299000-7f364e2a9000 rw-s 00000000 00:05 1603809                    /drm mm object (deleted)
7f364e2a9000-7f364e2d1000 rw-s 00000000 00:05 1603808                    /drm mm object (deleted)
7f364e2d1000-7f364e321000 rw-s 00000000 00:05 1603806                    /drm mm object (deleted)
7f364e321000-7f364e322000 rw-s 00000000 00:05 1603805                    /drm mm object (deleted)
7f364e322000-7f364e332000 rw-s 00000000 00:05 1603804                    /drm mm object (deleted)
7f364e332000-7f364e9b2000 rw-p 00000000 00:00 0 
7f364e9b2000-7f364e9b8000 rw-s 00000000 00:05 1606487                    /drm mm object (deleted)
7f364e9b8000-7f364e9c8000 rw-s 00000000 00:05 1606486                    /drm mm object (deleted)
7f364e9c8000-7f364e9cc000 rw-s 00000000 00:05 1606485                    /drm mm object (deleted)
7f364e9cc000-7f364e9dc000 rw-s 00000000 00:05 1606484                    /drm mm object (deleted)
7f364e9dc000-7f364f05c000 rw-p 00000000 00:00 0 
7f364f05c000-7f364f060000 rw-s 00000000 00:05 1603803                    /drm mm object (deleted)
7f364f060000-7f364f068000 rw-s 00000000 00:05 1603802                    /drm mm object (deleted)
7f364f068000-7f364f070000 rw-s 00000000 00:05 1603801                    /drm mm object (deleted)
7f364f070000-7f364f078000 rw-s 00000000 00:05 1603800                    /drm mm object (deleted)
7f364f078000-7f364f080000 rw-s 00000000 00:05 1603799                    /drm mm object (deleted)
7f364f080000-7f364f088000 rw-s 00000000 00:05 1603798                    /drm mm object (deleted)
7f364f088000-7f364f090000 rw-s 00000000 00:05 1603797                    /drm mm object (deleted)
7f364f090000-7f364f098000 rw-s 00000000 00:05 1603796                    /drm mm object (deleted)
7f364f098000-7f364f0a0000 rw-s 00000000 00:05 1603795                    /drm mm object (deleted)
7f364f0a0000-7f364f0a8000 rw-s 00000000 00:05 1603794                    /drm mm object (deleted)
7f364f0a8000-7f364f0ac000 rw-s 00000000 00:05 1603793                    /drm mm object (deleted)
7f364f0ac000-7f364f0d4000 rw-s 00000000 00:05 1603792                    /drm mm object (deleted)
7f364f0d4000-7f364f0d8000 rw-s 00000000 00:05 1603791                    /drm mm object (deleted)
7f364f0d8000-7f364f0dc000 rw-s 00000000 00:05 1603790                    /drm mm object (deleted)
7f364f0dc000-7f364f0e0000 rw-s 00000000 00:05 1603789                    /drm mm object (deleted)
7f364f0e0000-7f364f1c0000 rw-s 00000000 00:05 1603785                    /drm mm object (deleted)
7f364f1c0000-7f3650000000 rw-p 00000000 00:00 0 
7f3650000000-7f3650021000 rw-p 00000000 00:00 0 
7f3650021000-7f3654000000 ---p 00000000 00:00 0 
7f3654000000-7f3654001000 rw-s 00000000 00:05 1606440                    /drm mm object (deleted)
7f3654001000-7f3654005000 rw-s 00000000 00:05 1603788                    /drm mm object (deleted)
7f3654005000-7f3654009000 rw-s 00000000 00:05 1603787                    /drm mm object (deleted)
7f3654009000-7f365400d000 rw-s 00000000 00:05 1603786                    /drm mm object (deleted)
7f365400d000-7f3654d0d000 rw-p 00000000 00:00 0 
7f3654d0d000-7f3654d12000 rw-s 00000000 00:05 1603784                    /drm mm object (deleted)
7f3654d12000-7f3654d16000 rw-s 00000000 00:05 1603783                    /drm mm object (deleted)
7f3654d16000-7f3654d1c000 rw-s 00000000 00:05 1603782                    /drm mm object (deleted)
7f3654d1c000-7f3654d21000 rw-s 00000000 00:05 1603781                    /drm mm object (deleted)
7f3654d21000-7f3654d25000 rw-s 00000000 00:05 1603780                    /drm mm object (deleted)
7f3654d25000-7f3654d29000 rw-s 00000000 00:05 1603779                    /drm mm object (deleted)
7f3654d29000-7f3654d2d000 rw-s 00000000 00:05 1603778                    /drm mm object (deleted)
7f3654d2d000-7f3654d31000 rw-s 00000000 00:05 1603777                    /drm mm object (deleted)
7f3654d31000-7f3654d35000 rw-s 00000000 00:05 1603776                    /drm mm object (deleted)
7f3654d35000-7f3654d39000 rw-s 00000000 00:05 1603775                    /drm mm object (deleted)
7f3654d39000-7f3654d3d000 rw-s 00000000 00:05 1603774                    /drm mm object (deleted)
7f3654d3d000-7f3654d41000 rw-s 00000000 00:05 1603773                    /drm mm object (deleted)
7f3654d41000-7f3654d45000 rw-s 00000000 00:05 1603772                    /drm mm object (deleted)
7f3654d45000-7f3654d49000 rw-s 00000000 00:05 1603771                    /drm mm object (deleted)
7f3654d49000-7f3654d4d000 rw-s 00000000 00:05 1603770                    /drm mm object (deleted)
7f3654d4d000-7f3654d51000 rw-s 00000000 00:05 1603769                    /drm mm object (deleted)
7f3654d51000-7f3654d55000 rw-s 00000000 00:05 1603768                    /drm mm object (deleted)
7f3654d55000-7f3654d59000 rw-s 00000000 00:05 1603767                    /drm mm object (deleted)
7f3654d59000-7f3654d5d000 rw-s 00000000 00:05 1603766                    /drm mm object (deleted)
7f3654d5d000-7f365581d000 rw-p 00000000 00:00 0 
7f365581d000-7f3655821000 rw-s 00000000 00:05 1603765                    /drm mm object (deleted)
7f3655821000-7f3655825000 rw-s 00000000 00:05 1603764                    /drm mm object (deleted)
7f3655825000-7f3655b25000 rw-s 00000000 00:05 1603762                    /drm mm object (deleted)
7f3655b25000-7f3655ba5000 rw-p 00000000 00:00 0 
7f3655ba5000-7f3655ba6000 rw-s 00000000 00:05 1606483                    /drm mm object (deleted)
7f3655ba6000-7f3655baa000 rw-s 00000000 00:05 1606482                    /drm mm object (deleted)
7f3655baa000-7f3655baf000 rw-s 00000000 00:05 1606481                    /drm mm object (deleted)
7f3655baf000-7f3655bc3000 rw-s 00000000 00:05 1606480                    /drm mm object (deleted)
7f3655bc3000-7f3655bc7000 rw-s 00000000 00:05 1606479                    /drm mm object (deleted)
7f3655bc7000-7f3655bd1000 rw-s 00000000 00:05 1606478                    /drm mm object (deleted)
7f3655bd1000-7f3655cb1000 rw-s 00000000 00:05 1606477                    /drm mm object (deleted)
7f3655cb1000-7f3655cd9000 rw-s 00000000 00:05 1606476                    /drm mm object (deleted)
7f3655cd9000-7f3655d19000 rw-p 00000000 00:00 0 
7f3655d19000-7f3655d1c000 rw-s 00000000 00:05 1603761                    /drm mm object (deleted)
7f3655d1c000-7f3655d21000 rw-s 00000000 00:05 1603760                    /drm mm object (deleted)
7f3655d21000-7f3655d26000 rw-s 00000000 00:05 1603759                    /drm mm object (deleted)
7f3655d26000-7f3655d2a000 rw-s 00000000 00:05 1606469                    /drm mm object (deleted)
7f3655d2a000-7f3655d2e000 rw-s 00000000 00:05 1603267                    /drm mm object (deleted)
7f3655d2e000-7f3655d3e000 rw-s 00000000 00:05 1603266                    /drm mm object (deleted)
7f3655d3e000-7f3655d43000 rw-s 00000000 00:05 1603265                    /drm mm object (deleted)
7f3655d43000-7f3655d48000 rw-s 00000000 00:05 1603264                    /drm mm object (deleted)
7f3655d48000-7f3655d4a000 rw-s 00000000 00:05 1603263                    /drm mm object (deleted)
7f3655d4a000-7f3655d4c000 rw-s 00000000 00:05 1603262                    /drm mm object (deleted)
7f3655d4c000-7f3655d4e000 rw-s 00000000 00:05 1603261                    /drm mm object (deleted)
7f3655d4e000-7f3655d50000 rw-s 00000000 00:05 1603260                    /drm mm object (deleted)
7f3655d50000-7f3655d52000 rw-s 00000000 00:05 1603259                    /drm mm object (deleted)
7f3655d52000-7f3655d54000 rw-s 00000000 00:05 1603258                    /drm mm object (deleted)
7f3655d54000-7f3655d56000 rw-s 00000000 00:05 1603257                    /drm mm object (deleted)
7f3655d56000-7f3655d58000 rw-s 00000000 00:05 1603256                    /drm mm object (deleted)
7f3655d58000-7f3655d5a000 rw-s 00000000 00:05 1603255                    /drm mm object (deleted)
7f3655d5a000-7f3655d5c000 rw-s 00000000 00:05 1603254                    /drm mm object (deleted)
7f3655d5c000-7f3655d5e000 rw-s 00000000 00:05 1603253                    /drm mm object (deleted)
7f3655d5e000-7f3655d61000 rw-s 00000000 00:05 1603252                    /drm mm object (deleted)
7f3655d61000-7f3655d65000 rw-s 00000000 00:05 1603251                    /drm mm object (deleted)
7f3655d65000-7f3655d68000 rw-s 00000000 00:05 1603250                    /drm mm object (deleted)
7f3655d68000-7f3655d6a000 rw-s 00000000 00:05 1603249                    /drm mm object (deleted)
7f3655d6a000-7f3655d6f000 rw-s 00000000 00:05 1603248                    /drm mm object (deleted)
7f3655d6f000-7f3655d7f000 rw-s 00000000 00:05 1603247                    /drm mm object (deleted)
7f3655d7f000-7f3655d87000 rw-s 00000000 00:05 1603246                    /drm mm object (deleted)
7f3655d87000-7f3655d8b000 rw-s 00000000 00:05 1603245                    /drm mm object (deleted)
7f3655d8b000-7f3655d8f000 rw-s 00000000 00:05 1603244                    /drm mm object (deleted)
7f3655d8f000-7f3655d90000 rw-s 00000000 00:05 1603243                    /drm mm object (deleted)
7f3655d90000-7f3655d92000 rw-s 00000000 00:05 1603242                    /drm mm object (deleted)
7f3655d92000-7f3655d96000 rw-s 00000000 00:05 1603241                    /drm mm object (deleted)
7f3655d96000-7f3655d99000 rw-s 00000000 00:05 1603240                    /drm mm object (deleted)Aborted

**Comment by LinuxDonald** [comment]
What version of Uh are in the repos there?

**Comment by stadnichenko-a-s** [comment]
Package manager say 2014.1+ds1-2. Now I see it is may be too old. I will try newest.

**Comment by LinuxDonald** [comment]
Yeah this version is too old. Newest is 2017.2

**Comment by stadnichenko-a-s** [comment]
Now "Unsupported fife version 0.3.unknown, at least 0.4.0 required". There is not fife 0.4.0 in repository. There is prebuilded package ?

**Comment by LinuxDonald** [comment]
https://packages.ubuntu.com/search?keywords=python-fife

**Comment by stadnichenko-a-s** [comment]
Thanks. I will try.

**Comment by nihathrael** [comment]
@stadnichenko-a-s Did that resolve the problem for you? If yes, we could close this ticket.
