### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by dufferzafar** [unknown-horizons/unknown-horizons#2762]
I'm on Ubuntu 16.04 where the repositories have the 2014 version of the game.

Is there a PPA with the latest game? 

I've also tried downloading the source and running from there, but a bunch of dependencies caused issues. `python-fife` 4 is needed while ubuntu has 3 etc.

**Comment by LinuxDonald** [comment]
Sorry only in Ubuntu 17.04 we have the lastest version in.
