### ISSUE TITLE
Can't build new warehouses / lumberjack tents

### ISSUE THREAD

**Issue by dlalinsp** [unknown-horizons/unknown-horizons#2763]
The moment I try to place a warehouse or lumberjack tent in the designated area, the _game crashes_.

**Comment by LinuxDonald** [comment]
Have you an crash log for us? And what version of uh and fife do you use?

**Comment by dlalinsp** [comment]
This is what I got when try to upgrade it to v 2017.2: 'unknown-horizons is already the newest version (2014.1+ds1-2).' on Linux Lite (based on Ubuntu 16.04).

**Comment by dlalinsp** [comment]
Can you tell me what a crash log exactly is for starters?

**Comment by dlalinsp** [comment]
And how to get it?

**Comment by dlalinsp** [comment]
[unknown-horizons-2017-12-29_20-37-44.log](https://github.com/unknown-horizons/unknown-horizons/files/1593346/unknown-horizons-2017-12-29_20-37-44.log)
Is this it?

**Comment by LinuxDonald** [comment]
How do you start uh? is there maybe an fife.log too?

**Comment by dlalinsp** [comment]
I start UH via the Lite Menu. I downloaded it via the terminal. Didn't see a file called 'fife.log'.

**Comment by LinuxDonald** [comment]
could you try to start uh in an terminal/konsole? Maybe there is an crash log then.

**Comment by dlalinsp** [comment]
This is what I got. [Download it]
[UHTC.docx](https://github.com/unknown-horizons/unknown-horizons/files/1595175/UHTC.docx)

**Comment by LinuxDonald** [comment]
What version of fife have you installed?

**Comment by dlalinsp** [comment]
I  don't know.

**Comment by LinuxDonald** [comment]
@helios2000 could you maybe take an look please?

**Comment by dlalinsp** [comment]
Thanks for your help, _LinuxDonald_. I am going to uninstall UH and wait for it to be fixed before I play it.

Cheers.
