### ISSUE TITLE
Build a flatpak, maybe?

### ISSUE THREAD

**Issue by sanchitsamuel** [unknown-horizons/unknown-horizons#2775]
Are you guys planning to build and distribute as flatpak?

**Comment by LinuxDonald** [comment]
At the moment no. We don't have an maintainer for it.

**Comment by tintou** [comment]
I'm considering to make the FIFE version of Unknown Horizons available as Flatpak via Flathub, would you agree?
I think that it might attract more people to play Unknown Horizons and hopefully more developers for the Godot port :slightly_smiling_face:

**Comment by LinuxDonald** [comment]
If you maintain it. You have the go from me (Project Leader)

**Comment by tintou** [comment]
Great, I've a working version in the review pipeline then https://github.com/flathub/flathub/pull/2064 :slightly_smiling_face:

**Comment by sanchitsamuel** [comment]
wow! I can help, not very smart, but I can learn :D

**Comment by tintou** [comment]
@sanchitsamuel at the time of writing I already finished the flatpak manifest
Unknown Horizons is now available on Flathub https://flathub.org/apps/details/org.unknown_horizons.UnknownHorizons
This issue can now be closed :tada:
