### ISSUE TITLE
buttons unclickable when moving mouse over tooltip

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2776]
When the mouse moves over a gui button (for example the button to build some building) a small information message appears describing the action.
When the mouse then moves over this information message, it disappears.
However, after that the button is not clickable anymore until the mouse is moved out and back in again.

This happens with many different types of buttons: Building buttons, the buttons to select the build menu or diplomacy meny etc, the cancel and confirmation buttons in the main meny.

I'm running the latest version of unknown-horizons on archlinux; manual install, with a manual install of the lates fife and with fifechan-git from the aur. Fife was compiled without CEGUI support.

**Comment by jmdejong** [comment]
I changed the title for clarity.

Where are the race conditions caused? Which functions?
It also happens when I drag slowly by the way.

Is this final solution something that can be done in UH or would it require changes in fife?

**Comment by AndyMender** [comment]
The race conditions are between individual _Tooltip/ImageButton instances. I linked the code so you can inspect it if you like :). Internally, both classes track their on/off state so that's not the problem. I don't think that can be fixed on the UH side, but anyone is welcomed to try, of course.
