### ISSUE TITLE
Minimap 45 degrees rotated to map

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2784]
In the current version up in the minimap does not correspond to up in the actual map.
This is because the map is using diamond-shaped isometric presentation, while the minimap is just a square corresponding to the actual coordinates.

I have already begun working on this:
![correct_minimap_viewport](https://user-images.githubusercontent.com/7968950/38136067-463a98e8-341c-11e8-81f5-c331a2b99894.png)

The reason I'm opening this issue is that I'd like some input on how the minimap should look.
In the current minimap the corners of the map aren't drawn. The minimap will have to be resized.

How should it be resized? Downscaling the minimap or making its area larger?

If this would be used, should we still keep the setting "rotate minimap with map" around? Or can we just make rotating the default? And if we would keep it, should the standard rotation be square or diamond?

Should there be a border around the edges of the minimap?

Since the tiles aren't square, the width-height ratio of the map is different than on the minimap. Should the minimap be adapted to hae this same width-height ratio?

Those small holes are caused by some loss of precision in the rotation. If the minimap would be downscaled they would probably be fixed automatically, otherwise the precision of the minimap would have to be increased (which might have a small performance cost).

**Comment by LinuxDonald** [comment]
I think the minimap should rotate with the map rotation.
Standard Rotation maybe diamond?
Adapt the minimap.
An performence lost would not so good. But if the Minimap looks better its okay.

**Comment by jmdejong** [comment]
I found that there is a command line option `--generate-minimap`.
This option seems to be only for debugging, and is not shown in the help.
Is it ok if I remove it? This function depends on some structure that I'd rather change. Also the minimap is going to look different anyways.

I want to change `iter_minimap_points` into a member function of minimap, but the `--generate-minimap` option depends on it being an independent function.

About the performance loss: I think that could be avoided with the solution that I had in mind (making `iter_minimap_points` somewhat more sophisticated)

**Comment by LinuxDonald** [comment]
Yeah it's okay do it.

**Comment by jmdejong** [comment]
I found out that the code for the --generate-minimap option is also used to make the minimap preview from the main menu, so I'll keep it.
Minimap is looking better now. I have also made a lot of improvements for performance and mostly readability.
![better_minimap](https://user-images.githubusercontent.com/7968950/38442265-0cb9ac2c-39e8-11e8-9b68-41d4a8c58abc.png)

For making it larger or making it wider than tall I'll have to change the layout.
Also the border and background are actually an image, so it will be hard to adapt it all to a diamond shaped layout.

How do you think this looks so far?

**Comment by LinuxDonald** [comment]
It looks better :-)
