### ISSUE TITLE
--start-random-map option doesn't use random seed

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2785]
The option --start-random-map will always give the same map since the seed is not randomized.
It just stays `None`.

**Comment by AndyMender** [comment]
That is intended behavior, as far as I can tell. Here "random" does not mean that the map is selected at random from the command-line, but rather that the map was initially created as a random map. Check here for details: https://github.com/unknown-horizons/unknown-horizons/blob/9fef7c19986083f25f69f70d0dc3b8e280b81f8e/horizons/util/cmdlineoptions.py#L49
https://github.com/unknown-horizons/unknown-horizons/blob/9fef7c19986083f25f69f70d0dc3b8e280b81f8e/horizons/util/cmdlineoptions.py#L51

**Comment by jmdejong** [comment]
Alright. It seems kinda ambiguous to me but it would make sense.
It just kinda reminded me of this: https://www.xkcd.com/221/

It's indeed not really a problem since `--start-specific-random-map` with some random source could be used for a unique random map.
