### ISSUE TITLE
UI objects prevent moving the camera

### ISSUE THREAD

**Issue by iluvhalo** [unknown-horizons/unknown-horizons#2787]
### Intro
I'm sorry if this is a known issue, but it is something I noticed immediately after opening the game. I am on Windows 10, version 1709. The version of the game I am using is the one that the windows setup.exe from the main website sets up. The settings were all default except I changed the resolution to 1366x768 to match my native resolution and changed it to fullscreen. 

### Issue
 After starting the tutorial and looking around the map by moving my cursor to the edge of the screen, I noticed when I put my cursor in the top right corner to move up and right, it didn't move. It seemed like the minimap object was in the way of the boundary that is set up to move the camera. I noticed, too, that when I selected my starting ship, the ship's stat menu popped up and when I tried to pan the camera directly right, the same issue happened. Doing the same thing on the other side of the screen produced similar, but harder to notice results. You can move the camera, but there is a small gap between the objective/goal object ("Build a warehouse...") and the edge of the screen so you can still activate moving the camera, but you can still tell the object gets in the way a little bit. 

### Summary
I don't know how you guys have this code set up, but it definitely seems like the UI objects are getting in the way of the camera movement boundary. If this was a project in GIMP, I would compare it to just having things on the wrong layers. Again, sorry if this is a known issue. I searched the issue tracker for map, UI, and camera and didn't see anything that seemed to describe this. I can tell it's not a finished product, but really great job with everything you guys have done so far.

**Comment by jmdejong** [comment]
I agree. I have encountered this as problem too. I think it's just a matter of setting the size of all the UI widgets.

I do think it's important to fix [issue #2778](https://github.com/unknown-horizons/unknown-horizons/issues/2778) first.
If this issue would be changed first, it would be very likely that you can start moving the viewport by moving the mouse to the edge, but it will keep moving until you get the mouse out of the whole menu area.

**Comment by jmdejong** [comment]
fixed in #2818
