### ISSUE TITLE
Minimap Layout

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2823]
Now that the minimap is rotated like the map I have tried to change ghe dimensions and layout of the minimap area a bit:
![minimaplayout](https://user-images.githubusercontent.com/7968950/39966156-59a61418-56a7-11e8-9860-40a26904027e.png)
In code it all seems to work now, but I can't figure out what the best placement of all the overlay elements should be.
Does anyone have good suggestions on how to place them?

Currently it is still possible to use the square minimap layout if the "rotate minimap" setting is disabled.
With this new layout that wouldn't really make sense anymore, and maintaining two different layouts is impractical.
Shall I remove this setting?

Also, I tried to change the background of the minimap myself. I think it looks decent but there are still traces from the square layout. Could someone with more art skills try to improve this? The source image is here: https://github.com/unknown-horizons/gfx/blob/master/eoc/gui/minimap/new_map_bg.xcf
It needs to have a diamond shape cut out in the center of width 160 and height 120. This cutout should have a border.

Edit:
See branch minimaplayout: https://github.com/unknown-horizons/unknown-horizons/tree/minimaplayout
https://github.com/unknown-horizons/unknown-horizons/blob/minimaplayout/content/gui/xml/ingame/hud/minimap.xml

**Comment by AndyMender** [comment]
I think moving the main map area down would work so that the magnification value and the upper widgets don't overlap with the map area. There is lots of space under the map :).

**Comment by jmdejong** [comment]
It somehow feels incorrect to me to not draw the map in the middle of the circle.
The circle is mainly there to hold the map, it feels like the map should be in the centre

How about moving the rotate map buttons down instead?
![minimaplayout2](https://user-images.githubusercontent.com/7968950/39967097-2851a530-56b6-11e8-8d7e-2932ec1dab69.png)

**Comment by AndyMender** [comment]
Does the "0.5x" in the top-left part of the mini-map widget indicate game speed or magnification? If the former, apologies for the confusion earlier!

The new version you proposed ("rotate map" buttons under the map) looks a lot better, I reckon.

**Comment by jmdejong** [comment]
I improved the layout in #2825 
Should we close this or keep it open for improving the minimap background? Or would another layout be better?

**Comment by LinuxDonald** [comment]
Close
