### ISSUE TITLE
Win x64 Installation

### ISSUE THREAD

**Issue by stefanionescu** [unknown-horizons/unknown-horizons#2831]
Hey there,

I'm a real beginner especially in Python.

I try to install fifeengine on a Win x64 machine using the Fife SDK. I saw that Fife SDK comes with Python 2.7 but I need 3.5+ to run UH.

I checked the Developer Manual but I am still not sure about how I can use a different Python version than the one in the SDK.

Can you please point me to the instructions where I can use a Python 3.5+ version to run the game?

**Comment by LinuxDonald** [comment]
I think we don't have yet an Manuel how to install UH on Windows. To use the git version. At the moment I do think have the big time to write it. But you would like to need compile fife by yourself. I will update the fife sdk this week. The best is that you wait until I'm done. I could create too an UH git version installer.

**Comment by LinuxDonald** [comment]
Our current build pre-built fife for windows can't create because of errors and lastest fife version would be needed for uh. I must first fix the fife windows compile problem.

**Comment by stefanionescu** [comment]
Got it, I'll wait for it

**Comment by stefanionescu** [comment]
Ok another noob question: can I have 32 bit version of Python working on a 64 bit windows machine?

**Comment by jmdejong** [comment]
Yes. As far as I know 64bit windows can run all 32bit programs.

**Comment by stefanionescu** [comment]
Thank you, let me test the new SDK and I'll come with feedback

**Comment by LinuxDonald** [comment]
Feedback would be nice. For the next release of UH and fifengine we plan to release 64 bit version too for Windows.

**Comment by LinuxDonald** [comment]
The sdk will be delayed by one day. I dont had enough time to make it done. Appveyor needs to long time to make builds done.

**Comment by stefanionescu** [comment]
No problem

**Comment by LinuxDonald** [comment]
Fife SDK: https://ci.appveyor.com/api/buildjobs/ajdy50jgpf2ltcnf/artifacts/_build%2FFifeSDK-0.2.181-Setup-VC14-x86.exe

**Comment by LinuxDonald** [comment]
UH 2018.1-git Installer (includes fife and own python3 with all needed dependencies): https://ci.appveyor.com/api/buildjobs/hn80cq368yxvs052/artifacts/_build%2FUnknown-Horizons-2018.1-git.172-Setup-VC14-x86.exe

**Comment by LinuxDonald** [comment]
Both are not tested by me. Feedback is welcome :)

**Comment by stefanionescu** [comment]
@LinuxDonald When I install Fife SDK with Python 2, python is present in the fife folder, but when I install the SDK with Python 3 the python folder is not there.

Why not also put python 3 inside the fife SDK?

**Comment by LinuxDonald** [comment]
I will add it.

**Comment by LinuxDonald** [comment]
Here is the newest fixed sdk. We dont provide at the moment an include python. https://ci.appveyor.com/api/buildjobs/c4wibdcxt1c8ve5i/artifacts/_build%2FFifeSDK-0.2.184-Setup-VC14-x86.exe

**Comment by stefanionescu** [comment]
Ok let me have a look

**Comment by LinuxDonald** [comment]
@stefanionescu had you already time for testing?

**Comment by LinuxDonald** [comment]
Sorry that you have problems. But we dont support this version of UH anymore. We are working on an new version. That use now godot engine instand of fife. But we dont have yet an playable version of it.
https://github.com/unknown-horizons/godot-port
