### ISSUE TITLE
editor brush resets when moving cursor over brush selection widget

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2839]
If you reset the cursor to the normal cursor in the editor (by right clicking), then move the cursor over the brush selector widget (without clicking anything) and then back to the main view, the cursor turns into the tilelayer brush again by itself.
This makes it somewhat harder to click buttons in another menu (like the 'save map' button).

**Comment by Rootyjr** [comment]
I think I fixed this issue, though I'm still waiting on the pull request.

**Comment by LinuxDonald** [comment]
Should be fixed with: https://github.com/unknown-horizons/unknown-horizons/pull/2864
