### ISSUE TITLE
Update Fife in travis

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2841]
Currently gui tests fail with the message `AttributeError: 'SelectionTool' object has no attribute 'setGlobalListener'`.
This makes sense since the method `IMouseListener.setGlobalListener` was added in a recent change to the development version of Fife.
Can we update Fife in travis so that it includes this method?
Alternatively we could try to make a dummy implementation of that method.

**Comment by LinuxDonald** [comment]
@MasterofJOKers could you maybe update the fife packages for travis please?

**Comment by MarkusHackspacher** [comment]
See https://github.com/unknown-horizons/unknown-horizons/pull/2872
I use the new fife paket 0.4.1+git20180904-2 from debian sid.

**Comment by LinuxDonald** [comment]
Please fix the typo than I can merge it.

**Comment by MarkusHackspacher** [comment]
@LinuxDonald :  What you mean with fix the typo?

**Comment by LinuxDonald** [comment]
You have on one line python3.56 ;)

**Comment by LinuxDonald** [comment]
Fixed with: https://github.com/unknown-horizons/unknown-horizons/pull/2872
