### ISSUE TITLE
Ships floating on an island

### ISSUE THREAD

**Issue by CrafterSvK** [unknown-horizons/unknown-horizons#2862]
![snimka obrazovky_2018-07-17_10-27-13](https://user-images.githubusercontent.com/8365659/42813779-5ed52dae-89c2-11e8-9360-ea1c87e849fa.png)
Ship floated all around an island. If I did a spiral map they went like the island was never there.

**Comment by yhoyhoj** [comment]
I think you just reproduced #2859 ! No one had yet, so thanks for reporting.  
Could you give more information about your setup ? Especially what version of fife you use.

**Comment by CrafterSvK** [comment]
0.4.1.r492.gfa6ea6d2 from Archlinux AUR (fife-git) package.

**Comment by yhoyhoj** [comment]
Thanks, almost the same as mine (r491).
Do you agree it's a duplicate of #2859 ?

**Comment by CrafterSvK** [comment]
Yeah I am absolutely sorry. My bad. Closing issue.
