### ISSUE TITLE
Update polib to 1.1.0

### ISSUE THREAD

**Issue by MarkusHackspacher** [unknown-horizons/unknown-horizons#2873]
Hello,
is it possible update polib to version 1.1.0, in horizons/ext/ and requirements.txt?
Now is polib Version 1.0.8.
The file is in https://bitbucket.org/izi/polib/commits/branch/default

Because with that update can we use the actual isort version 4.3.4 (now 4.2.13).

**Comment by LinuxDonald** [comment]
If there is no api break it should be okay
