### ISSUE TITLE
Broken link on wiki's coding style page

### ISSUE THREAD

**Issue by koutoftimer** [unknown-horizons/unknown-horizons#2876]
https://github.com/unknown-horizons/unknown-horizons/wiki/Coding-style "Nice examples on {foo}.format usage" link is broken

**Comment by LinuxDonald** [comment]
@MarkusHackspacher have you maybe an link that works?

**Comment by koutoftimer** [comment]
@MarkusHackspacher so it can be deleted?

**Comment by LinuxDonald** [comment]
Deleted
