### ISSUE TITLE
setup.py crashes (Linux)

### ISSUE THREAD

**Issue by margoeth** [unknown-horizons/unknown-horizons#2877]
When trying to run setup.py in fails with the following message

File "setup.py", line 34, in <module>
    from horizons.constants import VERSION
  File "unknown-horizons/horizons/constants.py", line 702
SyntaxError: Non-ASCII character '\xd8' in file unknown-horizons/horizons/constants.py on line 702, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

The branch used is master, system is Debian GNU/Linux 9.5

**Comment by LinuxDonald** [comment]
@MarkusHackspacher could you maybe fix this please?

**Comment by koutoftimer** [comment]
I'd like to work on it, I'm using same OS.

**Comment by LinuxDonald** [comment]
Okay than do it :-)

**Comment by MarkusHackspacher** [comment]
Please use python3.

I got the same fault if I use python2
```
$ python2 setup.py 
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    from horizons.constants import VERSION
  File "unknown-horizons/horizons/constants.py", line 702
SyntaxError: Non-ASCII character '\xd8' in file unknown-horizons/horizons/constants.py on line 702, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

$ python3 setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by LinuxDonald** [comment]
UH need min Python3 3.5

**Comment by LinuxDonald** [comment]
Closing that.
