### ISSUE TITLE
help! after like 3 minutes the game crashes every time!

### ISSUE THREAD

**Issue by tallestdavid** [unknown-horizons/unknown-horizons#2883]
:( cant play at all.

**Comment by LinuxDonald** [comment]
Hey we need more infos. What OS? And maybe an crash log or something.

**Comment by tallestdavid** [comment]
i7 4770k gtx 1060 6GB 16GB ram 64 bit
:) the game is laggy as well :c

**Comment by LinuxDonald** [comment]
What os? Windows or Linux?

**Comment by tallestdavid** [comment]
windows 10

**Comment by jmdejong** [comment]
Which version of Unknown Horizons did you install?

Can you share the logs from the crashes?
You can find your logs in `My Games\unknown-horizons\log\`

**Comment by tallestdavid** [comment]
if I share on one drive would I give you permission to view my whole drive or that one file? I never shared anything on there since its has personal informations and passwords.

**Comment by tallestdavid** [comment]
also the current one.

**Comment by baka0815** [comment]
Just copy & paste the log here, no need to share your one drive.
If your log is multiple MB or GB in size maybe just the last 100 lines or so are sufficient.

**Comment by LinuxDonald** [comment]
An fresh log should be max 1 or 2 MB.

**Comment by Exerotris** [comment]
Does your mouse have a horizontal click sensor on the mouse wheel, this may cause the game to crash when pressed my accident.

**Comment by LinuxDonald** [comment]
I think that but is fixed in our dev Version. But next stable release will come next year.

**Comment by jmdejong** [comment]
@tallestdavid You will probably need to build the code from source (dev version) before we can help you with any problems.
There are many improvements in the dev version that aren't in the last released version.
The codebase has changed so much since the latest release that it is not practical for us to improve on that.

Coming to think of it, I could probably still fix the horizontal scrolling issue easily; that's just adding 2 empty methods.

**Comment by tallestdavid** [comment]
dang posting info of the log crashes the site for me haha xD

**Comment by tallestdavid** [comment]
Deer(id=1000013;worldid=103363)(state=working)(health=66) finished working
Production(state=producing;prodline=ProductionLineData(lineid=17)) _produce
Production(state=producing;prodline=ProductionLineData(lineid=17)) _produce Adding callback in 400 time
Deer(id=1000013;worldid=103363)(state=working)(health=66) end_job - waiting for new search_job
Deer(id=1000013;worldid=103363)(state=idle)(health=66) end_job; health: 66
S(t:58806): SchedCb(<bound method Unit[1000013].finish_working of <horizons.world.ingametype.Unit[1000013] object at 0x24F23870>> on Deer(id=1000013;worldid=103347)(state=working)(health=30))
Deer(id=1000013;worldid=103347)(state=working)(health=30) finished working
Production(state=producing;prodline=ProductionLineData(lineid=17)) _produce
Production(state=producing;prodline=ProductionLineData(lineid=17)) _produce Adding callback in 400 time
Deer(id=1000013;worldid=103347)(state=working)(health=30) end_job - waiting for new search_job
Deer(id=1000013;worldid=103347)(state=idle)(health=30) end_job; health: 30
S(t:58806): SchedCb(<bound method Producer.update_capacity_utilization of <horizons.world.production.producer.Producer object at 0x15D8D450>> on Producer(owner: House(id=3;worldid=100694)))
S(t:58806): SchedCb(<bound method Producer.update_capacity_utilization of <horizons.world.production.producer.Producer object at 0x16A7C1B0>> on Producer(owner: House(id=3;worldid=101859)))
S(t:58806): SchedCb(<bound method Unit[1000002].search_job of <horizons.world.ingametype.Unit[1000002] object at 0x16CFD150>> on BuildingCollector(id=1000002;worldid=102293)(state=idle))
BuildingCollector(id=1000002;worldid=102293)(state=idle): found no possible job, retry in 32 ticks
S(t:58806): SchedCb(<bound method Unit[1000022].search_job of <horizons.world.ingametype.Unit[1000022] object at 0x1A5C5250>> on DisasterRecoveryCollector(id=1000022;worldid=102294)(state=idle))
DisasterRecoveryCollector(id=1000022;worldid=102294)(state=idle): found no possible job, retry in 32 ticks
S(t:58806): SchedCb(<bound method Unit[1000009].search_job of <horizons.world.ingametype.Unit[1000009] object at 0x1A5D46D0>> on FieldCollector(id=1000009;worldid=101337)(state=idle))
FieldCollector(id=1000009;worldid=101337)(state=idle): found no possible job, retry in 32 ticks
S(t:58806): SchedCb(<bound method Unit[1000011].search_job of <horizons.world.ingametype.Unit[1000011] object at 0x1A60AF70>> on SettlerCollector(id=1000011;worldid=102715)(state=idle))
SettlerCollector(id=1000011;worldid=102715)(state=idle): found no possible job, retry in 32 ticks
S(t:58806): (_move_tick,103243)
S(t:58806): (_move_tick,103224)
S(t:58806): SchedCb(Callback(<bound method ProductionOverview._refresh_tick of <horizons.gui.widgets.productionoverview.ProductionOverview object at 0x272B7350>>, (), {}) on <horizons.gui.widgets.productionoverview.ProductionOverview object at 0x272B7350>)
S(t:58806): (_move_tick,103327)
S(t:58806): (_move_tick,103313)
S(t:58806): (_move_tick,103121)
S(t:58806): (_move_tick,103123)
S(t:58806): (_move_tick,100003)
S(t:58806): (_move_tick,100000)
S(t:58806): SchedCb(<bound method InventoryChecker.check_inventory_changed of <horizons.util.inventorychecker.InventoryChecker object at 0x2384D3B0>> on <horizons.util.inventorychecker.InventoryChecker object at 0x2384D3B0>)
S(t:58806): (_move_tick,103260)
S(t:58806): (_move_tick,103342)
S(t:58806): (_move_tick,103071)
Scheduler: finished tick 58806
Scheduler: tick 58807, cbs: 15
S(t:58807): SchedCb(<bound method Production._finished_producing of <horizons.world.production.production.Production object at 0x16EBE890>> on Production(state=producing;prodline=ProductionLineData(lineid=17)))
Production(state=producing;prodline=ProductionLineData(lineid=17)) finished
S(t:58807): SchedCb(<bound method Production._finished_producing of <horizons.world.production.production.Production object at 0x17407810>> on Production(state=producing;prodline=ProductionLineData(lineid=17)))
Production(state=producing;prodline=ProductionLineData(lineid=17)) finished
S(t:58807): SchedCb(<bound method Production._finished_producing of <horizons.world.production.production.Production object at 0x16B85270>> on Production(state=producing;prodline=ProductionLineData(lineid=17)))
Production(state=producing;prodline=ProductionLineData(lineid=17)) finished
S(t:58807): SchedCb(<bound method Unit[1000013].finish_working of <horizons.world.ingametype.Unit[1000013] object at 0x273B3DD0>> on Deer(id=1000013;worldid=103316)(state=working)(health=102))
Deer(id=1000013;worldid=103316)(state=working)(health=102) finished working
Production(state=producing;prodline=ProductionLineData(lineid=17)) _produce
Production(state=producing;prodline=ProductionLineData(lineid=17)) _produce Adding callback in 400 time
Deer(id=1000013;worldid=103316)(state=working)(health=102) end_job - waiting for new search_job
Deer(id=1000013;worldid=103316)(state=idle)(health=102) end_job; health: 102
S(t:58807): SchedCb(<bound method Producer.update_capacity_utilization of <horizons.world.production.producer.Producer object at 0x1678BDD0>> on Producer(owner: Hut(id=3;worldid=101739)))
S(t:58807): SchedCb(<bound method Producer.update_capacity_utilization of <horizons.world.production.producer.Producer object at 0x2303E9D0>> on Producer(owner: Tent(id=3;worldid=102329)))
S(t:58807): SchedCb(<bound method Unit[1000011].search_job of <horizons.world.ingametype.Unit[1000011] object at 0x24BC81B0>> on SettlerCollector(id=1000011;worldid=102551)(state=idle))
SettlerCollector(id=1000011;worldid=102551)(state=idle): found no possible job, retry in 32 ticks
S(t:58807): (_move_tick,103334)
S(t:58807): (_move_tick,103162)
S(t:58807): (_move_tick,103387)
S(t:58807): (_move_tick,103378)
S(t:58807): (_move_tick,103267)
Deer(id=1000013;worldid=103267)(state=moving_to_target)(health=122): movement finished. calling callbacks ['<function begin_working at 0x04460EB0>']
Deer(id=1000013;worldid=103267)(state=moving_to_target)(health=122) begins working
S(t:58807): (_move_tick,102148)
S(t:58807): (_move_tick,103213)
S(t:58807): SchedCb(Callback(<bound method ProductionFinishedIconManager.__render_icon of <horizons.world.managers.productionfinishediconmanager.ProductionFinishedIconManager object at 0x1A460490>>, (<horizons.world.ingametype.Building[8] object at 0x2465F7B0>, 'produced_resource_4_1c08067a-9ed3-4772-a775-2c282879b99b', 4, 1), {}) on <horizons.world.managers.productionfinishediconmanager.ProductionFinishedIconManager object at 0x1A460490>)
Scheduler: finished tick 58807
Scheduler: tick 58808, cbs: 10
S(t:58808): SchedCb(<bound method Production._finished_producing of <horizons.world.production.production.Production object at 0x269C0FD0>> on Production(state=producing;prodline=ProductionLineData(lineid=16)))
Production(state=producing;prodline=ProductionLineData(lineid=16)) finished
Production(state=producing;prodline=ProductionLineData(lineid=16)) _produce
Production(state=producing;prodline=ProductionLineData(lineid=16)) _produce Adding callback in 720 time
S(t:58808): SchedCb(<bound method Producer.update_capacity_utilization of <horizons.world.production.producer.Producer object at 0x17644B30>> on Producer(owner: Hut(id=3;worldid=102428)))
S(t:58808): SchedCb(<bound method Producer.update_capacity_utilization of <horizons.world.production.producer.Producer object at 0x176D5110>> on Producer(owner: Hut(id=3;worldid=102714)))
S(t:58808): SchedCb(<bound method Unit[1000013].search_job of <horizons.world.ingametype.Unit[1000013] object at 0x23912B90>> on Deer(id=1000013;worldid=103328)(state=idle)(health=114))
Deer(id=1000013;worldid=103328)(state=idle)(health=114) search job
found path: [(19, 135), (18, 136), (17, 137), (16, 138), (15, 138)]
Deer(id=1000013;worldid=103328)(state=idle)(health=114) prepares job Job(<horizons.world.ingametype.Building[17] object at 0x1578BF30>, [ResListEntry(res=12, amount=1, target_inventory_full=True)])
S(t:58808): SchedCb(<bound method Unit[1000011].search_job of <horizons.world.ingametype.Unit[1000011] object at 0x259247B0>> on SettlerCollector(id=1000011;worldid=102854)(state=idle))
SettlerCollector(id=1000011;worldid=102854)(state=idle): found no possible job, retry in 32 ticks
S(t:58808): (_move_tick,103281)
S(t:58808): (_move_tick,102313)
S(t:58808): (_move_tick,102098)
S(t:58808): (_move_tick,100691)
S(t:58808): SchedCb(<bound method InventoryChecker.check_inventory_changed of <horizons.util.inventorychecker.InventoryChecker object at 0x16590310>> on <horizons.util.inventorychecker.InventoryChecker object at 0x16590310>)
Scheduler: finished tick 58808

**Comment by LinuxDonald** [comment]
Should be fixed with 2019.1. Release is in around 2 weeks.

https://github.com/unknown-horizons/unknown-horizons/issues/2700
