### ISSUE TITLE
Savegame incompatibility

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2888]
I believe that the savegame data in the latest master is incompatible with 2017.02
I'm not sure about it though.

Should we increase the savegame revision number?
Or should we try to make it compatible first?

**Comment by baka0815** [comment]
What makes you believe that it's the case?

**Comment by jmdejong** [comment]
I can not load a savegame from the 2017.2 version with the latest master.
This doesn't surprise me since the uh code has changed a lot.
The savegame revision number is meant to be increased whenever we have a situation of incompatible savegames

**Comment by jmdejong** [comment]
Done.
I allowed upgrading savegame version 76 to 77 (even though the 2017.2 savegames with savegame version 76 don't work anymore) because otherwise we would break the savegames of everyone who has been playing the github version over the last year.

I also updated the changelog by the way
