### ISSUE TITLE
Exception on startup on Arch Linux

### ISSUE THREAD

**Issue by pau1ie** [unknown-horizons/unknown-horizons#2894]
On following the simple install instructions on release 2019.1 I discovered I had to
```
pip install future
pip install pyyaml
```
But even then it fails:

```$ ./run_uh.py
Traceback (most recent call last):
  File "./run_uh.py", line 381, in <module>
    main()
  File "./run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "/home/paul/Programs/unknownhorizons/unknown-horizons-2019.1/horizons/main.py", line 113, in start
    horizons.globals.fife = Fife()
  File "/home/paul/Programs/unknownhorizons/unknown-horizons-2019.1/horizons/engine/engine.py", line 50, in __init__
    self.init_logging()
  File "/home/paul/Programs/unknownhorizons/unknown-horizons-2019.1/horizons/engine/engine.py", line 140, in init_logging
    self._log = fifelog.LogManager(self.engine, log_to_prompt, log_to_file)
  File "/usr/lib/python3.7/site-packages/fife/extensions/fifelog.py", line 44, in __init__
    self.lm.setLogToPrompt(promptlog)
TypeError: in method 'LogManager_setLogToPrompt', argument 2 of type 'bool'
```

**Comment by pau1ie** [comment]
I used the install from source instructions on the current git versions of fife. Pretty much as per
https://github.com/unknown-horizons/unknown-horizons/wiki/Linux#install-from-source, but followed the more detailed http://docs.fifengine.net/developer-manual/en/#_building_fifengine_on_linux
I didn't install pyenet as I wanted to play single player.

**Comment by LinuxDonald** [comment]
Do you use fifechan-git lastest fifengine-git lastets and UH min version 2019.1?

**Comment by zezinho42** [comment]
I have the same crash packaging it for mageia, with latest tarballs.
fifechan-0.1.5
fife-0.4.2
UH 2019.1

First log launching with Hardware Open GL 2.1
Second log with LIBGL_ALWAYS_SOFTWARE=1 unknown-horizons -d

[unknown-horizons-2019-01-17_18-10-27.log](https://github.com/unknown-horizons/unknown-horizons/files/2769805/unknown-horizons-2019-01-17_18-10-27.log)
[unknown-horizons-2019-01-17_18-11-37.log](https://github.com/unknown-horizons/unknown-horizons/files/2769806/unknown-horizons-2019-01-17_18-11-37.log)

**Comment by zezinho42** [comment]
Ok, so for the second one I will continue in the 2892 bug report.
But for the first one, does UH accept OpenGL 2.1 hardware (Intel HD from 2010 in my system)?

**Comment by LinuxDonald** [comment]
i think yes but i dont have test hardware here.

**Comment by jmdejong** [comment]
@pau1ie I think you problem is in the settings.
You should go to your settings file (`$HOME/.config/unknown-horizons/settings.xml` by default) and ensure that the entry for "LogToPrompt" is either `True` or `False`.

If your settings file is more messed up, just copy the default from https://github.com/unknown-horizons/unknown-horizons/blob/master/content/settings-template.xml

**Comment by zezinho42** [comment]
> i think yes but i dont have test hardware here.

I have fixed the atlas.sql missing, but unfortunately I can just confirm that UH just crashes in GL2 hardware. I could try it with software rendering, and it is not too bad, so an enhancement could be to switch to software mode whan an extension is missing ;-)

**Comment by pau1ie** [comment]
@jmdejong Thanks, that fixed it. For some reason that variable was defined as an integer rather than boolean. Maybe I had an old config left over from ages ago. I'm happy to close this but I'll leave it open in case @zezinho42 needs it.

**Comment by zezinho42** [comment]
You can close it. For me this was fixed too, except the hardware limitation.
