### ISSUE TITLE
crash on quit

### ISSUE THREAD

**Issue by jakoch** [unknown-horizons/unknown-horizons#2897]
When quitting the game (on Windows), the game crashes.

> Starting Unknown Horizons
> output will be written to logfile "unknownhorizons-DATETIME.log"
> Logging to b'C:\\Users\\koch\\Documents\\My Games\\unknown-horizons\\log\\unknown-horizons-2019-01-26_17-04-04.log' and D:\Unknown-Horizons\unknown-horizons\fife.log
> Danke, dass Ihr Unknown Horizons spielt!Traceback (most recent call last):
>   File "run_uh.py", line 381, in <module>
>     main()
>   File "run_uh.py", line 127, in main
>     print(T('Thank you for using Unknown Horizons!'))
>   File "run_uh.py", line 255, in write
>     logfile.write(line)
> ValueError: I/O operation on closed file.
> 
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "run_uh.py", line 183, in excepthook
>     print('\n', T('Unknown Horizons has crashed.'), '\n')
>   File "run_uh.py", line 255, in write
>     logfile.write(line)
> ValueError: I/O operation on closed file.
> 
> Original exception was:
> Traceback (most recent call last):
>   File "run_uh.py", line 381, in <module>
>     main()
>   File "run_uh.py", line 127, in main
>     print(T('Thank you for using Unknown Horizons!'))
>   File "run_uh.py", line 255, in write
>     logfile.write(line)
> ValueError: I/O operation on closed file.
> Exception ignored in: <__main__.setup_debugging.<locals>.StdOutDuplicator object at 0x04401470>
> Traceback (most recent call last):
>   File "run_uh.py", line 258, in flush
>     logfile.flush()
> ValueError: I/O operation on closed file.

**Comment by jmdejong** [comment]
I think this is not just windows. I've had this a few times on linux as well

**Comment by LinuxDonald** [comment]
Is this bug fixed? We could do than an hot fix release.

**Comment by jmdejong** [comment]
I haven't been able to reproduce it right now and I don't remember the circumstances in which I had it earlier.
I think it would be easy to fix though if we'd move the "Thank you" print before the closing of the log file.

**Comment by LinuxDonald** [comment]
Sorry that you have problems. But we dont support this version of UH anymore. We are working on an new version. That use now godot engine instand of fife. But we dont have yet an playable version of it.
https://github.com/unknown-horizons/godot-port

**Comment by castastrophix** [comment]
I got it with a -d option.
I moved the 
if logfile:
after the 
if ret:
to print the message before we close the file and got the error on the flush 3 lines after the logfile.write(line)
