### ISSUE TITLE
Crashing on tutorial

### ISSUE THREAD

**Issue by DreamingFairy** [unknown-horizons/unknown-horizons#2900]
Game crashes when trying to play tutorial. It loads the boat at the beginning then crashes.

**Comment by jmdejong** [comment]
Probably the same as https://github.com/unknown-horizons/unknown-horizons/issues/2898

The problem has been fixed in the source code, but we still have to create a windows installer with the fix.

**Comment by DreamingFairy** [comment]
Great. Thanks for your response. How will i get the fix? Just re-download when it is released?

**Comment by LinuxDonald** [comment]
Just redownload the installer if an new one is out. I will post it in #2898
