### ISSUE TITLE
very frequent crashes making the game unplayable (win10): 4 logfiles

### ISSUE THREAD

**Issue by theGeneralTom** [unknown-horizons/unknown-horizons#2904]
[unknown-horizons-2019-02-17_20-27-33.log](https://github.com/unknown-horizons/unknown-horizons/files/2873321/unknown-horizons-2019-02-17_20-27-33.log)
[unknown-horizons-2019-02-17_20-27-51.log](https://github.com/unknown-horizons/unknown-horizons/files/2873322/unknown-horizons-2019-02-17_20-27-51.log)
[unknown-horizons-2019-02-17_20-28-04.log](https://github.com/unknown-horizons/unknown-horizons/files/2873323/unknown-horizons-2019-02-17_20-28-04.log)
[unknown-horizons-2019-02-17_20-30-06.log](https://github.com/unknown-horizons/unknown-horizons/files/2873324/unknown-horizons-2019-02-17_20-30-06.log)

**Comment by jmdejong** [comment]
Looks like this is the same as https://github.com/unknown-horizons/unknown-horizons/issues/2898

Have you tried the installer in the latest comment in that thread?

**Comment by theGeneralTom** [comment]
Now in tried the installer and it works. No more crashes. Thank you! :-)
