### ISSUE TITLE
Fails to run on Win 10 if installed to path containing spaces

### ISSUE THREAD

**Issue by j-richey** [unknown-horizons/unknown-horizons#2907]
After installing Unknown Horizons on Windows, launching the game from the desktop shortcut I get the following error:

```
Starting Unknown Horizons
output will be written to logfile "unknownhorizons-DATETIME.log"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
```

When installing the game I changed the install path from ``C:\Unknown-Horizons`` to  ``C:\Program Files\Unknown-Horizons``. I suspect the space in the path is causing this problem.

**Operating System:** Windows 10 Home
**Unknown Horizons version:** Unknown-Horizons-2019.1.214-Setup-VC15-x86.exe obtained from http://unknown-horizons.org/downloads/

## Steps to Reproduce

1.  Run the Unknown Horizons installer: ``Unknown-Horizons-2019.1.214-Setup-VC15-x86.exe``.
2.  When prompted for an instillation location select ``C:\Program Files\Unknown-Horizons`` (or any location containing a space).
3.  Launch the game from the desktop shortcut.

## Expected Behavior
The game should run if installed to ``C:\Program Files``. This is a common place to put Windows applications.

## Workaround
I was able to run the game by editing the shortcut's path from: 
  ``"C:\Program Files\Unknown-Horizons\unknown-horizons\run_uh.bat"``
to:
  ``"C:\Program Files\Unknown-Horizons\python\python.exe" run_uh.py``

**Comment by LinuxDonald** [comment]
Sorry that you have problems. But we dont support this version of UH anymore. We are working on an new version. That use now godot engine instand of fife. But we dont have yet an playable version of it.
https://github.com/unknown-horizons/godot-port
