### ISSUE TITLE
Incorrect Doctor tooltip

### ISSUE THREAD

**Issue by Wuzzy2** [unknown-horizons/unknown-horizons#2926]
The doctor building has the following tooltip:

>  Treats diseases. Consumes herbs.

This is wrong. The doctor consumes medical herbs, not herbs. Herbs and medical herbs are 2 separate resources.

* herbs: come from herbay
* medical herbs: farm turns herbs to medical herbs

Version: 2019.1.

**Comment by Istackz** [comment]
@Wuzzy2 Do you know which file contains this issue in the code?

**Comment by artism90** [comment]
https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/i18n/objecttranslations.py#L127
