### ISSUE TITLE
Incorrect tobacco-related tooltips

### ISSUE THREAD

**Issue by Wuzzy2** [unknown-horizons/unknown-horizons#2928]
The tobacconist building has the following tooltip:

> Produces tobaccos out of tobacco.

This is wrong. In reality, this building produces tobaccos out of tobacco *leaves*.

---

The tobacco field has the following tooltip:

> Produces tobacco. Needs a farm.

Also wrong. It produces tobacco plants.

Version: 2019.1.

**Comment by Istackz** [comment]
Do you know where the line and file this issue is located in? @Wuzzy2

**Comment by Wuzzy2** [comment]
Sigh. What's the point of thse questions? These strings can be trivially grepped …

ANYWAY:

* `content/objects/buildings/fields/tobaccofield.yaml`
* `content/objects/buildings/tobacconist.yaml`
