### ISSUE TITLE
Forum is broken

### ISSUE THREAD

**Issue by Wuzzy2** [unknown-horizons/unknown-horizons#2931]
https://forum.unknown-horizons.org/

I get “502 Bad Gateway”. (also with `http://`)

**Comment by LinuxDonald** [comment]
I will remove all links about the forum. Because it no one used it.

**Comment by clrg** [comment]
Maybe you guys want a forum on the [FreeGameDev forums](https://forum.freegamedev.net/), a bit like SuperTux or STK?

**Comment by Sawyer48** [comment]
Good idea to both.

**Comment by clrg** [comment]
What layout would you like? Just a simple one? "General" & "Development"?

**Comment by siccegge** [comment]
@LinuxDonald want any data from the old system to store somehwere? otherwise I'm just going to kill it ;-)

**Comment by LinuxDonald** [comment]
You can kill it.

**Comment by LinuxDonald** [comment]
@clrg for the first an simple one would be nice.

**Comment by clrg** [comment]
Ok, I'll set it up. You guys will need to register and give me your usernames so I can add you as mods to the forum.

**Comment by Wuzzy2** [comment]
Just amazing!

**Comment by clrg** [comment]
https://forum.freegamedev.net/viewforum.php?f=100

**Comment by LinuxDonald** [comment]
Can you give me mod rights or something? Same username as here.

**Comment by Wuzzy2** [comment]
The website link in the forum description points to Valyria Tear homepage.

**Comment by Wuzzy2** [comment]
OK, there's now a new forum, great!

The forum works now.

New issue created here: https://github.com/unknown-horizons/unknown-horizons.github.io/issues/23
