### ISSUE TITLE
Can you please release your game in AppImage format?

### ISSUE THREAD

**Issue by winterwolf** [unknown-horizons/unknown-horizons#2933]
Building from source it's a real PAIN! I waste a lot of time to get some unknown errors when building dependencies and can't provide any info because can't endure it longer. I'm just a user and wanna just play a game, I'm not a hacker! -__-

**Comment by LsHallo** [comment]
This is a project since 2017: https://github.com/unknown-horizons/unknown-horizons/projects/1
Not much has happened since as I can tell. I'm not on mac myself so I can not help with that endeavor.

**Comment by davidhealey** [comment]
An app image would be very helpful.

**Comment by LinuxDonald** [comment]
Sorry that you have problems. But we dont support this version of UH anymore. We are working on an new version. That use now godot engine instand of fife. But we dont have yet an playable version of it.
https://github.com/unknown-horizons/godot-port
