### ISSUE TITLE
Removed Package function in setup.py

### ISSUE THREAD

**Issue by tobiasjaster** [unknown-horizons/unknown-horizons#2934]
Since python3.8 python-module "platform" does not include dist() already. Setup.py uses this function to determinate installation path. Similar function can be found in "distro" module or wrapped from platform.platform()-String

**Comment by jnumm** [comment]
This was fixed already, please see #2910.

**Comment by LinuxDonald** [comment]
@tobiasjaster with what version of uh you found the problem?
