### ISSUE TITLE
Mac: black screen when starting game

### ISSUE THREAD

**Issue by LauraHensel** [unknown-horizons/unknown-horizons#2941]
I installed unknown horizons from source on my macbook pro (OSX catalina). When trying to start the game, a window opens and the music starts but the window is just black. 

The only error I get is: 'fatal: No names found, cannot describe anything'

I am guessing it is something to do with the graphics but I cannot figure out what (my system is running OpenGL version 2.1 - later versions haven't been supported by macs since Sierra as far as I know). 

I run into the same issue when I try to run the fifengine demos. 
Any idea how to fix this?

**Comment by LinuxDonald** [comment]
We don't support this version of uh anymore. And it's broken for an long time on macos sorry for that. The engine we use in this version of uh don't had updates for an long time. We switched to Godot Engine. But we don't have an release yet or an playable version. We hope that we will you see on our godot version of uh when it's ready. We will support macos there. https://github.com/unknown-horizons/godot-port
