### ISSUE TITLE
How to get pyenet for playing multiplayer?

### ISSUE THREAD

**Issue by o0Julia0o** [unknown-horizons/unknown-horizons#2957]
the game tells me i have to get pyenet - how can i install it?

**Comment by LinuxDonald** [comment]
You dont need it. Pynet is only for multiplayer. And multiplayer is broken. We are working on an new version of Unknown-Horizons that will have an working multiplayer mode.

https://github.com/unknown-horizons/godot-port

**Comment by o0Julia0o** [comment]
Thank you LinuxDonald! I fond this:
"The first step is to download the enet sources from http://enet.bespin.org/ and extract it to the enet/ directory in pyenet's source directory. You could also check out the enet source code from their CVS repository."
https://github.com/aresch/pyenet

But i don´t have a enet-directory.

So multiplayer is broken? Hm... too pitty. Is there a release date for the working multiplayer-version of the game? Is it called godot oder unknown horizons?

**Comment by LinuxDonald** [comment]
I don't think it will happen this year. We are searching more devs that help us. If you have discord you can join the discord community: https://discord.gg/VX6m2ZX
