### ISSUE TITLE
Infrastructure for git snapshot releaes

### ISSUE THREAD

**Issue by ghost** [unknown-horizons/unknown-horizons#437]
This issue was reported by **dauerflucher**

Prepare infrastructure for regular git snapshot releases. Such a release will be made in future everytime a new feature is fully implemented using most recent (and sufficiently stable) git revision.

@siccegge will know what exactly will have to be changed to make this happen.

A small list of what's available so far and what isn't:
## OS/Distro
- Windows: No nightly builds so far
- Arch Linux: https://aur.archlinux.org/packages/unknown-horizons-git/
- Gentoo: http://www.unknown-horizons.org/download/linux/ see Gentoo section
- Ubuntu: No nightly builds so far
- Debian: No nightly builds so far
- OpenSuse: http://www.unknown-horizons.org/download/linux/nightly-builds/
- Fedora: http://www.unknown-horizons.org/download/linux/nightly-builds/
- Mac OS X: No nightly builds so far

**Comment by Translator5** [comment]
AUR says "NO".

```
=> ERROR: Failure while downloading https://github.com/unknown-horizons/unknown-horizons/archive/2019.1.tar.gz
    Aborting...
```
