### ISSUE TITLE
Animate fire of market place and tent1

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#523]
Would be fine if someone could animate also the fire of the market place and the tent1, like this one of the signal fire.

*[https://github.com/unknown-horizons/gfx/raw/master/kaschte/buildings/uh_sailor_tent_01-BLENDER-v257.blend tent1]

*[https://github.com/unknown-horizons/gfx/blob/master/kaschte/buildings/uh_sailor_main_square-BLENDER_v248.blend?raw=true marketplace]

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/523)

**Comment by janexx** [comment]
Animation of the fire of the sailors market place: commit 81814ae45dcd5cb398b215b70c916a81b52bec9d

**Comment by LinuxDonald** [comment]
Good work janexx :)

**Comment by janexx** [comment]
Animation of tent 1: 84e7d32358f816a69aa14b7bd645b15de3c7cbc1
All done, I close this issue.
Thx @LinuxDonald ! :)
