### ISSUE TITLE
Create Tier 3 Buildings (Settlers)

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#599]
This serves as a meta-ticket which contains links to tickets for all graphics of buildings we currently lack or would like to be updated. Only graphics which are planned to get available in tier 3 reside here.

- [x] fields for farm #625
- [x] spice field #1788
- [x] smeltery #626
- [x] toolmaker #627
- [x] tobacconist #628 #1043
- [x] blender #629
- [x] clinker church #630
- [x] clinker lighthouse #631
- [x] tavern #632
- [x] half-timbered house (residential) #633 
- [x] barracks #634
- [x] salt ponds #953
- [x] butchery #1044
- [x] cattle run #2312

**Comment by janexx** [comment]
All issues are done! :)
