### ISSUE TITLE
Blender (spices>condiments, later also tea)

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#629]
Produces condiments (out of spices). An upgraded version of same size should also produce tea, so there is no need to have it look very professionally... called 'hut' as well in first stage.

**Comment by janexx** [comment]
I am thinking to work on this issue. Have you any ideas, how the blender should look like? And what size has the building?

**Comment by stubb** [comment]
Cool. The size is 2x2, https://github.com/unknown-horizons/unknown-horizons/blob/master/content/objects/buildings/blender.yaml#L37. The blender could be a hand-operated mill. So a small normal building could do the job. For identifing it as blender some opened bags of condiments and a small collection of mill stones in front of the building would be neat.

**Comment by janexx** [comment]
Ok, thanks. Does the name as_blender0 means, that its an animation/action set? You said "a small normal building could do the job" And which building can I take for the blender as basis?

**Comment by stubb** [comment]
as_blender0 is fine, just add an idle folder inside, simliar to the winery. I had something like the bakery in mind https://github.com/unknown-horizons/unknown-horizons/blob/master/content/gfx/buildings/citizens/bakery/as_bakery0/idle/45/000.png

**Comment by janexx** [comment]
I want to show you my intermediate result of the bakery. 
http://up.unknown-horizons.org/f/?id=705&n=blender_preview.png
I am not really satisfied. So maybe someone has ideas to make it better. I took the bakery as basis. Maybe its too similiar?

**Comment by stubb** [comment]
Looks fine so far. Maybe using a different roof color, like green could help to differ more from the backery. Also adding something like a mill, for example a hand driven one like this one https://de.wikipedia.org/wiki/Handdrehm%C3%BChle could be help to identify the building. Having a person grinding the spices could be a nice work animation.

Keep up the good work!

**Comment by janexx** [comment]
Ok, thanks for your hints. A person grinding spices... puh I have to think about that. Here is the new version of the blender: http://up.unknown-horizons.org/f/?id=706&n=blender.png

**Comment by janexx** [comment]
Is there a ready person already that I can use for a work animation?

**Comment by stubb** [comment]
@janexx Sorry for the long delay. Inken made a bunch of person gfx in the past. They are in https://github.com/unknown-horizons/gfx/tree/master/inken/units Is something useful for a work animation?

**Comment by janexx** [comment]
Yes, I think the inhabitant is a good basis. Should I let the person sit on the ground like in the picture at wikipedia? Or maybe I put the millstones on a kind of table like in the second wikipedia picture? 
And how should the work animation looks like? Has the person just to grind or maybe also walk to the mill stone? When I look at the other animations, they all seem to be as simple as possible.

**Comment by stubb** [comment]
In my opinion it looks nicer if the person stands on a table. Feel free to make the animation as complex you want. Its not necessary to keep it simple.

**Comment by stubb** [comment]
@janexx Just gave it a try and fixed some small issues, like adding it to the build menu and remove the placeholder gfx (2x2) from this buildings object file, commit incoming. The only think missing is a buildmenu icon for the blender. As we use the resource icon usually we should use the icon of condiments here content/gui/icons/resources/32/047.png. Can you make a 46x46px version of it, and also the highlighted and grey scale version of the icon?

**Comment by stubb** [comment]
That's the commit I was talking about in my previous comment: 82188bbf913866ddaa72b042beac55eb70155d80

**Comment by janexx** [comment]
yes, I will make the 46x46px icons.

**Comment by stubb** [comment]
Great thanks!

**Comment by janexx** [comment]
I added the buildmenu icons with commit e13264b92705a7fdad82b14abdfa79cb4a674d8d

**Comment by stubb** [comment]
Great, thanks!
