### ISSUE TITLE
(Hack-)Fix display issue with 3x2 buildings

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#804]
Right now, the charcoal burning has size 3x2.

The actual image however has some bad offset applied (still 3x2 but not fitting the area it occupies).

[`horizons/world/building/building.py`](../blob/master/horizons/world/building/building.py#L231-L238)

Compare #542 for reference.

Your task is to understand the code mentioned above and provide a general solution.
##

**Comment by AndyMender** [comment]
This is a deeper issue with how we load images onto the building tiles. Closing as this is more explicitly discussed in #1379 and a possible hack/solution was produced.
