### ISSUE TITLE
Render our awesome new sheep

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#858]
poss contributed this truly great sheep: [http://opengameart.org/content/sheep-rigged-textured-and-animated] to OGA after our request and so we're eager to see it ingame.

Sure, not as real sheep in 2011.1 since our farms are too bugged for this, but we will use the actual sheep in each release after the next one then, needing the following action sets:
* idle_x (never used in what I can imagine, but … it's one file)
* move_x (plodding along, no grazing) used to move to a new spot after production of one wool unit finished
* work_x (grazing, no movement) used while production 1 grass -> 1 wool is active
'''where x in {0,1,2,3}''', meaning that we have four (or even more) different stages and three different sets per stage.
Totals up to 12 sets if I didn't forget any important action.

```
so we could "increment" the stage every time a production is finished
i don't need to query the storage for wool
so it could happen that the shepherd shears sheep, that haven't reached the last state
```

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/858)

**Comment by janexx** [comment]
Where is the blend file for the actual sheep action set? I can't find it. I just find the file "sheepies*" from mssssm.

**Comment by stubb** [comment]
The current pasture gfx is made by inken. Sadly there isnt the gfx in the repo. I will ask her if she can provide the blend file.

**Comment by janexx** [comment]
OK. But maybe I simply take the cattle run blend file.

**Comment by LinuxDonald** [comment]
@janexx Should we close this here and make an new Issue for an new sheep farm? (For Version 2016.02 not for 2016.01)

**Comment by janexx** [comment]
Ok, good idea!
