### ISSUE TITLE
Make water tiles unwalkable

### ISSUE THREAD

**Issue by totycro** [unknown-horizons/unknown-horizons#867]
Currently, only coastline tiles are filtered out of IslandPathNodes as well as ConsumerBuildingPath nodes; the tiles that constitute the transition to deep sea are part of the island too and therefore assumed to be walkable.

This is usually not a problem, as they can't be reached, since coastlines aren't walkable. However, if you build a boatbuilder and a warehouse on the coastline, the sea becomes directly accessible. This seems to be really really improbable, but it actually happened (cf. link).

http://img848.imageshack.us/i/97375358.png/

Therefore, we should fix this once and for all properly by making water tiles not walkable.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/867)
##

**Comment by jmdejong** [comment]
How much of this is still relevant? I thought that we moved away from using Fife pathfinding? @AndyMender do you know if this could still be a problem?

**Comment by AndyMender** [comment]
This seems to be pretty much forsaken, so I have no idea.

**Comment by LinuxDonald** [comment]
Maybe close it. Because really old report. And we have a lot code changes.
