### ISSUE TITLE
Create Tier 1 population (Sailors)

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#893]
This serves as a meta-ticket which is blocked by all graphics of the population we currently lack or would like to be updated. Only graphics which are planned to get available in tier 1 reside here. 

[> Link to originally reported Trac ticket <] (http://trac.unknown-horizons.org/t/ticket/893)

**Comment by janexx** [comment]
The link above is damaged. Is there still something to do?

**Comment by LinuxDonald** [comment]
i must create new tickt with more details for this.
