### ISSUE TITLE
The pathfinder is slow

### ISSUE THREAD

**Issue by otinn** [unknown-horizons/unknown-horizons#967]
The extreme case for is when there is no route for a ship. Attached is an example where the main ship is blocking a small ship that is on a trade route.

[> Link to originally reported Trac ticket <](http://trac.unknown-horizons.org/t/ticket/967)
**Attachment**: [slow_pathfinder.sqlite](http://up.unknown-horizons.org/f/?id=193&n=slow_pathfinder.sqlite)
##

**Comment by AndyMender** [comment]
Closing in favor of a broader solution: https://github.com/unknown-horizons/unknown-horizons/issues/2659
